pub const COMMON_ANIMALS: [&str; 255] = [
    "House Sparrow",
    "Rock Pigeon",
    "Domestic Cat",
    "Domestic Dog",
    "Brown Rat",
    "European Starling",
    "House Fly",
    "American Cockroach",
    "Norway Rat",
    "Goldfish",
    "Mallard",
    "Common Carp",
    "Cattle",
    "Sheep",
    "Goat",
    "Pig",
    "Horse",
    "Chicken",
    "Turkey",
    "Bee",
    "Butterfly",
    "Common Frog",
    "American Robin",
    "Red Fox",
    "Grey Wolf",
    "White-tailed Deer",
    "Raccoon",
    "Squirrel",
    "Eastern Cottontail",
    "Black Bear",
    "Bald Eagle",
    "Great Horned Owl",
    "Canada Goose",
    "Blue Jay",
    "Opossum",
    "Coyote",
    "Beaver",
    "Mountain Lion",
    "Bobcat",
    "Elk",
    "Moose",
    "Wild Boar",
    "American Bison",
    "Pronghorn",
    "Arctic Fox",
    "Sea Otter",
    "Atlantic Salmon",
    "Rainbow Trout",
    "Northern Pike",
    "Walleye",
    "Largemouth Bass",
    "Common Loon",
    "Great Blue Heron",
    "Red-tailed Hawk",
    "American Goldfinch",
    "Common Raven",
    "Eastern Bluebird",
    "Northern Cardinal",
    "House Wren",
    "Killdeer",
    "Pileated Woodpecker",
    "Turkey Vulture",
    "Black-capped Chickadee",
    "Wood Duck",
    "Rocky Mountain Elk",
    "Prairie Dog",
    "American Alligator",
    "Green Anole",
    "Eastern Box Turtle",
    "Garter Snake",
    "Bullfrog",
    "American Toad",
    "Eastern Newt",
    "Common Garter Snake",
    "Northern Water Snake",
    "Striped Skunk",
    "Eastern Gray Squirrel",
    "Red Squirrel",
    "Mountain Goat",
    "Bighorn Sheep",
    "American Crow",
    "Black-throated Blue Warbler",
    "White-breasted Nuthatch",
    "Baltimore Oriole",
    "Eastern Phoebe",
    "Barn Swallow",
    "Common Yellowthroat",
    "Great Egret",
    "Wood Stork",
    "Black Vulture",
    "Snowy Owl",
    "Peregrine Falcon",
    "Cooper's Hawk",
    "Sharp-shinned Hawk",
    "Northern Harrier",
    "American Kestrel",
    "Barred Owl",
    "Long-eared Owl",
    "Short-eared Owl",
    "Eastern Screech Owl",
    "Red Fox",
    "Gray Fox",
    "Armadillo",
    "Raccoon Dog",
    "European Hedgehog",
    "Eurasian Lynx",
    "Siberian Tiger",
    "Indian Elephant",
    "Asian Palm Civet",
    "Bengal Tiger",
    "Giant Panda",
    "Orangutan",
    "Chimpanzee",
    "Western Lowland Gorilla",
    "Snow Leopard",
    "African Lion",
    "Cheetah",
    "African Elephant",
    "Hippopotamus",
    "Giraffe",
    "Zebra",
    "Meerkat",
    "Warthog",
    "Honeybee",
    "Monarch Butterfly",
    "Emperor Penguin",
    "King Penguin",
    "African Grey Parrot",
    "Macaw",
    "Cockatoo",
    "Toucan",
    "Scarlet Macaw",
    "Great Hornbill",
    "Blue Jay",
    "Common Loon",
    "American Flamingo",
    "Mallard Duck",
    "Canada Goose",
    "Mute Swan",
    "Common Pheasant",
    "Red-winged Blackbird",
    "Song Sparrow",
    "House Finch",
    "Northern Mockingbird",
    "Common Grackle",
    "Yellow-rumped Warbler",
    "American Bittern",
    "Sedge Wren",
    "Eastern Meadowlark",
    "Field Sparrow",
    "Tree Swallow",
    "Cedar Waxwing",
    "Rose-breasted Grosbeak",
    "Baltimore Oriole",
    "Brown Thrasher",
    "Yellow-bellied Sapsucker",
    "Pileated Woodpecker",
    "Downy Woodpecker",
    "Hairy Woodpecker",
    "Northern Flicker",
    "Black-capped Chickadee",
    "Tufted Titmouse",
    "Carolina Wren",
    "House Wren",
    "Winter Wren",
    "Ruby-throated Hummingbird",
    "Belted Kingfisher",
    "American Robin",
    "Eastern Bluebird",
    "Gray Catbird",
    "Northern Cardinal",
    "Indigo Bunting",
    "Eastern Towhee",
    "Common Raven",
    "American Crow",
    "Turkey Vulture",
    "Black Vulture",
    "Osprey",
    "Bald Eagle",
    "Golden Eagle",
    "Red-tailed Hawk",
    "Cooper's Hawk",
    "Sharp-shinned Hawk",
    "Northern Harrier",
    "American Kestrel",
    "Peregrine Falcon",
    "Great Horned Owl",
    "Barred Owl",
    "Eastern Screech Owl",
    "Barn Owl",
    "Snowy Owl",
    "Long-eared Owl",
    "Short-eared Owl",
    "Northern Saw-whet Owl",
    "Common Nighthawk",
    "Chuck-will's-widow",
    "Eastern Whip-poor-will",
    "Ruby-throated Hummingbird",
    "Red-headed Woodpecker",
    "Red-bellied Woodpecker",
    "Yellow-bellied Sapsucker",
    "Hairy Woodpecker",
    "Downy Woodpecker",
    "Northern Flicker",
    "Pileated Woodpecker",
    "American Kestrel",
    "Merlin",
    "Prairie Falcon",
    "Gyrfalcon",
    "Eurasian Eagle-Owl",
    "European Robin",
    "Common Blackbird",
    "Eurasian Blue Tit",
    "Great Tit",
    "Common Chaffinch",
    "European Goldfinch",
    "Eurasian Jay",
    "Common Magpie",
    "Eurasian Tree Sparrow",
    "European Starling",
    "House Sparrow",
    "Rock Dove",
    "Carrion Crow",
    "Common Buzzard",
    "Eurasian Eagle-Owl",
    "Common Kestrel",
    "Peregrine Falcon",
    "Golden Eagle",
    "White-tailed Eagle",
    "Black Grouse",
    "Capercaillie",
    "Black Woodpecker",
    "Eurasian Hoopoe",
    "Common Kingfisher",
    "European Green Woodpecker",
    "European Robin",
    "Eurasian Wren",
    "Common Nightingale",
    "Eurasian Blackcap",
    "Common Whitethroat",
    "Garden Warbler",
    "Willow Warbler",
    "Common Chiffchaff",
    "Goldcrest",
    "Crested Tit",
    "Coal Tit",
    "Blue Tit",
    "Great Tit",
    "Long-tailed Tit",
    "Bearded Tit",
    "European Nuthatch",
    "Eurasian Treecreeper",
    "Eurasian Jay",
    "Common Magpie",
    "Eurasian Jackdaw",
];

pub const MAMMALS: [&str; 312] = [
    "African Elephant",
    "Bengal Tiger",
    "Blue Whale",
    "Brown Bear",
    "Cheetah",
    "Chimpanzee",
    "Dolphin",
    "Eastern Gray Squirrel",
    "European Hedgehog",
    "Giant Panda",
    "Giraffe",
    "Grizzly Bear",
    "Hippopotamus",
    "Indian Elephant",
    "Jaguar",
    "Koala",
    "Leopard",
    "Lion",
    "Macropod",
    "Mole",
    "Mountain Gorilla",
    "Norway Rat",
    "Orangutan",
    "Polar Bear",
    "Pronghorn",
    "Red Fox",
    "Rhinoceros",
    "Sea Otter",
    "Sloth",
    "Snow Leopard",
    "Squirrel Monkey",
    "Tasmanian Devil",
    "Tiger",
    "Walrus",
    "Warthog",
    "Western Lowland Gorilla",
    "White-tailed Deer",
    "Wild Boar",
    "Wolverine",
    "Wolf",
    "Woodchuck",
    "Yellow Mongoose",
    "Zebra",
    "American Bison",
    "Arctic Fox",
    "Asian Elephant",
    "Black Bear",
    "Black-footed Ferret",
    "Bottlenose Dolphin",
    "Cape Buffalo",
    "Caracal",
    "Coyote",
    "European Mole",
    "Fennec Fox",
    "Florida Panther",
    "Gazelle",
    "Gray Wolf",
    "Harbor Seal",
    "Humpback Whale",
    "Impala",
    "Indian Pangolin",
    "Jaguarundi",
    "Japanese Macaque",
    "Kangaroo",
    "Lynx",
    "Malayan Tapir",
    "Meerkat",
    "Mink",
    "Musk Ox",
    "Numbat",
    "Okapi",
    "Panda Bear",
    "Platypus",
    "Polar Fox",
    "Porcupine",
    "Prairie Dog",
    "Red Deer",
    "Red Panda",
    "Ring-tailed Lemur",
    "Sea Lion",
    "Serval",
    "Siberian Tiger",
    "Sika Deer",
    "Sperm Whale",
    "Tasmanian Tiger",
    "Thomson's Gazelle",
    "Tiger Shark",
    "Tree Kangaroo",
    "Vaquita",
    "Wapiti",
    "Water Buffalo",
    "West Indian Manatee",
    "Wildcat",
    "Wolverine",
    "Yellow-bellied Marmot",
    "Zebra Finch",
    "Zorilla",
    "Addax",
    "Agouti",
    "Alpaca",
    "American Badger",
    "American Beaver",
    "American Mink",
    "Antechinus",
    "Antelope",
    "Aoudad",
    "Aye-aye",
    "Baboon",
    "Bandicoot",
    "Barasingha",
    "Binturong",
    "Black Mamba",
    "Black Rhinoceros",
    "Blackbuck",
    "Bonobo",
    "Bongo",
    "Brown Hyena",
    "Brown-throated Sloth",
    "Buffalo",
    "Bushbaby",
    "Bushpig",
    "Camel",
    "Capuchin",
    "Caribou",
    "Cassowary",
    "Catamount",
    "Cavy",
    "Chamois",
    "Chevrotain",
    "Chinchilla",
    "Chipmunk",
    "Coati",
    "Colobus Monkey",
    "Common Buzzard",
    "Common Eland",
    "Common Genet",
    "Common Warthog",
    "Common Yellowthroat",
    "Cottontail Rabbit",
    "Cougar",
    "Crested Porcupine",
    "Dama Gazelle",
    "Desert Hedgehog",
    "Desert Tortoise",
    "Dhole",
    "Dik-dik",
    "Dingo",
    "Doberman",
    "Dugong",
    "Dwarf Mongoose",
    "Eastern Chipmunk",
    "Eastern Cottontail",
    "Eurasian Lynx",
    "Eurasian Red Squirrel",
    "Fallow Deer",
    "Fennec Fox",
    "Ferret",
    "Flat-headed Cat",
    "Flying Squirrel",
    "Fossa",
    "Fruit Bat",
    "Galápagos Sea Lion",
    "Gelada",
    "Gerenuk",
    "Giant Anteater",
    "Giant Armadillo",
    "Giant Otter",
    "Gila Monster",
    "Giraffe Weevil",
    "Goral",
    "Grant's Gazelle",
    "Gray Fox",
    "Gray Seal",
    "Greater Kudu",
    "Greater Rhea",
    "Greater Stick-nest Rat",
    "Grévy's Zebra",
    "Guinea Baboon",
    "Guinea Pig",
    "Guillemot",
    "Hamadryas Baboon",
    "Hare",
    "Harpy Eagle",
    "Hartebeest",
    "Hedgehog",
    "Hippopotamus",
    "Honey Badger",
    "Hoopoe",
    "Horse",
    "Hummingbird",
    "Hyena",
    "Iriomote Cat",
    "Indian Cobra",
    "Indian Star Tortoise",
    "Indian Wolf",
    "Indigo Bunting",
    "Indri",
    "Irish Setter",
    "Jaguarundi",
    "Japanese Macaque",
    "Javan Rhino",
    "Jerboa",
    "Kangaroo Rat",
    "Kinkajou",
    "Kiwi",
    "Koala",
    "Komodo Dragon",
    "Kudu",
    "Lemur",
    "Leopard Cat",
    "Leopard Seal",
    "Lion",
    "Little Brown Bat",
    "Llama",
    "Long-eared Owl",
    "Long-tailed Weasel",
    "Lynx",
    "Macaw",
    "Macropod",
    "Malayan Tapir",
    "Manatee",
    "Mandrill",
    "Markhor",
    "Marmoset",
    "Marten",
    "Meerkat",
    "Mink",
    "Mole",
    "Mongoose",
    "Mountain Goat",
    "Mountain Lion",
    "Mouse",
    "Mule Deer",
    "Muskrat",
    "Naked Mole Rat",
    "Numbat",
    "Nutria",
    "Okapi",
    "Opossum",
    "Orangutan",
    "Oribi",
    "Oryx",
    "Otter",
    "Paca",
    "Pangolin",
    "Panther",
    "Patagonian Mara",
    "Peccary",
    "Pika",
    "Pine Marten",
    "Platypus",
    "Polar Bear",
    "Porcupine",
    "Possum",
    "Prairie Dog",
    "Proboscis Monkey",
    "Pudu",
    "Puma",
    "Quokka",
    "Quoll",
    "Raccoon",
    "Ratel",
    "Red Deer",
    "Red Fox",
    "Red Kangaroo",
    "Red Panda",
    "Reindeer",
    "Rhinoceros",
    "River Otter",
    "Rock Hyrax",
    "Rock Wallaby",
    "Rodent",
    "Saiga Antelope",
    "Saki Monkey",
    "Sea Otter",
    "Serval",
    "Sheep",
    "Siberian Tiger",
    "Skunk",
    "Sloth Bear",
    "Snow Leopard",
    "Solenodon",
    "Spectacled Bear",
    "Squirrel",
    "Squirrel Monkey",
    "Stoat",
    "Striped Hyena",
    "Sun Bear",
    "Takin",
    "Tapir",
    "Tasmanian Devil",
    "Tarsier",
    "Tiger",
    "Tiger Salamander",
    "Tree Kangaroo",
    "Tuatara",
    "Uakari",
    "Vicuna",
    "Wapiti",
    "Water Buffalo",
    "Weasel",
    "Western Lowland Gorilla",
    "Whale",
    "White-tailed Deer",
    "Wild Boar",
    "Wildcat",
    "Wildebeest",
    "Wolverine",
    "Wolf",
    "Wombat",
    "Yak",
    "Zebra",
];

pub const BIRDS: [&str; 235] = [
    "American Robin",
    "Bald Eagle",
    "Barn Owl",
    "Barn Swallow",
    "Black-capped Chickadee",
    "Blue Jay",
    "Canada Goose",
    "Common Raven",
    "Dark-eyed Junco",
    "Eastern Bluebird",
    "European Starling",
    "Great Horned Owl",
    "House Finch",
    "House Sparrow",
    "Killdeer",
    "Mourning Dove",
    "Northern Cardinal",
    "Northern Flicker",
    "Peregrine Falcon",
    "Pileated Woodpecker",
    "Red-tailed Hawk",
    "Rock Pigeon",
    "Song Sparrow",
    "Tufted Titmouse",
    "White-breasted Nuthatch",
    "Wood Duck",
    "Yellow-rumped Warbler",
    "American Goldfinch",
    "American Crow",
    "American Kestrel",
    "American Bittern",
    "American Pipit",
    "Anna's Hummingbird",
    "Audubon's Warbler",
    "Belted Kingfisher",
    "Black-and-white Warbler",
    "Black Vulture",
    "Black-throated Blue Warbler",
    "Black-throated Green Warbler",
    "Blue-gray Gnatcatcher",
    "Blue-winged Teal",
    "Bonaparte's Gull",
    "Brown Creeper",
    "Brown-headed Cowbird",
    "Brown Thrasher",
    "Canada Warbler",
    "Canvasback",
    "Cedar Waxwing",
    "Chestnut-sided Warbler",
    "Chipping Sparrow",
    "Clark's Nutcracker",
    "Cliff Swallow",
    "Common Eider",
    "Common Goldeneye",
    "Common Loon",
    "Common Nighthawk",
    "Common Tern",
    "Dark-eyed Junco",
    "Double-crested Cormorant",
    "Downy Woodpecker",
    "Eastern Phoebe",
    "Eastern Towhee",
    "Eastern Wood-Pewee",
    "Eastern Whip-poor-will",
    "Eurasian Collared-Dove",
    "Eurasian Wigeon",
    "Evening Grosbeak",
    "Field Sparrow",
    "Fish Crow",
    "Fox Sparrow",
    "Golden-crowned Kinglet",
    "Golden-crowned Sparrow",
    "Golden Eagle",
    "Gray Catbird",
    "Great Blue Heron",
    "Great Crested Flycatcher",
    "Great Egret",
    "Greater Yellowlegs",
    "Green Heron",
    "Hairy Woodpecker",
    "Hermit Thrush",
    "Hooded Merganser",
    "House Wren",
    "Imperial Shag",
    "Indigo Bunting",
    "Killdeer",
    "King Eider",
    "Lark Sparrow",
    "Laughing Gull",
    "Least Sandpiper",
    "Least Tern",
    "Lesser Goldfinch",
    "Lincoln's Sparrow",
    "Long-eared Owl",
    "Long-tailed Duck",
    "Magnolia Warbler",
    "Mallard",
    "Marsh Wren",
    "Merlin",
    "Mourning Warbler",
    "Nashville Warbler",
    "Northern Bobwhite",
    "Northern Harrier",
    "Northern Mockingbird",
    "Northern Shoveler",
    "Northern Saw-whet Owl",
    "Northern Waterthrush",
    "Osprey",
    "Palm Warbler",
    "Pied-billed Grebe",
    "Pine Grosbeak",
    "Pine Warbler",
    "Pileated Woodpecker",
    "Purple Finch",
    "Purple Martin",
    "Red-bellied Woodpecker",
    "Red-eyed Vireo",
    "Red-necked Grebe",
    "Red-shouldered Hawk",
    "Red-winged Blackbird",
    "Ring-billed Gull",
    "Ring-necked Duck",
    "Rock Wren",
    "Rose-breasted Grosbeak",
    "Rough-legged Hawk",
    "Ruby-throated Hummingbird",
    "Ruffed Grouse",
    "Rusty Blackbird",
    "Savannah Sparrow",
    "Scarlet Tanager",
    "Semipalmated Plover",
    "Semipalmated Sandpiper",
    "Sharp-shinned Hawk",
    "Short-eared Owl",
    "Snow Bunting",
    "Solitary Sandpiper",
    "Song Sparrow",
    "Sora",
    "Spotted Towhee",
    "Swainson's Thrush",
    "Swamp Sparrow",
    "Tree Swallow",
    "Trumpeter Swan",
    "Tufted Titmouse",
    "Turkey Vulture",
    "Veery",
    "Vesper Sparrow",
    "Virginia Rail",
    "Warbling Vireo",
    "Western Meadowlark",
    "Western Tanager",
    "White-crowned Sparrow",
    "White-eyed Vireo",
    "White-throated Sparrow",
    "Wild Turkey",
    "Willet",
    "Wilson's Snipe",
    "Winter Wren",
    "Wood Thrush",
    "Woodhouse's Scrub-Jay",
    "Yellow-bellied Sapsucker",
    "Yellow-bellied Flycatcher",
    "Yellow-headed Blackbird",
    "Yellow-rumped Warbler",
    "Yellow-throated Vireo",
    "American White Pelican",
    "Black-bellied Plover",
    "Black Skimmer",
    "Black-crowned Night Heron",
    "Blue-footed Booby",
    "Brown Pelican",
    "California Condor",
    "Common Murre",
    "Cooper's Hawk",
    "Double-striped Thick-knee",
    "Eastern Kingbird",
    "European Goldfinch",
    "European Starling",
    "Frigatebird",
    "Golden Plover",
    "Great Auk",
    "Great Cormorant",
    "Green-winged Teal",
    "Herring Gull",
    "King Rail",
    "Laughing Kookaburra",
    "Laysan Albatross",
    "Leach's Storm-petrel",
    "Magnificent Frigatebird",
    "Mottled Duck",
    "Northern Goshawk",
    "Northern Lapwing",
    "Northern Wheatear",
    "Pacific Loon",
    "Pacific-slope Flycatcher",
    "Parasitic Jaeger",
    "Pied Avocet",
    "Pied Kingfisher",
    "Pomarine Jaeger",
    "Piping Plover",
    "Plumbeous Water Redstart",
    "Purple Gallinule",
    "Razorbill",
    "Red Knot",
    "Red-legged Partridge",
    "Red-throated Loon",
    "Roseate Spoonbill",
    "Ruddy Turnstone",
    "Sabine's Gull",
    "Sandhill Crane",
    "Sanderling",
    "Scarlet Ibis",
    "Semipalmated Plover",
    "Short-billed Dowitcher",
    "Snow Goose",
    "Snowy Egret",
    "Steller's Jay",
    "Stilt Sandpiper",
    "Swallow-tailed Kite",
    "Thick-billed Murre",
    "Trumpeter Finch",
    "Tufted Puffin",
    "Tundra Swan",
    "Western Grebe",
    "Western Sandpiper",
    "Whimbrel",
    "White Ibis",
    "White-tailed Ptarmigan",
    "White-winged Crossbill",
    "Wood Stork",
    "Yellow Warbler",
    "Yellow-billed Cuckoo",
    "Yellow-crowned Night Heron",
    "Yellow-headed Blackbird",
    "Zebra Finch",
];

pub const INSECTS: [&str; 241] = [
    "Ant",
    "Aphid",
    "Armyworm",
    "Bee",
    "Beetle",
    "Bumblebee",
    "Butterfly",
    "Caddisfly",
    "Cicada",
    "Cockroach",
    "Crane Fly",
    "Cranefly",
    "Damselfly",
    "Dragonfly",
    "Earwig",
    "Firefly",
    "Flea",
    "Fruit Fly",
    "Grasshopper",
    "Horsefly",
    "Ichneumon Wasp",
    "June Bug",
    "Ladybug",
    "Leafhopper",
    "Lice",
    "Locust",
    "Longhorn Beetle",
    "Luna Moth",
    "Maggot",
    "Mantis",
    "Mayfly",
    "Mosquito",
    "Moth",
    "Mud Dauber",
    "Nit",
    "Painted Lady",
    "Paper Wasp",
    "Peacock Butterfly",
    "Pillbug",
    "Pine Beetle",
    "Planthopper",
    "Queen Butterfly",
    "Red Admiral",
    "Robber Fly",
    "Scarab Beetle",
    "Scorpionfly",
    "Silverfish",
    "Skipper Butterfly",
    "Slug Caterpillar",
    "Spider Beetle",
    "Springtail",
    "Stag Beetle",
    "Stonefly",
    "Stink Bug",
    "Swallowtail Butterfly",
    "Tarantula Hawk",
    "Termite",
    "Tick",
    "Tiger Moth",
    "Tsetse Fly",
    "Walking Stick",
    "Water Strider",
    "Weevil",
    "Yellowjacket",
    "Zebra Butterfly",
    "Zygoptera",
    "Agapostemon",
    "Alfalfa Weevil",
    "Alderfly",
    "Alfalfa Butterfly",
    "Apple Maggot",
    "Asiatic Garden Beetle",
    "Atlas Moth",
    "Bark Beetle",
    "Banded Woolly Bear",
    "Banana Weevil",
    "Banded Cucumber Beetle",
    "Black Fly",
    "Blister Beetle",
    "Boxelder Bug",
    "Braconid Wasp",
    "Buck Moth",
    "Cabbage White",
    "Carpenter Bee",
    "Caterpillar",
    "Cicada Killer",
    "Clouded Sulphur",
    "Clover Mite",
    "Colorado Potato Beetle",
    "Corn Earworm",
    "Cricket",
    "Cucumber Beetle",
    "Darkling Beetle",
    "Damsel Bug",
    "Desert Locust",
    "Diamondback Moth",
    "Dobsonfly",
    "Dogbane Leaf Beetle",
    "Drone Fly",
    "Dytiscid Beetle",
    "Earwig",
    "Emerald Ash Borer",
    "European Corn Borer",
    "European Pine Sawfly",
    "Fire Ant",
    "Flea Beetle",
    "Flower Fly",
    "Giant Water Bug",
    "Giant Silk Moth",
    "Giant Swallowtail",
    "Glasswing Butterfly",
    "Goldsmith Beetle",
    "Gossamer-winged Butterfly",
    "Grasshopper Mouse",
    "Grape Leafhopper",
    "Green Darner",
    "Green Lacewing",
    "Gulf Fritillary",
    "Gyrinidae",
    "Harlequin Bug",
    "Harvester Ant",
    "Hawk Moth",
    "Hazel Leafroller",
    "Hercules Beetle",
    "Hickory Horned Devil",
    "Hoplothrips",
    "Housefly",
    "Hummingbird Moth",
    "Ichneumon Wasp",
    "Imperial Moth",
    "Indian Meal Moth",
    "Japanese Beetle",
    "Junebug",
    "Katydid",
    "King Swallowtail",
    "Lace Bug",
    "Lacewing",
    "Ladybird Beetle",
    "Leaf Beetle",
    "Lily Beetle",
    "Linden Bug",
    "Long-legged Fly",
    "Lonomia Caterpillar",
    "Luna Moth",
    "Macadamia Nut Borer",
    "Manduca Sexta",
    "Maple Leafcutter",
    "May Beetle",
    "Mealybug",
    "Midge",
    "Milkweed Bug",
    "Milkweed Butterfly",
    "Millipede",
    "Mole Cricket",
    "Monarch Butterfly",
    "Mosquito Fish",
    "Mountain Pine Beetle",
    "Mud Dauber",
    "Mugwort Aphid",
    "Musk Beetle",
    "Native Bee",
    "Net-winged Beetle",
    "Net-winged Moth",
    "Northern Flicker",
    "Oak Leafroller",
    "Oakworm Moth",
    "Olive Fruit Fly",
    "Onion Maggot",
    "Orange Sulphur",
    "Oriental Fruit Fly",
    "Oriental Leafhopper",
    "Painted Lady Butterfly",
    "Paper Wasp",
    "Parasitic Wasp",
    "Pea Aphid",
    "Peacock Butterfly",
    "Pear Psylla",
    "Pine Sawfly",
    "Pine Weevil",
    "Pine Woolly Adelgid",
    "Pineapple Mealybug",
    "Pinewood Nematode",
    "Plague Locust",
    "Plum Curculio",
    "Plum Sawfly",
    "Plum Weevil",
    "Powderpost Beetle",
    "Praying Mantis",
    "Queen Alexandra's Birdwing",
    "Red Admiral Butterfly",
    "Red Flour Beetle",
    "Red-shouldered Bug",
    "Rice Weevil",
    "Rice Worm",
    "Robber Fly",
    "Rose Chafer",
    "Rose Curculio",
    "Rose Sawfly",
    "Rusty Tussock Moth",
    "Saltmarsh Caterpillar",
    "Scorpionfly",
    "Seed Bug",
    "Seven-spot Ladybird",
    "Silkworm",
    "Silverfish",
    "Skipper Butterfly",
    "Slug Moth",
    "Slug Caterpillar",
    "Small White Butterfly",
    "Snow Flea",
    "Sphinx Moth",
    "Spittlebug",
    "Squash Bug",
    "Squash Vine Borer",
    "Stag Beetle",
    "Stink Bug",
    "Swallowtail Butterfly",
    "Tarantula Hawk",
    "Termite",
    "Thrip",
    "Tiger Beetle",
    "Tiger Moth",
    "Tomato Hornworm",
    "Tsetse Fly",
    "Turnip Moth",
    "Tussock Moth",
    "Twice-stabbed Lady Beetle",
    "Viceroy Butterfly",
    "Walnut Caterpillar",
    "Walkingstick",
    "Water Boatman",
    "Water Strider",
    "Weevil",
    "Western Corn Rootworm",
    "Western Honeybee",
    "Western Tent Caterpillar",
    "Woolly Bear",
    "Yellowjacket",
    "Zebra Butterfly",
    "Zebra Swallowtail",
    "Zoraptera",
];

pub const FISHES: [&str; 342] = [
    "Anchovy",
    "Hammerhead Shark",
    "Great White Shark",
    "Tiger Shark",
    "Bull Shark",
    "Whale Shark",
    "Blue Shark",
    "Mako Shark",
    "Sand Tiger Shark",
    "Nurse Shark",
    "Blacktip Reef Shark",
    "Port Jackson Shark",
    "Angelfish",
    "Archerfish",
    "Arowana",
    "Basa",
    "Barracuda",
    "Bass",
    "Betta",
    "Bichir",
    "Black Drum",
    "Black Ghost Knifefish",
    "Black Marlin",
    "Blue Tang",
    "Bluegill",
    "Blue Marlin",
    "Bluefish",
    "Bowfin",
    "Brook Trout",
    "Brown Trout",
    "Butterflyfish",
    "Carp",
    "Catfish",
    "Clownfish",
    "Cod",
    "Coelacanth",
    "Corydoras",
    "Crappie",
    "Crucian Carp",
    "Cunner",
    "Dace",
    "Damselfish",
    "Danio",
    "Darter",
    "Discus",
    "Dogfish",
    "Dorado",
    "Eel",
    "Electric Eel",
    "European Perch",
    "Flatfish",
    "Flounder",
    "Goby",
    "Gourami",
    "Grass Carp",
    "Grayling",
    "Gudgeon",
    "Guppy",
    "Haddock",
    "Halibut",
    "Hammerhead Shark",
    "Herring",
    "Horn Shark",
    "Horse Mackerel",
    "Indian Carp",
    "Jackfish",
    "John Dory",
    "Kissing Gourami",
    "Kingfish",
    "Koi",
    "Lamprey",
    "Lionfish",
    "Largemouth Bass",
    "Mahi-mahi",
    "Mako Shark",
    "Mandarinfish",
    "Molly",
    "Moray Eel",
    "Mullet",
    "Napoleon Wrasse",
    "Needlefish",
    "Northern Pike",
    "Nothern Snakehead",
    "Oscar",
    "Pacu",
    "Pangasius",
    "Parrotfish",
    "Perch",
    "Pike",
    "Pipefish",
    "Plaice",
    "Pufferfish",
    "Pygmy Seahorse",
    "Rainbow Trout",
    "Red Drum",
    "Red Snapper",
    "Roach",
    "Rockfish",
    "Sailfish",
    "Salmon",
    "Sand Lance",
    "Scad",
    "Scorpionfish",
    "Sea Bass",
    "Sea Bream",
    "Sea Horse",
    "Shad",
    "Shark",
    "Sheepshead",
    "Silverside",
    "Skate",
    "Smelt",
    "Snook",
    "Sockeye Salmon",
    "Spadefish",
    "Spotted Gar",
    "Spotfin Killifish",
    "Sturgeon",
    "Swordfish",
    "Tarpon",
    "Threadfin",
    "Tilapia",
    "Trout",
    "Triggerfish",
    "Tuna",
    "Walleye",
    "White Bass",
    "Whitefish",
    "Wolf Fish",
    "Wrasse",
    "Yellow Perch",
    "Zander",
    "Zebrafish",
    "Atlantic Cod",
    "Atlantic Salmon",
    "Black Sea Bass",
    "Blue Catfish",
    "Blue Marlin",
    "Brown Bullhead",
    "Carolina Madtom",
    "Channel Catfish",
    "Chinese Algae Eater",
    "Cobia",
    "Common Carp",
    "Crested Guppy",
    "Electric Catfish",
    "Emerald Green Rasbora",
    "Firefish",
    "Flying Fish",
    "Golden Dorado",
    "Golden Trout",
    "Giant Gourami",
    "Green Swordtail",
    "Greenling",
    "Guppy",
    "Hackleback",
    "Hardhead Catfish",
    "Huchen",
    "Indian Starfish",
    "Japanese Koi",
    "Japanese Pufferfish",
    "Kissing Gourami",
    "Lake Trout",
    "Largescale Madtom",
    "Largescale Stoneroller",
    "Longnose Gar",
    "Mahi-mahi",
    "Managuense",
    "Marmalade Rasbora",
    "Mekong Giant Catfish",
    "Minnow",
    "Mudskipper",
    "Neon Tetra",
    "Northern Pike",
    "Oscar",
    "Pacific Cod",
    "Paddlefish",
    "Piranha",
    "Rainbowfish",
    "Red Lionfish",
    "Redear Sunfish",
    "Redtail Catfish",
    "Rio Grande Cichlid",
    "Roosterfish",
    "Royal Gramma",
    "Sailfin Molly",
    "Sand Goby",
    "Sardine",
    "Sea Robin",
    "Shiner",
    "Shortnose Gar",
    "Silver Dollar",
    "Silver Perch",
    "Silver Salmon",
    "Skate",
    "Smallmouth Bass",
    "Smokerfish",
    "Snowflake Moray",
    "Speckled Trout",
    "Spotted Gar",
    "Spotted Knifejaw",
    "Spotted Ray",
    "Sucker",
    "Sunfish",
    "Swordfish",
    "Tench",
    "Threadfin",
    "Tilapia",
    "Tommyfish",
    "Torpedo Ray",
    "Triggerfish",
    "Tripletail",
    "Tuna",
    "Upside-down Catfish",
    "Vampire Fish",
    "Wahoo",
    "Warmouth",
    "Warty Sea Cucumber",
    "White Sturgeon",
    "White Bass",
    "White Crappie",
    "White Perch",
    "Whiting",
    "Wolf Herring",
    "Wrasse",
    "Yellowfin Tuna",
    "Yellowtail Amberjack",
    "Zebra Danio",
    "Zebra Pleco",
    "African Butterflyfish",
    "Amazon Swordfish",
    "Amur Catfish",
    "Anglerfish",
    "Atlantic Mackerel",
    "Atlantic Sturgeon",
    "Australian Lungfish",
    "Bala Shark",
    "Banded Killifish",
    "Barred Knifejaw",
    "Bigeye Tuna",
    "Black Bream",
    "Black Ghost Knifefish",
    "Blacktip Reef Shark",
    "Blue Gourami",
    "Blue Tang",
    "Bluefin Tuna",
    "Bristlenose Pleco",
    "Bronze Corydoras",
    "Brown Trout",
    "Bull Shark",
    "Butterfly Peacock Bass",
    "Carp",
    "Climbing Perch",
    "Cobalt Blue Zebra",
    "Common Pleco",
    "Convict Cichlid",
    "Ctenopharyngodon Idella",
    "Dace",
    "Daruma Loach",
    "Discus",
    "Electric Ray",
    "Electric Yellow Cichlid",
    "Emperor Angelfish",
    "Fangtooth",
    "Featherfin Squeaker",
    "Fire Eel",
    "Firemouth Cichlid",
    "Flowerhorn Cichlid",
    "Foureye Butterflyfish",
    "Freshwater Angelfish",
    "Giant Gourami",
    "Giant Snakehead",
    "Goldfish",
    "Green Terror",
    "Green Chromide",
    "Green Spotted Puffer",
    "Guppy",
    "Hatchetfish",
    "Indian Glassy Fish",
    "Indian Mackerel",
    "Jack Dempsey",
    "Jellyfish",
    "Kissing Gourami",
    "Koi",
    "Kuhli Loach",
    "Lake Sturgeon",
    "Largemouth Bass",
    "Lionfish",
    "Longnose Gar",
    "Mayan Cichlid",
    "Molly",
    "Monkfish",
    "Moonfish",
    "Murray Cod",
    "Neon Tetra",
    "Oscar",
    "Oscar Cichlid",
    "Pacific Halibut",
    "Parrot Cichlid",
    "Pearl Danio",
    "Peacock Bass",
    "Piranha",
    "Popeye Fish",
    "Rainbow Trout",
    "Redtail Catfish",
    "Riffle Minnow",
    "River Carp",
    "Roach",
    "Rosy Barb",
    "Sailfin Molly",
    "Sand Goby",
    "Siamese Fighting Fish",
    "Silver Dollar",
    "Silver Arowana",
    "Silver Perch",
    "Skate",
    "Snakehead",
    "Snook",
    "Southern Pike",
    "Spotted Gar",
    "Spotted Knifejaw",
    "Spotfin Butterflyfish",
    "Swordfish",
    "Tinfoil Barb",
    "Torpedo Ray",
    "Triggerfish",
    "Trumpetfish",
    "Tuna",
    "Upside-down Catfish",
    "Vampire Fish",
    "Wels Catfish",
    "Whale Shark",
    "White Bass",
    "White Crappie",
    "White Sturgeon",
    "White Perch",
    "Wolf Herring",
    "Wrasse",
    "Yellow Tang",
    "Yellowfin Tuna",
    "Zebra Danio",
    "Zebra Pleco",
];

pub const AMPHIBIANS: [&str; 102] = [
    "Frog",
    "Toad",
    "Salamander",
    "Newt",
    "Caecilian",
    "Axolotl",
    "Tree Frog",
    "Bullfrog",
    "Glass Frog",
    "Fire Salamander",
    "Tiger Salamander",
    "Mudpuppy",
    "Hellbender",
    "Spadefoot Toad",
    "Poison Dart Frog",
    "Clawed Frog",
    "African Bullfrog",
    "Green Tree Frog",
    "Japanese Giant Salamander",
    "Marbled Salamander",
    "Mountain Yellow-legged Frog",
    "Eastern Newt",
    "Pacific Tree Frog",
    "European Fire-bellied Toad",
    "American Toad",
    "Common Frog",
    "Green Frog",
    "Pickerel Frog",
    "Wood Frog",
    "Cane Toad",
    "Mexican Burrowing Toad",
    "Northern Leopard Frog",
    "Southern Leopard Frog",
    "African Clawed Frog",
    "Tiger Frog",
    "Golden Toad",
    "Giant Tree Frog",
    "Oriental Fire-bellied Toad",
    "Striped Rocket Frog",
    "Yellow-bellied Toad",
    "Midwife Toad",
    "Goliath Frog",
    "Tomato Frog",
    "Mantella Frog",
    "Asian Painted Frog",
    "European Green Toad",
    "Oriental Fire-bellied Newt",
    "Western Toad",
    "Italian Crested Newt",
    "California Newt",
    "Spotted Salamander",
    "Alpine Newt",
    "Black-spotted Newt",
    "Four-toed Salamander",
    "Eastern Spadefoot",
    "Rough-skinned Newt",
    "Mexican Tree Frog",
    "Dusky Salamander",
    "Barking Tree Frog",
    "Cope's Gray Tree Frog",
    "Cuban Tree Frog",
    "Dart Frog",
    "European Tree Frog",
    "Fire-bellied Toad",
    "Green and Black Poison Dart Frog",
    "Harlequin Poison Frog",
    "Indian Bullfrog",
    "Japanese Tree Frog",
    "Mossy Frog",
    "Northern Spring Salamander",
    "Orange-bellied Frog",
    "Pacific Giant Salamander",
    "Panamanian Golden Frog",
    "Pine Barrens Treefrog",
    "Purple Frog",
    "Rana Pipiens",
    "Red-eyed Tree Frog",
    "Southern Chorus Frog",
    "Spring Peeper",
    "Steelhead Newt",
    "Strawberry Poison-dart Frog",
    "Sumatran Horned Frog",
    "Western Chorus Frog",
    "Western Narrow-mouthed Toad",
    "Western Toad",
    "White-lipped Tree Frog",
    "Yellow-eyed Tree Frog",
    "Yellow-spotted Tree Frog",
    "Zebra Dart Frog",
    "Zigzag Salamander",
    "Mountain Chorus Frog",
    "Giant Salamander",
    "Chinese Giant Salamander",
    "Hellbender Salamander",
    "Marbled Newt",
    "European Fire Salamander",
    "Asian Giant Salamander",
    "Black Salamander",
    "Northern Dusky Salamander",
    "Eastern Newt Larva",
    "Greater Siren",
    "Lungless Salamander",
];

pub const REPTILES: [&str; 97] = [
    "Alligator",
    "Anole",
    "Bearded Dragon",
    "Boa Constrictor",
    "Box Turtle",
    "Carolina Anole",
    "Chameleon",
    "Corn Snake",
    "Crocodile",
    "Desert Tortoise",
    "Diamondback Rattlesnake",
    "Eastern Box Turtle",
    "Eastern Diamondback",
    "Gecko",
    "Gila Monster",
    "Green Iguana",
    "Horned Lizard",
    "King Cobra",
    "Komodo Dragon",
    "Leatherback Turtle",
    "Loggerhead Turtle",
    "Mamba",
    "Moccasin",
    "Monitor Lizard",
    "Musk Turtle",
    "Nile Crocodile",
    "Painted Turtle",
    "Peregrine Turtle",
    "Pogona",
    "Python",
    "Rattlesnake",
    "Red-eared Slider",
    "Ringneck Snake",
    "Rosy Boa",
    "Sea Turtle",
    "Skink",
    "Slow Worm",
    "Snapping Turtle",
    "Spiny-tailed Lizard",
    "Spectacled Caiman",
    "Spiny Softshell Turtle",
    "Texas Horned Lizard",
    "Timber Rattlesnake",
    "Tortoise",
    "Water Dragon",
    "Western Diamondback",
    "Western Painted Turtle",
    "Yellow Anole",
    "Yellow-bellied Sea Snake",
    "African Rock Python",
    "Aldabra Giant Tortoise",
    "American Alligator",
    "Ball Python",
    "Banded Rock Rattlesnake",
    "Black Rat Snake",
    "Blue-tongued Skink",
    "Common Garter Snake",
    "Common Snapping Turtle",
    "Eastern Coral Snake",
    "Eastern Indigo Snake",
    "Eastern Mud Turtle",
    "Florida Box Turtle",
    "Four-lined Snake",
    "Garter Snake",
    "Green Sea Turtle",
    "Hognose Snake",
    "Indian Star Tortoise",
    "King Snake",
    "Mata Mata Turtle",
    "Milk Snake",
    "Moorish Gecko",
    "Mud Turtle",
    "Northern Copperhead",
    "Olive Ridley Turtle",
    "Puff Adder",
    "Rainbow Boa",
    "Red-footed Tortoise",
    "Reticulated Python",
    "Rio Grande Leopard Frog",
    "Ringed Turtle",
    "Rubber Boa",
    "Saltwater Crocodile",
    "Screech Owl",
    "Short-tailed Shrew",
    "Sidewinder Rattlesnake",
    "Smooth Green Snake",
    "Softshell Turtle",
    "Spiny-tailed Iguana",
    "Timber Rattlesnake",
    "Tusksnake",
    "Venomous Snake",
    "Western Fence Lizard",
    "Western Rattlesnake",
    "Western Tiger Snake",
    "Yellow-bellied Racer",
    "Zebra-tailed Lizard",
    "Zebra Tortoise",
];

pub const ARACHNIDS: [&str; 114] = [
    "Black Widow",
    "Brown Recluse",
    "Wolf Spider",
    "Tarantula",
    "Jumping Spider",
    "Daddy Longlegs",
    "Orb Weaver",
    "Huntsman Spider",
    "Trapdoor Spider",
    "Camel Spider",
    "Harvestman",
    "Brown Widow",
    "Brazilian Wandering Spider",
    "Green Lynx Spider",
    "Garden Spider",
    "Golden Silk Orb-weaver",
    "Fishing Spider",
    "Crab Spider",
    "Yellow Sac Spider",
    "Six-eyed Sand Spider",
    "Australian Funnel-web Spider",
    "Sydney Funnel-web Spider",
    "Redback Spider",
    "Scorpion",
    "Pseudoscorpion",
    "Tick",
    "Mite",
    "Cave Spider",
    "Cave Orb Weaver",
    "Cellar Spider",
    "European Garden Spider",
    "European Tarantula",
    "Green Huntsman Spider",
    "Hobo Spider",
    "House Spider",
    "Jumping Spider",
    "Long-jawed Orb Weaver",
    "Marbled Orb Weaver",
    "Mouse Spider",
    "Nursery Web Spider",
    "Pholcus",
    "Pinktoe Tarantula",
    "Purseweb Spider",
    "Red Ghost Spider",
    "Recluse Spider",
    "Rice Paddy Spider",
    "Sac Spider",
    "Scorpionfly",
    "Sheetweb Spider",
    "Six-spotted Fishing Spider",
    "Social Spider",
    "Spiny Orb-weaver",
    "Steatoda",
    "Stone Spider",
    "Striped Lynx Spider",
    "Sun Spider",
    "Tarantula Hawk",
    "Trapdoor Spider",
    "Tree Spider",
    "Two-tailed Spider",
    "Velvet Spider",
    "Water Spider",
    "Wolf Spider",
    "Woodlouse Spider",
    "Yellow Garden Spider",
    "Zebra Jumping Spider",
    "Zebra Tarantula",
    "Zigzag Spider",
    "Brazilian Black Tarantula",
    "Baldlegged Orb Weaver",
    "Barn Funnel Weaver",
    "Black House Spider",
    "Bluefanged Cleaner Wrasse",
    "Blue-legged Tarantula",
    "Brazilian Brown Tarantula",
    "Cave Orb Weaver",
    "Caribbean Spider",
    "Central American Wandering Spider",
    "Chinese Bird Spider",
    "Colombian Lesserblack Tarantula",
    "Common House Spider",
    "Costa Rican Tiger Rump Tarantula",
    "Dark Fishing Spider",
    "Desert Recluse",
    "European Garden Spider",
    "False Widow",
    "Feather-legged Spider",
    "Florida Bark Spider",
    "Funnel-web Spider",
    "Giant Crab Spider",
    "Giant House Spider",
    "Golden Huntsman Spider",
    "Gooty Sapphire Tarantula",
    "Green Lynx Spider",
    "Green Recluse",
    "Huntsman Spider",
    "Indian Ornamental Tarantula",
    "Joro Spider",
    "Long-bodied Cellar Spider",
    "Long-jawed Orb Weaver",
    "Malaysian Earth Tiger Tarantula",
    "Mexican Red-knee Tarantula",
    "Orange Baboon Tarantula",
    "Orb Weaver",
    "Pine Bark Spider",
    "Pinktoe Tarantula",
    "Redback Spider",
    "Redfem Tarantula",
    "Selenocosmia",
    "Shamrock Spider",
    "Spitting Spider",
    "Sydney Funnel-web Spider",
    "Tarantula",
    "Tarantula Hawk",
];

pub const MOLLUSKS: [&str; 93] = [
    "Octopus",
    "Squid",
    "Cuttlefish",
    "Nautilus",
    "Snail",
    "Slug",
    "Clam",
    "Oyster",
    "Mussel",
    "Scallop",
    "Chiton",
    "Abalone",
    "Conch",
    "Whelk",
    "Nerite",
    "Periwinkle",
    "Cockle",
    "Limpet",
    "Sea Hare",
    "Dog Whelk",
    "Giant Clam",
    "Freshwater Mussel",
    "Garden Snail",
    "Sea Slug",
    "Moon Snail",
    "Turban Snail",
    "Olive Shell",
    "Tulip Shell",
    "Wentletrap",
    "Bubble Shell",
    "Apple Snail",
    "Mangrove Snail",
    "Horned Nerite",
    "Chocolate Clam",
    "Geoduck",
    "Pearl Oyster",
    "Pismo Clam",
    "Atlantic Surf Clam",
    "Bay Scallop",
    "Sea Butterfly",
    "Sea Lemon",
    "Amber Snail",
    "Blue Mussel",
    "Brown Mussel",
    "California Sea Hare",
    "Dog Conch",
    "Dove Snail",
    "Eastern Oyster",
    "Flat Tree Oyster",
    "Fluted Giant Clam",
    "Giant African Land Snail",
    "Giant Pacific Octopus",
    "Green Turbo",
    "Horse Conch",
    "Japanese Turban",
    "King Scallop",
    "Lace Snail",
    "Limpet",
    "Little Neck Clam",
    "Long-spined Sea Urchin",
    "Margaritifera",
    "Marbled Cone Snail",
    "Mediterranean Mussel",
    "Moon Snail",
    "Mud Snail",
    "Nassarius",
    "Northern Abalone",
    "Olive Snail",
    "Pacific Razor Clam",
    "Pearl Oyster",
    "Periwinkle",
    "Queen Conch",
    "Razor Clam",
    "Red Abalone",
    "Rough Limpet",
    "Sailor’s Hornpipe",
    "Scallop",
    "Sea Biscuit",
    "Sea Snail",
    "Slipper Limpet",
    "Smooth Periwinkle",
    "Spiny Oyster",
    "Spotted Dog Whelk",
    "Striped Nerite",
    "Surf Clam",
    "Tusk Shell",
    "Venus Clam",
    "Wavy Turban",
    "White Abalone",
    "Winkles",
    "Wooden Whelk",
    "Yellow Periwinkle",
    "Zebra Nerite",
];

pub const CRUSTACEANS: [&str; 98] = [
    "Crab",
    "Lobster",
    "Shrimp",
    "Prawn",
    "Krill",
    "Barnacle",
    "Crawfish",
    "Crayfish",
    "Hermit Crab",
    "Isopod",
    "Amphipod",
    "Copepod",
    "Ghost Shrimp",
    "Mantis Shrimp",
    "Water Flea",
    "Fairy Shrimp",
    "Seed Shrimp",
    "Tanner Crab",
    "Blue Crab",
    "Dungeness Crab",
    "King Crab",
    "Snow Crab",
    "Stone Crab",
    "Fiddler Crab",
    "Spider Crab",
    "Hairy Crab",
    "Mud Crab",
    "Velvet Crab",
    "Porcelain Crab",
    "Red Rock Crab",
    "Sand Crab",
    "Shore Crab",
    "Swimmer Crab",
    "Tasmanian Giant Crab",
    "Tiger Shrimp",
    "Northern Shrimp",
    "Pink Shrimp",
    "White Shrimp",
    "Brown Shrimp",
    "Spot Shrimp",
    "Northern Lobster",
    "Spiny Lobster",
    "Slipper Lobster",
    "Rock Lobster",
    "Electric Lobster",
    "Squat Lobster",
    "Norway Lobster",
    "Stone Lobster",
    "Blue Lobster",
    "Alaskan King Crab",
    "Chocolate Clam",
    "Eastern Oyster",
    "Giant Clam",
    "Green Crab",
    "Japanese Spider Crab",
    "Mangrove Crab",
    "Mole Crab",
    "Mud Lobster",
    "Pacific Rock Crab",
    "Pea Crab",
    "Porcelain Crab",
    "Red Claw Crab",
    "Red King Crab",
    "Red Swamp Crayfish",
    "Sally Lightfoot Crab",
    "Spiny King Crab",
    "Tropical Rock Lobster",
    "Velvet Shrimp",
    "Warty Crab",
    "White-clawed Crayfish",
    "Yeti Crab",
    "Zebra Crab",
    "Coral Crab",
    "Dwarf Crab",
    "Finger Crab",
    "Giant Clam",
    "Horseshoe Crab",
    "Japanese Spider Crab",
    "Lobster Moth",
    "Megalopa",
    "Mud Crab",
    "Narrow-clawed Lobster",
    "Pacific White Shrimp",
    "Pea Crab",
    "Peacock Mantis Shrimp",
    "Porcelain Crab",
    "Red King Crab",
    "Rock Crab",
    "Sea Slater",
    "Swimmer Crab",
    "Tasmanian Giant Crab",
    "Tiger Prawn",
    "Tropical Rock Lobster",
    "Velvet Crab",
    "White Shrimp",
    "Xanthid Crab",
    "Yellow Crab",
    "Zombie Crab",
];

pub const ANIMAL_TYPES: [&str; 10] = [
    "Mammal",
    "Bird",
    "Fish",
    "Reptile",
    "Amphibian",
    "Insect",
    "Arachnid",
    "Crustacean",
    "Mollusk",
    "Echinoderm",
];
