pub const LITERARY_GENRES: &[&str] = &[
    "Adventure",
    "Autobiography",
    "Bildungsroman",
    "Biography",
    "Campus Fiction",
    "Campus Novel",
    "Chick Lit",
    "Children's",
    "Classic",
    "Classic Literature",
    "Comedy",
    "Coming-of-Age",
    "Courtroom Drama",
    "Crime",
    "Crime Fiction",
    "Cyberpunk",
    "Dark Fantasy",
    "Dark Humor",
    "Detective",
    "Doomsday",
    "Drama",
    "Drama Fiction",
    "Dystopian",
    "Epic",
    "Epic Fantasy",
    "Epic Poetry",
    "Erotica",
    "Existentialism",
    "Fable",
    "Fairy Tale",
    "Fairy Tale Fiction",
    "Fan Fiction",
    "Fantasy",
    "Fantasy Fiction",
    "Feminist Fiction",
    "Fiction",
    "Fictional Biography",
    "Flash Fiction",
    "Folklore",
    "Ghost Story",
    "Gothic",
    "Gothic Fiction",
    "Graphic Novel",
    "Hard Science Fiction",
    "Hardboiled",
    "Heroic Fantasy",
    "High Fantasy",
    "Historical",
    "Historical Fiction",
    "Historical Romance",
    "Historical Thriller",
    "Holiday Romance",
    "Horror",
    "Horror Fiction",
    "Humorous Fiction",
    "Humour",
    "Humour Fiction",
    "Inspirational",
    "Legal Thriller",
    "Legend",
    "Literary Fiction",
    "Magic Realism",
    "Magical Realism",
    "Magical Realism Fiction",
    "Martial Arts",
    "Medical Fiction",
    "Medical Thriller",
    "Memoir",
    "Military Fiction",
    "Military Thriller",
    "Moral Tale",
    "Mystery",
    "Mythological Fiction",
    "Mythology",
    "Mythopoeia",
    "Nonfiction",
    "Nonlinear Narrative",
    "Occult",
    "Parable",
    "Paranormal",
    "Paranormal Romance",
    "Philosophical",
    "Philosophical Fiction",
    "Philosophical Novel",
    "Poetry",
    "Political",
    "Political Fiction",
    "Political Thriller",
    "Post-Apocalyptic",
    "Psychological",
    "Psychological Fiction",
    "Psychological Thriller",
    "Realism",
    "Regional Fiction",
    "Religious",
    "Romance",
    "Romantic Comedy",
    "Romantic Fantasy",
    "Romantic Suspense",
    "Romantic Thriller",
    "Saga",
    "Satire",
    "Satire Fiction",
    "Satirical Fiction",
    "Science Fantasy",
    "Science Fiction",
    "Science Fiction Fantasy",
    "Short Story",
    "Slipstream",
    "Space Opera",
    "Space Western",
    "Speculative",
    "Spy Fiction",
    "Spy Thriller",
    "Steampunk",
    "Superhero",
    "Supernatural",
    "Supernatural Thriller",
    "Surrealism",
    "Suspense",
    "Techno Thriller",
    "Techno-Thriller",
    "Thriller",
    "Thriller Fiction",
    "Tragedy",
    "Tragicomedy",
    "Urban Fantasy",
    "Urban Fiction",
    "Utopian",
    "Victorian Fiction",
    "War",
    "Western",
    "Western Fiction",
    "Western Romance",
    "Women's Fiction",
    "Women's Literature",
];

pub const ARCHITECTURAL_STYLES: &[&str] = &[
    "Art Brut",
    "Art Deco",
    "Art Nouveau",
    "Barbizon",
    "Baroque",
    "Bauhaus",
    "Beaux-Arts",
    "Biedermeier",
    "Blobitecture",
    "Brutalism",
    "Bungalow",
    "Byzantine",
    "Cape Cod",
    "Chalet Style",
    "Chateauesque",
    "Churrigueresque",
    "Colonial",
    "Colonial Revival",
    "Constructivism",
    "Craftsman",
    "Critical Regionalism",
    "De Stijl",
    "Deconstructivism",
    "Digital Architecture",
    "Dutch Colonial",
    "Edwardian",
    "Egyptian Revival",
    "Expressionism",
    "Expressionist Architecture",
    "Fantastical",
    "Federal",
    "Federal Style",
    "Federalist",
    "French Colonial",
    "Futurism",
    "Garden Style",
    "Georgian",
    "Googie",
    "Googie Architecture",
    "Gothic",
    "Gothic Revival",
    "Grecian",
    "Greek Revival",
    "Green Architecture",
    "High-Tech",
    "Islamic",
    "Islamic Revival",
    "Italian Renaissance",
    "Italianate",
    "Jacobean",
    "Jacobethan",
    "Japonism",
    "Mediterranean",
    "Mediterranean Revival",
    "Metabolism",
    "Mid-Century Modern",
    "Minimalism",
    "Moderne",
    "Modernism",
    "Moorish",
    "Mughal",
    "Neo-Baroque",
    "Neo-Classicism",
    "Neo-Expressionism",
    "Neo-Futurism",
    "Neo-Minimalism",
    "Neo-Renaissance",
    "Neo-Romanesque",
    "Neo-Victorian",
    "Neoclassical",
    "Neoclassicism",
    "Neogothic",
    "New Urbanism",
    "Nordic Classicism",
    "Néo-gothique",
    "Organic",
    "Organic Architecture",
    "Palladian",
    "Palladianism",
    "Parametricism",
    "Post-War Modernism",
    "Postmodern Architecture",
    "Postmodernism",
    "Prairie",
    "Pueblo Revival",
    "Queen Anne",
    "Regionalism",
    "Renaissance",
    "Richardsonian Romanesque",
    "Rococo",
    "Roman",
    "Roman Revival",
    "Romanesque",
    "Romanesque Revival",
    "Romanian Revival",
    "Rustic",
    "Saltbox",
    "Santa Fe",
    "Scandinavian",
    "Second Empire",
    "Second Renaissance Revival",
    "Shingle",
    "Shingle Style",
    "Socialist Classicism",
    "Soviet",
    "Spanish Colonial",
    "Stick Style",
    "Streamline",
    "Streamline Moderne",
    "Structuralism",
    "Sullivan Style",
    "Sustainable Architecture",
    "Swiss Chalet",
    "Tadao Ando Style",
    "Transitional",
    "Tropical Modernism",
    "Tudor",
    "Tudor Revival",
    "Tudorbethan",
    "Tulip Style",
    "Tuscan",
    "Usonian",
    "Venetian Gothic",
    "Vernacular",
    "Vernacular Architecture",
    "Vernacular Modernism",
    "Victorian",
    "Victorian Gothic",
    "Victorian Italianate",
    "Viennese Secession",
    "Wright Style",
    "Wrightian",
    "Yugoslav Modernism",
    "Zaha Hadid Style",
    "Zenith",
    "Zeppelin",
    "Zigzag Art Deco",
    "Zigzag Moderne",
];

pub const MUSICAL_GENRES: &[&str] = &[
    "Afrobeat",
    "Alternative",
    "Ambient",
    "Big Band",
    "Black Metal",
    "Bluegrass",
    "Blues",
    "Bossa Nova",
    "Cajun",
    "Calypso",
    "Celtic",
    "Chillout",
    "Chiptune",
    "Choral",
    "Classical",
    "Country",
    "Cumbia",
    "Dance Pop",
    "Dancehall",
    "Darkwave",
    "Death Metal",
    "Disco",
    "Drill",
    "Drum and Bass",
    "Dubstep",
    "Electro",
    "Electro Swing",
    "Electronic",
    "Electropop",
    "Emo",
    "Eurodance",
    "Fado",
    "Folk",
    "Folk Rock",
    "Freakbeat",
    "Funk",
    "Garage",
    "Garage House",
    "Garage Punk",
    "Garage Rock",
    "Glam Metal",
    "Glam Rock",
    "Glitch",
    "Gospel",
    "Gothic Rock",
    "Grime",
    "Grindcore",
    "Grunge",
    "Hard Bop",
    "Hard Rock",
    "Hardcore",
    "Hardstyle",
    "Hi-NRG",
    "Hip Hop",
    "House",
    "House Music",
    "Indie",
    "Industrial",
    "J-Pop",
    "Jazz",
    "Jazz Blues",
    "Jazz Funk",
    "Jazz Fusion",
    "K-Pop",
    "Krautrock",
    "Latin",
    "Latin Jazz",
    "Latin Pop",
    "Lo-fi",
    "Lo-fi Hip Hop",
    "Mariachi",
    "Merengue",
    "Metal",
    "Metalcore",
    "Microhouse",
    "Modern Classical",
    "Motown",
    "Neo Folk",
    "Neo Soul",
    "Neue Deutsche Welle",
    "New Age",
    "New Wave",
    "Noise",
    "Noise Rock",
    "Nu Metal",
    "Oldies",
    "Opera",
    "Polka",
    "Pop",
    "Pop Punk",
    "Post Disco",
    "Post Hardcore",
    "Post Punk",
    "Post Punk Revival",
    "Post Rock",
    "Power Electronics",
    "Power Metal",
    "Power Pop",
    "Progressive Metal",
    "Progressive Rock",
    "Psychedelic Rock",
    "Psytrance",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Salsa",
    "Samba",
    "Screamo",
    "Shoegaze",
    "Singer-Songwriter",
    "Ska",
    "Ska Punk",
    "Soft Rock",
    "Soul",
    "Southern Rock",
    "Space Rock",
    "Speed Metal",
    "Surf Rock",
    "Swing",
    "Swing Jazz",
    "Swing Revival",
    "Synthpop",
    "Synthpunk",
    "Synthwave",
    "Tech House",
    "Techno",
    "Techno Hardcore",
    "Tejano",
    "Thrash",
    "Thrash Metal",
    "Trance",
    "Trap",
    "Trip Hop",
    "Vaporwave",
    "Western Swing",
    "World Music",
    "Zouk",
    "Zydeco",
];

pub const MUSICAL_INSTRUMENTS: &[&str] = &[
    "Accordion",
    "Agogo Bells",
    "Alphorn",
    "Anklung",
    "Bagpipes",
    "Balalaika",
    "Bandoneon",
    "Banjo",
    "Baritone Horn",
    "Baritone Saxophone",
    "Bass Clarinet",
    "Bass Drum",
    "Bass Guitar",
    "Bass Recorder",
    "Bassoon",
    "Bawu",
    "Bendir",
    "Bodhrán",
    "Bombard",
    "Bouzouki",
    "Cajón",
    "Calimba",
    "Castanets",
    "Celesta",
    "Cello",
    "Chapman Stick",
    "Cimbalom",
    "Clarinet",
    "Claves",
    "Clavichord",
    "Conga Drums",
    "Congas",
    "Contrabass Clarinet",
    "Contrabassoon",
    "Crwth",
    "Cuíca",
    "Damaru",
    "Dhol",
    "Didgeridoo",
    "Dizi",
    "Djembe",
    "Double Bass",
    "Drums",
    "Duduk",
    "Electric Bass",
    "Electric Guitar",
    "Erhu",
    "Euphonium",
    "Fife",
    "Flugelhorn",
    "Flute",
    "French Horn",
    "Gaita",
    "Gamelan",
    "Glass Harmonica",
    "Glockenspiel",
    "Gong",
    "Guiro",
    "Guitar",
    "Hang Drum",
    "Hardanger Fiddle",
    "Harmonica",
    "Harp",
    "Hurdy-Gurdy",
    "Jaw Harp",
    "Kalimba",
    "Kamancheh",
    "Kaval",
    "Khomus",
    "Kora",
    "Koto",
    "Lazavox",
    "Laúd",
    "Lur",
    "Lute",
    "Lyre",
    "Lá Làn",
    "Mandolin",
    "Maracas",
    "Marimba",
    "Mbira",
    "Melodica",
    "Morin Khuur",
    "Musical Saw",
    "Nagoya Harp",
    "Nai",
    "Ngoni",
    "Nyckelharpa",
    "Oboe",
    "Ocarina",
    "Octobass",
    "Ondes Martenot",
    "Pan Flute",
    "Pandeiro",
    "Panpipes",
    "Pennywhistle",
    "Piano",
    "Piccolo",
    "Piccolo Trumpet",
    "Psaltery",
    "Pungi",
    "Quena",
    "Rabab",
    "Rebab",
    "Recorder",
    "Santoor",
    "Sanza",
    "Sarangi",
    "Sarrusophone",
    "Saxophone",
    "Serpent",
    "Shakuhachi",
    "Shamisen",
    "Shehnai",
    "Shekere",
    "Sheng",
    "Shofar",
    "Sitar",
    "Sousaphone",
    "Steel Drum",
    "Suling",
    "Surdu",
    "Synthesizer",
    "Tabla",
    "Tambourine",
    "Tambura",
    "Theremin",
    "Timpani",
    "Tiple",
    "Tongue Drum",
    "Triangle",
    "Trombone",
    "Trumpet",
    "Trống",
    "Tuba",
    "Tubular Bells",
    "Udu",
    "Uilleann Pipes",
    "Ukulele",
    "Veena",
    "Vibraphone",
    "Violin",
    "Vuvuzela",
    "Wagakki",
    "Washboard",
    "Water Drum",
    "Waterphone",
    "Whistle",
    "Woodblock",
    "Xylophone",
    "Yangqin",
    "Zabumba",
    "Zheng",
    "Zills",
    "Zither",
    "Zithers",
    "Zurna",
];
