pub const LITERARY_GENRES: [&str; 138] = [
    "Adventure",
    "Biography",
    "Children's",
    "Classic",
    "Comedy",
    "Crime",
    "Drama",
    "Dystopian",
    "Epic",
    "Fantasy",
    "Fiction",
    "Gothic",
    "Historical",
    "Horror",
    "Humour",
    "Legend",
    "Magic Realism",
    "Memoir",
    "Mystery",
    "Mythology",
    "Nonfiction",
    "Parable",
    "Philosophical",
    "Poetry",
    "Political",
    "Psychological",
    "Realism",
    "Romance",
    "Satire",
    "Science Fiction",
    "Short Story",
    "Speculative",
    "Suspense",
    "Thriller",
    "Tragedy",
    "Western",
    "Autobiography",
    "Chick Lit",
    "Cyberpunk",
    "Detective",
    "Epic Poetry",
    "Fable",
    "Fairy Tale",
    "Fan Fiction",
    "Gothic Fiction",
    "Hard Science Fiction",
    "Historical Fiction",
    "Heroic Fantasy",
    "High Fantasy",
    "Humour Fiction",
    "Inspirational",
    "Magical Realism",
    "Martial Arts",
    "Medical Fiction",
    "Military Fiction",
    "Mythopoeia",
    "Noir",
    "Occult",
    "Paranormal",
    "Philosophical Fiction",
    "Political Fiction",
    "Post-Apocalyptic",
    "Psychological Thriller",
    "Religious",
    "Romantic Comedy",
    "Romantic Suspense",
    "Satirical Fiction",
    "Science Fantasy",
    "Slipstream",
    "Space Opera",
    "Spy Fiction",
    "Steampunk",
    "Superhero",
    "Supernatural",
    "Surrealism",
    "Techno-Thriller",
    "Tragicomedy",
    "Urban Fantasy",
    "Utopian",
    "War",
    "Western Fiction",
    "Women's Fiction",
    "Bildungsroman",
    "Campus Novel",
    "Campus Fiction",
    "Classic Literature",
    "Coming-of-Age",
    "Courtroom Drama",
    "Crime Fiction",
    "Dark Fantasy",
    "Dark Humor",
    "Doomsday",
    "Drama Fiction",
    "Epic Fantasy",
    "Erotica",
    "Existentialism",
    "Fairy Tale Fiction",
    "Fantasy Fiction",
    "Feminist Fiction",
    "Fictional Biography",
    "Flash Fiction",
    "Folklore",
    "Ghost Story",
    "Graphic Novel",
    "Hardboiled",
    "Historical Romance",
    "Historical Thriller",
    "Holiday Romance",
    "Horror Fiction",
    "Humorous Fiction",
    "Legal Thriller",
    "Literary Fiction",
    "Magical Realism Fiction",
    "Medical Thriller",
    "Military Thriller",
    "Moral Tale",
    "Mythological Fiction",
    "Neo-Noir",
    "Nonlinear Narrative",
    "Paranormal Romance",
    "Philosophical Novel",
    "Political Thriller",
    "Psychological Fiction",
    "Regional Fiction",
    "Romantic Fantasy",
    "Romantic Thriller",
    "Saga",
    "Satire Fiction",
    "Science Fiction Fantasy",
    "Space Western",
    "Spy Thriller",
    "Supernatural Thriller",
    "Techno Thriller",
    "Thriller Fiction",
    "Urban Fiction",
    "Victorian Fiction",
    "Western Romance",
    "Women's Literature",
];

pub const ARCHITECTURAL_STYLES: [&str; 142] = [
    "Gothic",
    "Baroque",
    "Romanesque",
    "Renaissance",
    "Neoclassical",
    "Art Deco",
    "Art Nouveau",
    "Modernism",
    "Brutalism",
    "Postmodernism",
    "Minimalism",
    "Bauhaus",
    "Victorian",
    "Georgian",
    "Edwardian",
    "Colonial",
    "Federal",
    "Tudor",
    "Greek Revival",
    "Islamic",
    "Byzantine",
    "Moorish",
    "Mughal",
    "Roman",
    "Palladian",
    "Beaux-Arts",
    "Deconstructivism",
    "Expressionism",
    "Constructivism",
    "International",
    "Futurism",
    "Grecian",
    "Neogothic",
    "Neo-Baroque",
    "Neo-Renaissance",
    "Prairie",
    "Craftsman",
    "Shingle",
    "Cape Cod",
    "Mid-Century Modern",
    "Organic",
    "High-Tech",
    "Swiss Chalet",
    "Dutch Colonial",
    "French Colonial",
    "Chateauesque",
    "Second Empire",
    "Queen Anne",
    "Saltbox",
    "Mediterranean Revival",
    "Spanish Colonial",
    "Tuscan",
    "Italianate",
    "Streamline Moderne",
    "Richardsonian Romanesque",
    "Soviet",
    "Bungalow",
    "Barbizon",
    "Churrigueresque",
    "Colonial Revival",
    "Roman Revival",
    "Gothic Revival",
    "Jacobethan",
    "Jacobean",
    "International Style",
    "Vernacular",
    "Scandinavian",
    "Shingle Style",
    "Stick Style",
    "Tudorbethan",
    "Federal Style",
    "Federalist",
    "Metabolism",
    "Neo-Futurism",
    "Neo-Classicism",
    "Neo-Expressionism",
    "Neo-Minimalism",
    "Neo-Victorian",
    "Organic Architecture",
    "Pueblo Revival",
    "Rococo",
    "Romanian Revival",
    "Rustic",
    "Santa Fe",
    "Second Renaissance Revival",
    "Socialist Classicism",
    "Sullivan Style",
    "Tropical Modernism",
    "Usonian",
    "Vernacular Modernism",
    "Victorian Gothic",
    "Wrightian",
    "Zeppelin",
    "Zigzag Moderne",
    "Art Brut",
    "Biedermeier",
    "Chalet Style",
    "Expressionist Architecture",
    "Fantastical",
    "Garden Style",
    "Googie",
    "Italian Renaissance",
    "International Style",
    "Japonism",
    "Mediterranean",
    "Neoclassicism",
    "Neo-Romanesque",
    "Postmodern Architecture",
    "Romanesque Revival",
    "Streamline",
    "Transitional",
    "Tudor Revival",
    "Venetian Gothic",
    "Viennese Secession",
    "Yugoslav Modernism",
    "Zaha Hadid Style",
    "Zenith",
    "Zigzag Art Deco",
    "New Urbanism",
    "Blobitecture",
    "Digital Architecture",
    "De Stijl",
    "Parametricism",
    "Critical Regionalism",
    "Sustainable Architecture",
    "Green Architecture",
    "Vernacular Architecture",
    "Islamic Revival",
    "Egyptian Revival",
    "Googie Architecture",
    "Moderne",
    "Néo-gothique",
    "Nordic Classicism",
    "Palladianism",
    "Post-War Modernism",
    "Regionalism",
    "Structuralism",
    "Tadao Ando Style",
    "Tulip Style",
    "Victorian Italianate",
    "Wright Style",
    "Zigzag Moderne",
];

pub const MUSICAL_GENRES: [&str; 144] = [
    "Rock",
    "Pop",
    "Jazz",
    "Classical",
    "Blues",
    "Country",
    "Hip Hop",
    "R&B",
    "Electronic",
    "Reggae",
    "Funk",
    "Soul",
    "Metal",
    "Punk",
    "Disco",
    "Folk",
    "Gospel",
    "Ska",
    "Techno",
    "House",
    "Trance",
    "Ambient",
    "Dubstep",
    "Grunge",
    "Indie",
    "K-Pop",
    "Latin",
    "Opera",
    "Bluegrass",
    "Choral",
    "Swing",
    "Big Band",
    "Synthpop",
    "Garage",
    "Emo",
    "Industrial",
    "Alternative",
    "New Wave",
    "Post Punk",
    "Progressive Rock",
    "Hard Rock",
    "Thrash Metal",
    "Death Metal",
    "Black Metal",
    "Dancehall",
    "Drum and Bass",
    "Electro",
    "Garage Rock",
    "Glitch",
    "Grime",
    "Hardcore",
    "Jazz Fusion",
    "Lo-fi",
    "Motown",
    "Noise",
    "Post Rock",
    "Power Metal",
    "Rap",
    "Reggaeton",
    "Shoegaze",
    "Singer-Songwriter",
    "Surf Rock",
    "Swing Revival",
    "Synthwave",
    "Trip Hop",
    "World Music",
    "Zydeco",
    "Afrobeat",
    "Bossa Nova",
    "Cajun",
    "Calypso",
    "Chiptune",
    "Cumbia",
    "Dance Pop",
    "Darkwave",
    "Drill",
    "Electro Swing",
    "Eurodance",
    "Fado",
    "Freakbeat",
    "Garage Punk",
    "Grindcore",
    "Glam Rock",
    "Gothic Rock",
    "Hardstyle",
    "Hi-NRG",
    "House Music",
    "J-Pop",
    "Krautrock",
    "Latin Jazz",
    "Mariachi",
    "Merengue",
    "Metalcore",
    "Microhouse",
    "Neo Soul",
    "Neue Deutsche Welle",
    "Nu Metal",
    "Oldies",
    "Polka",
    "Pop Punk",
    "Post Hardcore",
    "Power Pop",
    "Progressive Metal",
    "Psychedelic Rock",
    "Salsa",
    "Samba",
    "Screamo",
    "Ska Punk",
    "Soft Rock",
    "Southern Rock",
    "Space Rock",
    "Speed Metal",
    "Swing Jazz",
    "Synthpop",
    "Tejano",
    "Thrash",
    "Trap",
    "Vaporwave",
    "Western Swing",
    "Zouk",
    "Chillout",
    "Celtic",
    "Dancehall",
    "Electropop",
    "Folk Rock",
    "Garage House",
    "Glam Metal",
    "Hard Bop",
    "Jazz Blues",
    "Jazz Funk",
    "Latin Pop",
    "Lo-fi Hip Hop",
    "Modern Classical",
    "Neo Folk",
    "New Age",
    "Noise Rock",
    "Post Disco",
    "Post Punk Revival",
    "Power Electronics",
    "Psytrance",
    "Shoegaze",
    "Synthpunk",
    "Tech House",
    "Techno Hardcore",
];

pub const MUSICAL_INSTRUMENTS: [&str; 182] = [
    "Piano",
    "Violin",
    "Guitar",
    "Flute",
    "Drums",
    "Saxophone",
    "Trumpet",
    "Cello",
    "Clarinet",
    "Harp",
    "Trombone",
    "Bassoon",
    "Oboe",
    "Accordion",
    "Banjo",
    "Bass Guitar",
    "French Horn",
    "Tuba",
    "Double Bass",
    "Mandolin",
    "Harmonica",
    "Synthesizer",
    "Xylophone",
    "Marimba",
    "Didgeridoo",
    "Bagpipes",
    "Ukulele",
    "Congas",
    "Tabla",
    "Bongo",
    "Castanets",
    "Djembe",
    "Tambourine",
    "Pan Flute",
    "Recorder",
    "Melodica",
    "Bass Clarinet",
    "Piccolo",
    "Ocarina",
    "Sitar",
    "Kalimba",
    "Lute",
    "Zither",
    "Cajón",
    "Electric Guitar",
    "Timpani",
    "Sousaphone",
    "Bass Drum",
    "Celesta",
    "Euphonium",
    "Steel Drum",
    "Flugelhorn",
    "Santoor",
    "Shakuhachi",
    "Vibraphone",
    "Electric Bass",
    "Bassoon",
    "Glockenspiel",
    "Hurdy-Gurdy",
    "Jaw Harp",
    "Koto",
    "Lazavox",
    "Lyre",
    "Maracas",
    "Mbira",
    "Musical Saw",
    "Nagoya Harp",
    "Nyckelharpa",
    "Panpipes",
    "Pennywhistle",
    "Piccolo Trumpet",
    "Quena",
    "Rebab",
    "Santoor",
    "Shamisen",
    "Shehnai",
    "Sheng",
    "Suling",
    "Surdu",
    "Theremin",
    "Triangle",
    "Uilleann Pipes",
    "Waterphone",
    "Whistle",
    "Woodblock",
    "Yangqin",
    "Zabumba",
    "Zurna",
    "Bass Recorder",
    "Baritone Saxophone",
    "Contrabassoon",
    "Contrabass Clarinet",
    "Octobass",
    "Sarrusophone",
    "Serpent",
    "Tubular Bells",
    "Washboard",
    "Alphorn",
    "Bandoneon",
    "Chapman Stick",
    "Clavichord",
    "Crwth",
    "Duduk",
    "Glass Harmonica",
    "Hardanger Fiddle",
    "Laúd",
    "Lur",
    "Ondes Martenot",
    "Pennywhistle",
    "Psaltery",
    "Rebab",
    "Sanza",
    "Serpent",
    "Suling",
    "Theremin",
    "Timpani",
    "Tongue Drum",
    "Vuvuzela",
    "Wagakki",
    "Water Drum",
    "Yangqin",
    "Zheng",
    "Zurna",
    "Zills",
    "Zithers",
    "Agogo Bells",
    "Anklung",
    "Balalaika",
    "Bass Recorder",
    "Baritone Horn",
    "Bawu",
    "Bendir",
    "Bodhrán",
    "Bombard",
    "Bouzouki",
    "Calimba",
    "Cimbalom",
    "Claves",
    "Conga Drums",
    "Cuíca",
    "Damaru",
    "Dhol",
    "Djembe",
    "Dizi",
    "Erhu",
    "Fife",
    "Gaita",
    "Gamelan",
    "Gong",
    "Guiro",
    "Hang Drum",
    "Hardanger Fiddle",
    "Hurdy-Gurdy",
    "Kamancheh",
    "Kaval",
    "Khomus",
    "Kora",
    "Lá Làn",
    "Lur",
    "Mbira",
    "Morin Khuur",
    "Nai",
    "Ngoni",
    "Nyckelharpa",
    "Ocarina",
    "Pandeiro",
    "Pungi",
    "Rabab",
    "Sanza",
    "Sarangi",
    "Shakuhachi",
    "Shekere",
    "Sheng",
    "Shofar",
    "Sitar",
    "Tambura",
    "Tiple",
    "Trombone",
    "Trống",
    "Udu",
    "Veena",
    "Zither",
];
