pub const CAR_BRANDS: [&str; 101] = [
    "Toyota",
    "Ford",
    "Honda",
    "Chevrolet",
    "Mercedes",
    "BMW",
    "Audi",
    "Volkswagen",
    "Hyundai",
    "Nissan",
    "Kia",
    "Subaru",
    "Mazda",
    "Lexus",
    "Jaguar",
    "Tesla",
    "Volvo",
    "Ferrari",
    "Porsche",
    "Land Rover",
    "Bentley",
    "Mitsubishi",
    "Renault",
    "Fiat",
    "Skoda",
    "Suzuki",
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Bugatti",
    "Cadillac",
    "Chrysler",
    "Dodge",
    "Genesis",
    "GMC",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Lamborghini",
    "Land Rover",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Mini",
    "Mitsubishi",
    "Opel",
    "Ram",
    "Rolls-Royce",
    "Saab",
    "Seat",
    "Smart",
    "SsangYong",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "McLaren",
    "Pagani",
    "Mahindra",
    "Tata",
    "Dacia",
    "Lada",
    "Geely",
    "Great Wall",
    "Haval",
    "BYD",
    "Chery",
    "ZX Auto",
    "Fisker",
    "Rivian",
    "Polestar",
    "Lucid",
    "Caterham",
    "Scion",
    "Vauxhall",
    "Zotye",
    "Perodua",
    "Proton",
    "Hennessey",
    "Ginetta",
    "Dodge",
    "MG",
    "Holden",
    "Lincoln",
    "Cadillac",
    "Hummer",
    "Saturn",
    "Oldsmobile",
    "Pontiac",
    "Saab",
    "Isuzu",
    "Daewoo",
    "Skoda",
    "Lancia",
    "Alpina",
    "DeLorean",
    "Troller",
    "Morgan",
    "Tesla",
    "Peugeot",
];

pub const COMPANY_NAMES: [&str; 153] = [
    "Apple",
    "Google",
    "Microsoft",
    "Amazon",
    "Meta",
    "Tesla",
    "IBM",
    "Intel",
    "Samsung",
    "Sony",
    "LG",
    "Dell",
    "HP",
    "Lenovo",
    "Nvidia",
    "AMD",
    "Oracle",
    "Cisco",
    "Salesforce",
    "Adobe",
    "Spotify",
    "Netflix",
    "Uber",
    "Airbnb",
    "Twitter",
    "Snap",
    "TikTok",
    "Alibaba",
    "Tencent",
    "Baidu",
    "Xiaomi",
    "Huawei",
    "SpaceX",
    "Stripe",
    "Shopify",
    "Dropbox",
    "Zoom",
    "Red Hat",
    "GitHub",
    "Bitbucket",
    "DigitalOcean",
    "Slack",
    "WeWork",
    "Siemens",
    "Bosch",
    "Philips",
    "Panasonic",
    "Toshiba",
    "NEC",
    "Asus",
    "Acer",
    "Razer",
    "Qualcomm",
    "Arm",
    "Ericsson",
    "Nokia",
    "ZTE",
    "T-Mobile",
    "AT&T",
    "Verizon",
    "Vodafone",
    "Orange",
    "BT",
    "China Mobile",
    "NTT",
    "Rakuten",
    "SoftBank",
    "SK Telecom",
    "Lyft",
    "Pinterest",
    "eBay",
    "PayPal",
    "Square",
    "Block",
    "Intuit",
    "Bloomberg",
    "Reuters",
    "BBC",
    "CNN",
    "Fox",
    "NBC",
    "Disney",
    "Pixar",
    "Marvel",
    "Warner Bros.",
    "Paramount",
    "Universal",
    "Sony Pictures",
    "HBO",
    "Hulu",
    "Peacock",
    "TikTok",
    "ByteDance",
    "Alibaba",
    "JD.com",
    "Rakuten",
    "Flipkart",
    "Oppo",
    "Vivo",
    "OnePlus",
    "Realme",
    "Honor",
    "Motorola",
    "BlackBerry",
    "Fairphone",
    "Nothing",
    "Steam",
    "Epic Games",
    "Valve",
    "Electronic Arts",
    "Activision",
    "Blizzard",
    "Ubisoft",
    "Square Enix",
    "Bandai Namco",
    "Sega",
    "Nintendo",
    "Konami",
    "Capcom",
    "Rockstar",
    "Bethesda",
    "CD Projekt",
    "IKEA",
    "Zara",
    "H&M",
    "Uniqlo",
    "Adidas",
    "Nike",
    "Puma",
    "Under Armour",
    "Reebok",
    "LVMH",
    "Chanel",
    "Gucci",
    "Prada",
    "Hermès",
    "Cartier",
    "Rolex",
    "Omega",
    "Swatch",
    "Nestlé",
    "Coca-Cola",
    "PepsiCo",
    "Unilever",
    "Procter & Gamble",
    "Danone",
    "Kraft Heinz",
    "General Mills",
    "Mars",
    "Heineken",
    "Anheuser-Busch",
    "L'Oréal",
    "Johnson & Johnson",
];

pub const JOBS: [&str; 173] = [
    "Accountant",
    "Actor",
    "Actuary",
    "Architect",
    "Artist",
    "Astronomer",
    "Attorney",
    "Auditor",
    "Baker",
    "Banker",
    "Barber",
    "Biologist",
    "Bookkeeper",
    "Broker",
    "Butcher",
    "Carpenter",
    "Chef",
    "Chemist",
    "Clerk",
    "Coach",
    "Consultant",
    "Dentist",
    "Designer",
    "Developer",
    "Dietitian",
    "Doctor",
    "Driver",
    "Economist",
    "Editor",
    "Electrician",
    "Engineer",
    "Farmer",
    "Fashion Designer",
    "Firefighter",
    "Fisherman",
    "Florist",
    "Gardener",
    "Geologist",
    "Graphic Designer",
    "Hairdresser",
    "Health Inspector",
    "Historian",
    "Illustrator",
    "Interpreter",
    "Janitor",
    "Journalist",
    "Judge",
    "Laborer",
    "Lawyer",
    "Librarian",
    "Mechanic",
    "Meteorologist",
    "Musician",
    "Nurse",
    "Nutritionist",
    "Occupational Therapist",
    "Optician",
    "Painter",
    "Paramedic",
    "Pharmacist",
    "Photographer",
    "Physician",
    "Physiotherapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Politician",
    "Professor",
    "Programmer",
    "Psychologist",
    "Receptionist",
    "Researcher",
    "Salesperson",
    "Scientist",
    "Secretary",
    "Security Guard",
    "Singer",
    "Social Worker",
    "Statistician",
    "Surgeon",
    "Teacher",
    "Technician",
    "Translator",
    "Travel Agent",
    "Truck Driver",
    "Veterinarian",
    "Waiter",
    "Web Developer",
    "Writer",
    "Zoologist",
    "Animator",
    "Archaeologist",
    "Auditor",
    "Biochemist",
    "Cartographer",
    "Choreographer",
    "Counselor",
    "Curator",
    "Dancer",
    "Data Analyst",
    "Database Administrator",
    "Dietitian",
    "Economist",
    "Editor",
    "Electrical Engineer",
    "Environmental Scientist",
    "Event Planner",
    "Fashion Designer",
    "Film Director",
    "Firefighter",
    "Fitness Trainer",
    "Flight Attendant",
    "Game Designer",
    "Geographer",
    "Graphic Artist",
    "HR Specialist",
    "Insurance Agent",
    "Interior Designer",
    "IT Specialist",
    "Journalist",
    "Judge",
    "Laboratory Technician",
    "Law Enforcement Officer",
    "Legal Advisor",
    "Linguist",
    "Logistician",
    "Marketing Manager",
    "Mathematician",
    "Mechanical Engineer",
    "Medical Technician",
    "Microbiologist",
    "Network Engineer",
    "Nuclear Engineer",
    "Occupational Therapist",
    "Oceanographer",
    "Operations Manager",
    "Orthodontist",
    "Paralegal",
    "Park Ranger",
    "Petroleum Engineer",
    "Pharmacologist",
    "Physicist",
    "Pilot",
    "Plumber",
    "Product Manager",
    "Programmer",
    "Project Manager",
    "Psychiatrist",
    "Quality Analyst",
    "Real Estate Agent",
    "Receptionist",
    "Robotics Engineer",
    "Safety Officer",
    "Sales Manager",
    "Scientist",
    "Social Scientist",
    "Software Engineer",
    "Statistician",
    "Stockbroker",
    "Surgeon",
    "Systems Analyst",
    "Tax Advisor",
    "Teacher",
    "Technical Writer",
    "Translator",
    "Urban Planner",
    "UX Designer",
    "Veterinarian",
    "Video Editor",
    "Web Designer",
    "Writer",
    "Yoga Instructor",
    "Zoologist",
];
