pub const CURRENCY_NAMES: &[&str] = &[
    "Argentine Peso",
    "Australian Dollar",
    "Bahraini Dinar",
    "Bangladeshi Taka",
    "Brazilian Real",
    "British Pound",
    "Canadian Dollar",
    "Chilean Peso",
    "Chinese Yuan",
    "Colombian Peso",
    "Costa Rican Colon",
    "Croatian Kuna",
    "Czech Koruna",
    "Danish Krone",
    "Egyptian Pound",
    "Euro",
    "Hong Kong Dollar",
    "Hungarian Forint",
    "Icelandic Krona",
    "Indian Rupee",
    "Indonesian Rupiah",
    "Israeli New Shekel",
    "Japanese Yen",
    "Jordanian Dinar",
    "Kuwaiti Dinar",
    "Lebanese Pound",
    "Malaysian Ringgit",
    "Mexican Peso",
    "Moroccan Dirham",
    "New Zealand Dollar",
    "Norwegian Krone",
    "Omani Rial",
    "Pakistani Rupee",
    "Peruvian Sol",
    "Philippine Peso",
    "Polish Zloty",
    "Qatari Riyal",
    "Russian Ruble",
    "Saudi Riyal",
    "Singapore Dollar",
    "South African Rand",
    "South Korean Won",
    "Swedish Krona",
    "Swiss Franc",
    "Thai Baht",
    "Turkish Lira",
    "US Dollar",
    "Ukrainian Hryvnia",
    "United Arab Emirates Dirham",
    "Vietnamese Dong",
];

pub const CURRENCY_SYMBOLS: &[&str] = &[
    "$", "£", "¥", "฿", "₠", "₡", "₣", "₤", "₥", "₦", "₧", "₨", "₩", "₪", "₫", "€", "₭", "₮", "₯",
    "₰", "₱", "₲", "₳", "₴", "₵", "₸", "₹", "₺", "₼", "₽",
];

pub const CURRENCY_CODES: &[&str] = &[
    "AED", "ARS", "AUD", "BDT", "BHD", "BRL", "CAD", "CHF", "CLP", "CNY", "COP", "CRC", "CZK",
    "DKK", "EGP", "EUR", "GBP", "HKD", "HRK", "HUF", "IDR", "ILS", "INR", "ISK", "JOD", "JPY",
    "KRW", "KWD", "LBP", "MAD", "MXN", "MYR", "NOK", "NZD", "OMR", "PEN", "PHP", "PKR", "PLN",
    "QAR", "RUB", "SAR", "SEK", "SGD", "THB", "TRY", "UAH", "USD", "VND", "ZAR",
];
