pub const FRENCH_STREETS: &[&str] = &[
    "Avenue Montaigne",
    "Avenue des Champs Elysees",
    "Boulevard Beaumarchais",
    "Boulevard Bonne Nouvelle",
    "Boulevard Haussmann",
    "Boulevard Montmartre",
    "Boulevard Saint Germain",
    "Boulevard Voltaire",
    "Boulevard des Italiens",
    "Rue Cler",
    "Rue Lafayette",
    "Rue Mouffetard",
    "Rue Oberkampf",
    "Rue Saint Antoine",
    "Rue Saint Bernard",
    "Rue Saint Charles",
    "Rue Saint Denis",
    "Rue Saint Dominique",
    "Rue Saint Georges",
    "Rue Saint Honore",
    "Rue Saint Jacques",
    "Rue Saint Lazare",
    "Rue Saint Martin",
    "Rue de Bellechasse",
    "Rue de Belleville",
    "Rue de Buci",
    "Rue de Castiglione",
    "Rue de Douai",
    "Rue de Grenelle",
    "Rue de Lappe",
    "Rue de Rennes",
    "Rue de Rivoli",
    "Rue de Seine",
    "Rue de Turenne",
    "Rue de Vaugirard",
    "Rue de l'Abbe de l'Epee",
    "Rue de l'Eglise",
    "Rue de l'Odéon",
    "Rue de la Barre",
    "Rue de la Boetie",
    "Rue de la Bourse",
    "Rue de la Clef",
    "Rue de la Convention",
    "Rue de la Fayette",
    "Rue de la Fontaine",
    "Rue de la Harpe",
    "Rue de la Huchette",
    "Rue de la Monnaie",
    "Rue de la Paix",
    "Rue de la Pompe",
    "Rue de la Roquette",
    "Rue de la Tour",
    "Rue de la Tour d'Auvergne",
    "Rue de la Victoire",
    "Rue de la Villette",
    "Rue des Archives",
    "Rue des Ecoles",
    "Rue des Francs Bourgeois",
    "Rue des Martyrs",
    "Rue des Petits Champs",
    "Rue des Rosiers",
    "Rue du Bac",
    "Rue du Chemin Vert",
    "Rue du Cherche Midi",
    "Rue du Commerce",
    "Rue du Faubourg Montmartre",
    "Rue du Faubourg Poissonniere",
    "Rue du Faubourg Saint Antoine",
    "Rue du Faubourg Saint Denis",
    "Rue du Faubourg Saint Honore",
    "Rue du Faubourg Saint Martin",
    "Rue du Mont Thabor",
    "Rue du Pont Neuf",
    "Rue du Temple",
];

pub const FRENCH_ROAD_TYPES: &[&str] = &[
    "Allée",
    "Avenue",
    "Boulevard",
    "Chemin",
    "Clos",
    "Cours",
    "Domaine",
    "Esplanade",
    "Impasse",
    "Passage",
    "Place",
    "Promenade",
    "Quai",
    "Route",
    "Rue",
    "Ruelle",
    "Sentier",
    "Square",
    "Traverse",
    "Voie",
];

pub const FRENCH_COUNTIES: &[&str] = &[
    "Ain",
    "Aisne",
    "Allier",
    "Alpes-Maritimes",
    "Alpes-de-Haute-Provence",
    "Ardennes",
    "Ardèche",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bas-Rhin",
    "Bouches-du-Rhône",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente-Maritime",
    "Cher",
    "Corrèze",
    "Corse-du-Sud",
    "Creuse",
    "Côte-d'Or",
    "Côtes-d'Armor",
    "Deux-Sèvres",
    "Dordogne",
    "Doubs",
    "Drôme",
    "Essonne",
    "Eure",
    "Eure-et-Loir",
    "Finistère",
    "Gard",
    "Gers",
    "Gironde",
    "Guadeloupe",
    "Guyane",
    "Haut-Rhin",
    "Haute-Corse",
    "Haute-Garonne",
    "Haute-Loire",
    "Haute-Marne",
    "Haute-Savoie",
    "Haute-Saône",
    "Haute-Vienne",
    "Hautes-Alpes",
    "Hautes-Pyrénées",
    "Hauts-de-Seine",
    "Hérault",
    "Ille-et-Vilaine",
    "Indre",
    "Indre-et-Loire",
    "Isère",
    "Jura",
    "La Réunion",
    "Landes",
    "Loir-et-Cher",
    "Loire",
    "Loire-Atlantique",
    "Loiret",
    "Lot",
    "Lot-et-Garonne",
    "Lozère",
    "Maine-et-Loire",
    "Manche",
    "Marne",
    "Martinique",
    "Mayenne",
    "Mayotte",
    "Meurthe-et-Moselle",
    "Meuse",
    "Morbihan",
    "Moselle",
    "Nièvre",
    "Nord",
    "Oise",
    "Orne",
    "Paris",
    "Pas-de-Calais",
    "Puy-de-Dôme",
    "Pyrénées-Atlantiques",
    "Pyrénées-Orientales",
    "Rhône",
    "Sarthe",
    "Savoie",
    "Saône-et-Loire",
    "Seine-Maritime",
    "Seine-Saint-Denis",
    "Seine-et-Marne",
    "Somme",
    "Tarn",
    "Tarn-et-Garonne",
    "Territoire de Belfort",
    "Val-d'Oise",
    "Val-de-Marne",
    "Var",
    "Vaucluse",
    "Vendée",
    "Vienne",
    "Vosges",
    "Yonne",
    "Yvelines",
];

pub const LONGEST_FRENCH_RIVERS: &[&str] = &[
    "Adour",
    "Aisne",
    "Allier",
    "Ardèche",
    "Aube",
    "Aude",
    "Bléone",
    "Charente",
    "Cher",
    "Creuse",
    "Cèze",
    "Dives",
    "Dordogne",
    "Durance",
    "Eure",
    "Garonne",
    "Gave d'Oloron",
    "Gave de Pau",
    "Hérault",
    "L'Ain",
    "L'Allier",
    "L'Indre",
    "L'Oise",
    "La Dordogne",
    "La Drôme",
    "La Durance",
    "La Garonne",
    "La Meurthe",
    "La Nive",
    "La Saône",
    "La Vienne",
    "La Vilaine",
    "Loir",
    "Loire",
    "Lot",
    "Marne",
    "Mayenne",
    "Meuse",
    "Moselle",
    "Oise",
    "Orne",
    "Rhône",
    "Sarthe",
    "Saône",
    "Seine",
    "Somme",
    "Sèvre Niortaise",
    "Tarn",
    "Vienne",
    "Vézère",
];
