pub const HISTORICAL_BATTLES: &[&str] = &[
    "Battle of Actium",
    "Battle of Adrianople",
    "Battle of Aegospotami",
    "Battle of Agincourt",
    "Battle of Agnadello",
    "Battle of Alesia",
    "Battle of Amiens",
    "Battle of Antietam",
    "Battle of Appomattox Court House",
    "Battle of Arras",
    "Battle of Austerlitz",
    "Battle of Bannockburn",
    "Battle of Berlin",
    "Battle of Blenheim",
    "Battle of Borodino",
    "Battle of Bosworth",
    "Battle of Bosworth Field",
    "Battle of Breitenfeld",
    "Battle of Bunker Hill",
    "Battle of Cambrai",
    "Battle of Cannae",
    "Battle of Caporetto",
    "Battle of Carrhae",
    "Battle of Castillon",
    "Battle of Chaeronea",
    "Battle of Chalons",
    "Battle of Chancellorsville",
    "Battle of Chickamauga",
    "Battle of Cold Harbor",
    "Battle of Coral Sea",
    "Battle of Crecy",
    "Battle of Culloden",
    "Battle of Dien Bien Phu",
    "Battle of El Alamein",
    "Battle of Fallujah",
    "Battle of Flodden",
    "Battle of Fontenoy",
    "Battle of Fredericksburg",
    "Battle of Gallipoli",
    "Battle of Gaugamela",
    "Battle of Gettysburg",
    "Battle of Guadalcanal",
    "Battle of Hastings",
    "Battle of Hue",
    "Battle of Inchon",
    "Battle of Issus",
    "Battle of Iwo Jima",
    "Battle of Jena",
    "Battle of Jutland",
    "Battle of Khe Sanh",
    "Battle of Khotyn",
    "Battle of Kursk",
    "Battle of Legnano",
    "Battle of Leipzig",
    "Battle of Lepanto",
    "Battle of Leyte Gulf",
    "Battle of Lützen",
    "Battle of Manila Bay",
    "Battle of Manzikert",
    "Battle of Marathon",
    "Battle of Marne",
    "Battle of Marston Moor",
    "Battle of Megiddo",
    "Battle of Midway",
    "Battle of Mohács",
    "Battle of Mosul",
    "Battle of Naseby",
    "Battle of New Orleans",
    "Battle of Okinawa",
    "Battle of Passchendaele",
    "Battle of Philippi",
    "Battle of Pinkie Cleugh",
    "Battle of Plassey",
    "Battle of Plataea",
    "Battle of Poitiers",
    "Battle of Poltava",
    "Battle of Roncevaux Pass",
    "Battle of Salamanca",
    "Battle of Salamis",
    "Battle of Saratoga",
    "Battle of Sedan",
    "Battle of Somme",
    "Battle of Stalingrad",
    "Battle of Tannenberg",
    "Battle of Thermopylae",
    "Battle of Tours",
    "Battle of Trafalgar",
    "Battle of Verdun",
    "Battle of Vicksburg",
    "Battle of Vienna",
    "Battle of Vimy Ridge",
    "Battle of Wagram",
    "Battle of Waterloo",
    "Battle of Wounded Knee",
    "Battle of Yorktown",
    "Battle of Zama",
    "Battle of the Bulge",
    "Battle of the Somme",
];
