pub const HISTORICAL_BATTLES: [&str; 147] = [
    "Battle of Hastings",
    "Battle of Waterloo",
    "Battle of Gettysburg",
    "Battle of Thermopylae",
    "Battle of Stalingrad",
    "Battle of Midway",
    "Battle of Agincourt",
    "Battle of Trafalgar",
    "Battle of Lepanto",
    "Battle of Marathon",
    "Battle of Yorktown",
    "Battle of Bannockburn",
    "Battle of Kursk",
    "Battle of Culloden",
    "Battle of Austerlitz",
    "Battle of Salamis",
    "Battle of Gallipoli",
    "Battle of Verdun",
    "Battle of Chancellorsville",
    "Battle of the Bulge",
    "Battle of Actium",
    "Battle of Poitiers",
    "Battle of Tours",
    "Battle of Cannae",
    "Battle of Zama",
    "Battle of Antietam",
    "Battle of Philippi",
    "Battle of Adrianople",
    "Battle of Roncevaux Pass",
    "Battle of Plataea",
    "Battle of Bunker Hill",
    "Battle of Berlin",
    "Battle of the Somme",
    "Battle of Vimy Ridge",
    "Battle of Sedan",
    "Battle of Agnadello",
    "Battle of Hastings",
    "Battle of Mohács",
    "Battle of Alesia",
    "Battle of Carrhae",
    "Battle of Crecy",
    "Battle of Poitiers",
    "Battle of Trafalgar",
    "Battle of Naseby",
    "Battle of Bosworth Field",
    "Battle of Lepanto",
    "Battle of Marston Moor",
    "Battle of Breitenfeld",
    "Battle of Poltava",
    "Battle of Blenheim",
    "Battle of Plassey",
    "Battle of Yorktown",
    "Battle of Bunker Hill",
    "Battle of Wounded Knee",
    "Battle of New Orleans",
    "Battle of Antietam",
    "Battle of Fredericksburg",
    "Battle of Chancellorsville",
    "Battle of Gettysburg",
    "Battle of Chickamauga",
    "Battle of Cold Harbor",
    "Battle of Appomattox Court House",
    "Battle of Manila Bay",
    "Battle of Tannenberg",
    "Battle of Gallipoli",
    "Battle of Verdun",
    "Battle of Jutland",
    "Battle of Caporetto",
    "Battle of Cambrai",
    "Battle of Amiens",
    "Battle of Megiddo",
    "Battle of El Alamein",
    "Battle of Kursk",
    "Battle of Leyte Gulf",
    "Battle of Iwo Jima",
    "Battle of Okinawa",
    "Battle of Berlin",
    "Battle of Midway",
    "Battle of Guadalcanal",
    "Battle of Coral Sea",
    "Battle of Dien Bien Phu",
    "Battle of Inchon",
    "Battle of Khe Sanh",
    "Battle of Hue",
    "Battle of Fallujah",
    "Battle of Mosul",
    "Battle of Verdun",
    "Battle of Marne",
    "Battle of Amiens",
    "Battle of Somme",
    "Battle of Arras",
    "Battle of Passchendaele",
    "Battle of Jena",
    "Battle of Leipzig",
    "Battle of Borodino",
    "Battle of Salamanca",
    "Battle of Lützen",
    "Battle of Wagram",
    "Battle of Trafalgar",
    "Battle of Vienna",
    "Battle of Lepanto",
    "Battle of Mohács",
    "Battle of Issus",
    "Battle of Gaugamela",
    "Battle of Marathon",
    "Battle of Thermopylae",
    "Battle of Plataea",
    "Battle of Chaeronea",
    "Battle of Aegospotami",
    "Battle of Salamis",
    "Battle of Actium",
    "Battle of Adrianople",
    "Battle of Chalons",
    "Battle of Tours",
    "Battle of Hastings",
    "Battle of Manzikert",
    "Battle of Legnano",
    "Battle of Bannockburn",
    "Battle of Agincourt",
    "Battle of Castillon",
    "Battle of Bosworth",
    "Battle of Flodden",
    "Battle of Pinkie Cleugh",
    "Battle of Khotyn",
    "Battle of Vienna",
    "Battle of Blenheim",
    "Battle of Poltava",
    "Battle of Fontenoy",
    "Battle of Culloden",
    "Battle of Bunker Hill",
    "Battle of Saratoga",
    "Battle of Yorktown",
    "Battle of New Orleans",
    "Battle of Gettysburg",
    "Battle of Antietam",
    "Battle of Chancellorsville",
    "Battle of Vicksburg",
    "Battle of Appomattox Court House",
    "Battle of Manila Bay",
    "Battle of Midway",
    "Battle of Leyte Gulf",
    "Battle of Guadalcanal",
    "Battle of Stalingrad",
    "Battle of Kursk",
    "Battle of the Bulge",
    "Battle of Berlin",
    "Battle of Okinawa",
];
