pub const PROGRAMMING_LANGUAGES: [&str; 146] = [
    "Rust",
    "C",
    "C++",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Swift",
    "Kotlin",
    "Ruby",
    "PHP",
    "Perl",
    "Scala",
    "Haskell",
    "Elixir",
    "Dart",
    "Lua",
    "Objective-C",
    "C#",
    "F#",
    "MATLAB",
    "Groovy",
    "COBOL",
    "Fortran",
    "Ada",
    "R",
    "Visual Basic",
    "Julia",
    "Bash",
    "PowerShell",
    "Scheme",
    "Prolog",
    "Lisp",
    "Erlang",
    "Smalltalk",
    "Delphi",
    "VHDL",
    "Assembly",
    "Crystal",
    "Nim",
    "OCaml",
    "Zig",
    "Clojure",
    "D",
    "Tcl",
    "Hack",
    "Elm",
    "ReasonML",
    "Solidity",
    "Awk",
    "Forth",
    "Racket",
    "Idris",
    "Mercury",
    "Pony",
    "Vala",
    "NATURAL",
    "Algol",
    "ColdFusion",
    "Groovy",
    "ActionScript",
    "VBScript",
    "Q#",
    "AngelScript",
    "Hack",
    "Chapel",
    "PL/SQL",
    "Xojo",
    "REXX",
    "ABAP",
    "OpenCL",
    "OpenGL Shading Language",
    "Haxe",
    "J#",
    "KornShell",
    "OCaml",
    "QBasic",
    "Sed",
    "SPARK",
    "Transact-SQL",
    "VHDL",
    "Verilog",
    "Wolfram",
    "Yorick",
    "Zsh",
    "Hack",
    "GAMS",
    "Eiffel",
    "CFML",
    "DCL",
    "SAS",
    "Logo",
    "Modula-2",
    "NATURAL",
    "Pascal",
    "PL/I",
    "PowerBuilder",
    "RPG",
    "Simula",
    "Smalltalk",
    "SNOBOL",
    "Tcl",
    "VBA",
    "Wolfram Language",
    "Zig",
    "ZPL",
    "Bourne shell",
    "Caml",
    "Curl",
    "Dylan",
    "F#",
    "IDL",
    "J",
    "LabVIEW",
    "Ladder Logic",
    "LiveCode",
    "Lovelace",
    "M4",
    "MUMPS",
    "NATURAL",
    "Nimrod",
    "OCaml",
    "OpenCL",
    "OpenEdge ABL",
    "PL/SQL",
    "PostScript",
    "PowerShell",
    "PureBasic",
    "Q",
    "Racket",
    "REXX",
    "Ring",
    "SAS",
    "Scala",
    "Scheme",
    "Scratch",
    "Smalltalk",
    "SPARK",
    "Swift",
    "Tcl",
    "Transact-SQL",
    "VB.NET",
    "Visual Basic",
    "Xojo",
    "Zig",
    "ZPL",
];

pub const PROGRAMMING_PARADIGMS: [&str; 148] = [
    "Procedural",
    "Object-Oriented",
    "Functional",
    "Declarative",
    "Imperative",
    "Event-Driven",
    "Logic",
    "Concurrent",
    "Aspect-Oriented",
    "Generic",
    "Reflective",
    "Reactive",
    "Metaprogramming",
    "Symbolic",
    "Data-Driven",
    "Component-Based",
    "Flow-Based",
    "Stack-Based",
    "Array-Based",
    "Constraint-Based",
    "Service-Oriented",
    "Agent-Oriented",
    "Distributed",
    "Visual",
    "Quantum",
    "Automata-Based",
    "Pipeline",
    "Rule-Based",
    "Process-Oriented",
    "Transformational",
    "Hybrid",
    "Modular",
    "Actor-Based",
    "Message-Passing",
    "State-Based",
    "Class-Based",
    "Prototype-Based",
    "Batch",
    "Lazy Evaluation",
    "Strict Evaluation",
    "Pure",
    "Non-Pure",
    "Reflective",
    "Extensible",
    "Concurrent",
    "Parallel",
    "Functional Reactive",
    "Imperative Reactive",
    "Probabilistic",
    "Aspect",
    "Structured",
    "Object-Based",
    "Stack",
    "Procedural-Oriented",
    "Event-Based",
    "Dataflow",
    "Reactive Programming",
    "Declarative Programming",
    "Domain-Specific",
    "Embedded",
    "Episodic",
    "Function-Level",
    "Generic Programming",
    "Interactive",
    "Logic Programming",
    "Metaprogramming",
    "Non-Deterministic",
    "Object-Functional",
    "Parallel Programming",
    "Pipeline",
    "Procedural Programming",
    "Reactive Programming",
    "Rule-Based Programming",
    "Signal-Based",
    "Synchronous Programming",
    "Transformational Programming",
    "Unification-Based",
    "Visual Programming",
    "Weakly Typed",
    "Strongly Typed",
    "Dynamic Typing",
    "Static Typing",
    "Duck Typing",
    "Gradual Typing",
    "Nominal Typing",
    "Structural Typing",
    "Subtyping",
    "Dependent Typing",
    "Intersection Typing",
    "Union Typing",
    "Flow Typing",
    "Behavioral Typing",
    "Actor Model",
    "Lambda Calculus",
    "Process Calculus",
    "Predicate Logic",
    "Temporal Logic",
    "Concurrent Constraint Programming",
    "Event Calculus",
    "Functional Logic Programming",
    "Probabilistic Programming",
    "Stochastic Programming",
    "Constraint Logic Programming",
    "Imperative Programming",
    "Logic-Based Programming",
    "Monadic Programming",
    "Object-Oriented Programming",
    "Prototype-Based Programming",
    "Reflective Programming",
    "Relational Programming",
    "Scripted Programming",
    "Symbolic Programming",
    "Typed Programming",
    "Untyped Programming",
    "Web Programming",
    "XML Programming",
    "Aspect-Oriented Programming",
    "Component-Oriented Programming",
    "Data-Oriented Programming",
    "Declarative Programming",
    "Embedded Programming",
    "Functional Programming",
    "Generic Programming",
    "Imperative Programming",
    "Metaprogramming",
    "Modular Programming",
    "Object-Oriented Programming",
    "Procedural Programming",
    "Reactive Programming",
    "Rule-Based Programming",
    "Service-Oriented Programming",
    "Visual Programming",
    "Workflow Programming",
    "Block-Based Programming",
    "Constraint Programming",
    "Dataflow Programming",
    "Declarative Programming",
    "Event-Driven Programming",
    "Functional Programming",
    "Imperative Programming",
    "Logic Programming",
    "Object-Oriented Programming",
    "Procedural Programming",
    "Reactive Programming",
    "Rule-Based Programming",
    "Structured Programming",
    "Symbolic Programming",
    "Workflow Programming",
];

pub const EDITOR_COLOR_THEMES: [&str; 124] = [
    "One Dark Pro Monokai Darker",
    "Monokai",
    "Solarized Light",
    "Solarized Dark",
    "Dracula",
    "Gruvbox",
    "One Dark",
    "Nord",
    "Palenight",
    "Material",
    "Atom One Dark",
    "Atom One Light",
    "Cobalt",
    "Tomorrow Night",
    "Tomorrow",
    "Shades of Purple",
    "Night Owl",
    "Oceanic Next",
    "Ayu Dark",
    "Ay Light",
    "Base16",
    "Dark+ (default dark)",
    "Light+ (default light)",
    "Kimbie Dark",
    "Kimbie Light",
    "SynthWave '84",
    "Horizon",
    "Bluloco Light",
    "Bluloco Dark",
    "GitHub Light",
    "GitHub Dark",
    "Quiet Light",
    "Red",
    "Solarized Dark Higher Contrast",
    "Solarized Light Higher Contrast",
    "Tango",
    "Zenburn",
    "Panda",
    "Material Palenight",
    "Material Ocean",
    "Material Darker",
    "Material Lighter",
    "Material Vivid",
    "Material Oceanic",
    "One Light",
    "Sublime Text",
    "Visual Studio",
    "Visual Studio Dark",
    "Darkula",
    "Cobalt2",
    "Dracula Official",
    "PaperColor",
    "Monokai Pro",
    "Firefly",
    "Atom One Dark Reasonable",
    "Neon",
    "Iceberg",
    "Hopscotch",
    "Brogrammer",
    "Paraiso Dark",
    "Paraiso Light",
    "Bluloco",
    "Solarized Dark (official)",
    "Solarized Light (official)",
    "Noctis",
    "Winter is Coming",
    "Oceanic Next",
    "Material Theme",
    "Night Fox",
    "Carbon",
    "Darcula",
    "GitHub",
    "Gruvbox Dark Hard",
    "Gruvbox Dark Medium",
    "Gruvbox Light",
    "PaperColor Light",
    "Selenized Dark",
    "Selenized Light",
    "Tokyo Night",
    "Shades of Purple",
    "Atom Dark",
    "Base16 Eighties",
    "Base16 Default Dark",
    "Base16 Default Light",
    "Base16 Ocean",
    "Base16 Material",
    "Base16 Solarized Dark",
    "Base16 Solarized Light",
    "Bespin",
    "Blackboard",
    "Clearnight",
    "Clouds",
    "Clouds Midnight",
    "Cobalt",
    "Crimson Editor",
    "Dawn",
    "Dreamweaver",
    "Eiffel",
    "Espresso",
    "Fade to Grey",
    "IDLE",
    "Katzenmilch",
    "KR Theme",
    "Kuroir",
    "LAZY",
    "MagicWB",
    "Merbivore",
    "Merbivore Soft",
    "Misterioso",
    "Night Owl",
    "Oceanic",
    "Pastels on Dark",
    "Solarized",
    "Solarized Light",
    "Solarized Dark",
    "Sqlserver",
    "Terminal",
    "Tomorrow Night",
    "Twilight",
    "Vibrant Ink",
    "XCode",
    "Zenburn",
    "Zebra",
    "Zenburnesque",
];

pub const IT_DOMAINS: [&str; 143] = [
    "Embedded Systems",
    "Robotics",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Cloud Computing",
    "DevOps",
    "Networking",
    "Software Development",
    "Web Development",
    "Mobile Development",
    "Game Development",
    "Database Management",
    "Big Data",
    "Internet of Things",
    "Blockchain",
    "Virtual Reality",
    "Augmented Reality",
    "Quantum Computing",
    "Computer Vision",
    "Natural Language Processing",
    "Computer Graphics",
    "Operating Systems",
    "Distributed Systems",
    "Microservices",
    "APIs",
    "Software Testing",
    "Continuous Integration",
    "Continuous Deployment",
    "Automation",
    "Serverless Computing",
    "Edge Computing",
    "Data Engineering",
    "Data Analytics",
    "Human-Computer Interaction",
    "UX/UI Design",
    "Embedded AI",
    "Cloud Security",
    "Cryptography",
    "Network Security",
    "Penetration Testing",
    "Information Security",
    "Systems Architecture",
    "Cloud Architecture",
    "High Performance Computing",
    "Parallel Computing",
    "Mobile Security",
    "Database Security",
    "Firmware Development",
    "Digital Signal Processing",
    "Computer Architecture",
    "Compiler Design",
    "Software Engineering",
    "Project Management",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "IT Service Management",
    "Technical Support",
    "Help Desk",
    "Cloud Storage",
    "Content Delivery Networks",
    "Web Services",
    "E-commerce",
    "Social Media Technologies",
    "Cloud Platforms",
    "Operating System Development",
    "Embedded Linux",
    "Network Administration",
    "Cloud Networking",
    "Software Licensing",
    "Digital Forensics",
    "Data Privacy",
    "IT Compliance",
    "Risk Management",
    "Technical Writing",
    "Open Source Software",
    "Cloud Automation",
    "Robotic Process Automation",
    "Business Intelligence",
    "IT Consulting",
    "Software Architecture",
    "Telecommunications",
    "Voice over IP",
    "Video Streaming",
    "Virtual Machines",
    "Containers",
    "Kubernetes",
    "Docker",
    "Cloud Orchestration",
    "API Management",
    "Augmented Analytics",
    "Data Visualization",
    "Edge AI",
    "Smart Cities",
    "Digital Twins",
    "Wearable Technology",
    "Cyber-Physical Systems",
    "Embedded Security",
    "Industrial IoT",
    "Smart Manufacturing",
    "AI Ethics",
    "AI Governance",
    "Bioinformatics",
    "Geospatial Technology",
    "IT Infrastructure",
    "Cloud Migration",
    "Cloud Native Applications",
    "Software Localization",
    "Localization Engineering",
    "Natural User Interfaces",
    "Gesture Recognition",
    "Voice Recognition",
    "Autonomous Vehicles",
    "AI-powered Automation",
    "Chatbots",
    "Virtual Assistants",
    "Digital Marketing Technology",
    "Content Management Systems",
    "Server Management",
    "Database Administration",
    "Data Warehousing",
    "ETL Processes",
    "Data Lakes",
    "Mobile Payments",
    "Fintech Technologies",
    "Cryptocurrency",
    "Smart Contracts",
    "Identity and Access Management",
    "Endpoint Security",
    "Network Monitoring",
    "IT Auditing",
    "System Integration",
    "Legacy Systems",
    "Cloud Billing",
    "Cloud Cost Management",
    "Tech Support Automation",
    "Low-code Development",
    "No-code Platforms",
    "Code Review",
    "Software Maintenance",
    "Performance Testing",
];
