pub const CONSTELLATIONS: [&str; 88] = [
    "Andromeda",
    "Antlia",
    "Apus",
    "Aquarius",
    "Aquila",
    "Ara",
    "Aries",
    "Auriga",
    "Boötes",
    "Caelum",
    "Camelopardalis",
    "Cancer",
    "Canes Venatici",
    "Canis Major",
    "Canis Minor",
    "Capricornus",
    "Carina",
    "Cassiopeia",
    "Centaurus",
    "Cepheus",
    "Cetus",
    "Chamaeleon",
    "Circinus",
    "Columba",
    "Coma Berenices",
    "Corona Australis",
    "Corona Borealis",
    "Corvus",
    "Crater",
    "Crux",
    "Cygnus",
    "Delphinus",
    "Dorado",
    "Draco",
    "Equuleus",
    "Eridanus",
    "Fornax",
    "Gemini",
    "Grus",
    "Hercules",
    "Horologium",
    "Hydra",
    "Hydrus",
    "Indus",
    "Lacerta",
    "Leo",
    "Leo Minor",
    "Lepus",
    "Libra",
    "Lupus",
    "Lynx",
    "Lyra",
    "Mensa",
    "Microscopium",
    "Monoceros",
    "Musca",
    "Norma",
    "Octans",
    "Ophiuchus",
    "Orion",
    "Pavo",
    "Pegasus",
    "Perseus",
    "Phoenix",
    "Pictor",
    "Pisces",
    "Piscis Austrinus",
    "Puppis",
    "Pyxis",
    "Reticulum",
    "Sagitta",
    "Sagittarius",
    "Scorpius",
    "Sculptor",
    "Scutum",
    "Serpens",
    "Sextans",
    "Taurus",
    "Telescopium",
    "Triangulum",
    "Triangulum Australe",
    "Tucana",
    "Ursa Major",
    "Ursa Minor",
    "Vela",
    "Virgo",
    "Volans",
    "Vulpecula",
];

pub const PLANETS: [&str; 8] = [
    "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune",
];

pub const STARS: [&str; 99] = [
    "Sirius",
    "Canopus",
    "Arcturus",
    "Alpha Centauri",
    "Vega",
    "Capella",
    "Rigel",
    "Procyon",
    "Achernar",
    "Betelgeuse",
    "Hadar",
    "Altair",
    "Aldebaran",
    "Spica",
    "Antares",
    "Pollux",
    "Fomalhaut",
    "Deneb",
    "Mimosa",
    "Regulus",
    "Adhara",
    "Shaula",
    "Castor",
    "Gacrux",
    "Bellatrix",
    "Elnath",
    "Miaplacidus",
    "Alnilam",
    "Alnair",
    "Alioth",
    "Dubhe",
    "Mirfak",
    "Wezen",
    "Sargas",
    "Kaus Australis",
    "Avior",
    "Alkaid",
    "Menkent",
    "Alphard",
    "Algieba",
    "Alhena",
    "Mizar",
    "Acrux",
    "Dubhe",
    "Merak",
    "Alsephina",
    "Alphard",
    "Alnitak",
    "Algol",
    "Alpheratz",
    "Rigil Kentaurus",
    "Markab",
    "Hamal",
    "Schedar",
    "Diphda",
    "Nunki",
    "Pherkad",
    "Zubenelgenubi",
    "Menkib",
    "Eltanin",
    "Zubeneschamali",
    "Kochab",
    "Polaris",
    "Denebola",
    "Atria",
    "Alnair",
    "Algorab",
    "Alrescha",
    "Caph",
    "Cursa",
    "Eltanin",
    "Enif",
    "Lesath",
    "Maasym",
    "Mimosa",
    "Nashira",
    "Peacock",
    "Rasalhague",
    "Rasalgethi",
    "Rukbat",
    "Sabik",
    "Sargas",
    "Shaula",
    "Suhail",
    "Tarazed",
    "Tejat",
    "Thuban",
    "Unukalhai",
    "Vindemiatrix",
    "Zaurak",
    "Zosma",
    "Zubenelakrab",
    "Zubenelgenubi",
    "Alkaid",
    "Acrux",
    "Alioth",
    "Alnilam",
    "Alphard",
    "Altair",
];

pub const GALAXIES: [&str; 50] = [
    "Milky Way",
    "Andromeda",
    "Triangulum",
    "Whirlpool",
    "Sombrero",
    "Pinwheel",
    "Centaurus A",
    "Large Magellanic Cloud",
    "Small Magellanic Cloud",
    "Cartwheel",
    "Sunflower",
    "Tadpole",
    "Black Eye",
    "Cigar",
    "Fireworks",
    "Telescope",
    "Silver Dollar",
    "Canis Major Dwarf",
    "Circinus",
    "Fornax",
    "Hydra",
    "Pisces Dwarf",
    "Sculptor Dwarf",
    "Triangulum II",
    "Ursa Major Dwarf",
    "Ursa Minor Dwarf",
    "Virgo Cluster",
    "Centaurus Cluster",
    "Coma Cluster",
    "Perseus Cluster",
    "Leo Cluster",
    "Fornax Cluster",
    "Hercules Cluster",
    "Virgo Supercluster",
    "Laniakea Supercluster",
    "Shapley Supercluster",
    "Fingers of God",
    "Great Attractor",
    "Bullet Cluster",
    "El Gordo",
    "MACS J0717.5+3745",
    "CL J1001+0220",
    "Phoenix Cluster",
    "Cartwheel Ring",
    "Hoag's Object",
    "NGC 604",
    "Antennae Galaxies",
    "Stephan's Quintet",
    "Leo Triplet",
    "Sculptor Group",
];
