pub const UK_COUNTY_CODES: &[&str] = &[
    "AB", "AL", "AV", "BD", "BH", "BL", "BN", "BR", "BS", "CB", "CF", "CH", "CM", "CO", "CR", "CT",
    "CV", "CW", "DA", "DD", "DE", "DG", "DH", "DL", "DN", "DT", "DY", "EC", "EH", "EN", "EX", "FK",
    "FY", "GL", "GU", "HA", "HD", "HG", "HP", "HR", "HS", "HU", "HX", "IG", "IP", "IV", "KA", "KT",
];

pub const UK_COUNTIES: &[&str] = &[
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "City of London",
    "Cornwall",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "East Riding of Yorkshire",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
];

pub const UK_ROAD_TYPES: &[&str] = &[
    "Avenue",
    "Boulevard",
    "Close",
    "Court",
    "Crescent",
    "Drive",
    "Gardens",
    "Grove",
    "Hill",
    "Lane",
    "Meadow",
    "Park",
    "Place",
    "Road",
    "Row",
    "Street",
    "Terrace",
    "Vale",
    "Walk",
    "Way",
];

pub const LONGEST_UK_RIVERS: &[&str] = &[
    "Afon Conwy",
    "Aire",
    "Aln",
    "Avon",
    "Ayr",
    "Bann",
    "Calder",
    "Clyde",
    "Dart",
    "Dee",
    "Derwent",
    "Don",
    "Esk",
    "Exe",
    "Forth",
    "Frome",
    "Gala Water",
    "Great Ouse",
    "Irwell",
    "Lagan",
    "Lune",
    "Medway",
    "Mersey",
    "Nene",
    "Ouse",
    "Rheidol",
    "Ribble",
    "Severn",
    "Spey",
    "Stour",
    "Taff",
    "Tamar",
    "Tavy",
    "Tees",
    "Thames",
    "Trent",
    "Tweed",
    "Tyne",
    "Ure",
    "Usk",
    "Wear",
    "Wensum",
    "Wye",
    "Yare",
];

pub const UK_STREETS: &[&str] = &[
    "Abbey Road",
    "Albany Street",
    "Argyll Street",
    "Baker Street",
    "Belgravia Road",
    "Blackfriars Road",
    "Bond Street",
    "Brick Lane",
    "Broadway",
    "Brompton Road",
    "Camden High Street",
    "Camden Road",
    "Carnaby Street",
    "Cavendish Square",
    "Charing Cross Road",
    "Cheapside",
    "Chiswell Street",
    "Chiswick High Road",
    "Clapham High Street",
    "Clerkenwell Road",
    "Cornhill",
    "Curzon Street",
    "Downing Street",
    "Drury Lane",
    "Edgware Road",
    "Edinburgh Road",
    "Euston Road",
    "Farringdon Road",
    "Fleet Street",
    "Gower Street",
    "Gray's Inn Road",
    "Greenwich High Road",
    "Hammersmith Road",
    "Hampstead High Street",
    "Hatton Garden",
    "High Holborn",
    "Highgate Road",
    "Islington High Street",
    "Islington Road",
    "Jermyn Street",
    "Jubilee Street",
    "Kensington High Street",
    "Kensington Road",
    "King's Cross Road",
    "Kings Road",
    "Knightsbridge",
    "Ladbroke Grove",
    "Lambeth Road",
    "Leadenhall Street",
    "Leicester Square",
    "Lisson Grove",
    "Ludgate Hill",
    "Maida Vale",
    "Marylebone High Street",
    "Marylebone Lane",
    "Marylebone Road",
    "Notting Hill Gate",
    "Old Compton Street",
    "Old Street",
    "Oxford Circus",
    "Oxford Street",
    "Pall Mall",
    "Park Lane",
    "Piccadilly",
    "Piccadilly Circus",
    "Portman Street",
    "Portobello Road",
    "Queensway",
    "Regent Street",
    "Regent's Park Road",
    "Richmond Road",
    "Russell Square",
    "Seven Sisters Road",
    "Shepherd's Bush Road",
    "Shoreditch High Street",
    "Soho Square",
    "Soho Street",
    "Southwark Street",
    "St Martin's Lane",
    "St Pancras",
    "Strand",
    "The Mall",
    "The Strand",
    "Tottenham Court Road",
    "Tottenham High Road",
    "Tower Hill",
    "Upper Street",
    "Vauxhall Bridge Road",
    "Victoria Street",
    "Wandsworth High Street",
    "West End Lane",
    "Westminster Bridge Road",
    "Whitechapel High Street",
    "Whitechapel Road",
    "Whitehall",
    "Wilton Road",
    "Windmill Street",
    "York Road",
    "Zetland Street",
];
