pub const UK_COUNTY_CODES: [&str; 48] = [
    "AB", "AL", "AV", "BD", "BH", "BL", "BN", "BR", "BS", "CB", "CF", "CH", "CM", "CO", "CR", "CT",
    "CV", "CW", "DA", "DD", "DE", "DG", "DH", "DL", "DN", "DT", "DY", "EC", "EH", "EN", "EX", "FK",
    "FY", "GL", "GU", "HA", "HD", "HG", "HP", "HR", "HS", "HU", "HX", "IG", "IP", "IV", "KA", "KT",
];
pub const UK_COUNTIES: [&str; 48] = [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "City of London",
    "Cornwall",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "East Riding of Yorkshire",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
];
pub const UK_ROAD_TYPES: [&str; 20] = [
    "Avenue",
    "Boulevard",
    "Close",
    "Court",
    "Drive",
    "Lane",
    "Place",
    "Road",
    "Street",
    "Terrace",
    "Walk",
    "Way",
    "Gardens",
    "Crescent",
    "Hill",
    "Grove",
    "Meadow",
    "Park",
    "Row",
    "Vale",
];

pub const LONGEST_UK_RIVERS: [&str; 50] = [
    "Severn",
    "Thames",
    "Trent",
    "Wye",
    "Great Ouse",
    "Exe",
    "Tweed",
    "Ure",
    "Tamar",
    "Nene",
    "Don",
    "Clyde",
    "Spey",
    "Avon",
    "Derwent",
    "Wear",
    "Ouse",
    "Calder",
    "Tyne",
    "Stour",
    "Tees",
    "Ribble",
    "Aire",
    "Mersey",
    "Esk",
    "Ayr",
    "Forth",
    "Dart",
    "Tavy",
    "Lune",
    "Frome",
    "Wensum",
    "Clyde",
    "Tweed",
    "Afon Conwy",
    "Taff",
    "Mersey",
    "Medway",
    "Lagan",
    "Rheidol",
    "Irwell",
    "Gala Water",
    "Bann",
    "Tweed",
    "Yare",
    "Usk",
    "Aln",
    "Dee",
    "Tweed",
    "Don",
];

pub const UK_STREETS: [&str; 105] = [
    "Oxford Street",
    "Regent Street",
    "Bond Street",
    "Piccadilly",
    "Baker Street",
    "Fleet Street",
    "Kings Road",
    "Carnaby Street",
    "Charing Cross Road",
    "Abbey Road",
    "Whitehall",
    "Downing Street",
    "The Mall",
    "Park Lane",
    "Strand",
    "Tottenham Court Road",
    "Camden High Street",
    "Brick Lane",
    "Westminster Bridge Road",
    "Knightsbridge",
    "Portobello Road",
    "Edgware Road",
    "Upper Street",
    "Broadway",
    "Old Compton Street",
    "Farringdon Road",
    "High Holborn",
    "Southwark Street",
    "Marylebone Road",
    "Clapham High Street",
    "King's Cross Road",
    "Camden Road",
    "Tower Hill",
    "Oxford Circus",
    "Brompton Road",
    "Chiswick High Road",
    "Cheapside",
    "Gray's Inn Road",
    "Marylebone Lane",
    "Queensway",
    "Soho Square",
    "Vauxhall Bridge Road",
    "Whitechapel Road",
    "West End Lane",
    "Blackfriars Road",
    "Camden High Street",
    "Chiswell Street",
    "Edinburgh Road",
    "Greenwich High Road",
    "Hampstead High Street",
    "Islington High Street",
    "Jermyn Street",
    "Kensington High Street",
    "Ladbroke Grove",
    "Lambeth Road",
    "Leicester Square",
    "Lisson Grove",
    "Maida Vale",
    "Marylebone High Street",
    "Notting Hill Gate",
    "Old Street",
    "Oxford Circus",
    "Pall Mall",
    "Piccadilly Circus",
    "Portman Street",
    "Queensway",
    "Regent's Park Road",
    "Richmond Road",
    "Russell Square",
    "Seven Sisters Road",
    "Shepherd's Bush Road",
    "Shoreditch High Street",
    "Soho Street",
    "St Martin's Lane",
    "St Pancras",
    "The Strand",
    "Tottenham High Road",
    "Victoria Street",
    "Wandsworth High Street",
    "Whitechapel High Street",
    "Wilton Road",
    "Windmill Street",
    "York Road",
    "Zetland Street",
    "Albany Street",
    "Argyll Street",
    "Baker Street",
    "Belgravia Road",
    "Camden High Street",
    "Cavendish Square",
    "Clerkenwell Road",
    "Cornhill",
    "Curzon Street",
    "Drury Lane",
    "Euston Road",
    "Fleet Street",
    "Gower Street",
    "Hammersmith Road",
    "Hatton Garden",
    "Highgate Road",
    "Islington Road",
    "Jubilee Street",
    "Kensington Road",
    "Leadenhall Street",
    "Ludgate Hill",
];
