pub const SCHOOL_SUBJECTS: &[&str] = &[
    "Accounting",
    "Agricultural Science",
    "Algebra",
    "Ancient History",
    "Animal Science",
    "App Development",
    "Arabic",
    "Architecture",
    "Art",
    "Astronautics",
    "Astronomy",
    "Automotive Technology",
    "Band",
    "Bengali",
    "Biology",
    "Business Studies",
    "Calculus",
    "Cantonese",
    "Carpentry",
    "Chemistry",
    "Choir",
    "Civics",
    "Civil Engineering",
    "Computer Science",
    "Cosmetology",
    "Creative Writing",
    "Critical Thinking",
    "Czech",
    "Dance",
    "Danish",
    "Debate",
    "Design",
    "Drama",
    "Drawing",
    "Dutch",
    "Earth Science",
    "Economics",
    "Electrical Engineering",
    "Engineering",
    "English",
    "English Language",
    "English Literature",
    "Entrepreneurship",
    "Environmental Science",
    "Ethics",
    "European History",
    "Fashion Design",
    "Film Studies",
    "Finance",
    "Finnish",
    "Food Technology",
    "Forestry",
    "French",
    "Game Design",
    "Geography",
    "Geometry",
    "German",
    "Graphic Design",
    "Greek",
    "Health Education",
    "Hebrew",
    "Hindi",
    "History",
    "Home Economics",
    "Horticulture",
    "Hungarian",
    "Indonesian",
    "Information Technology",
    "Instrumental Music",
    "Interior Design",
    "Italian",
    "Japanese",
    "Journalism",
    "Korean",
    "Latin",
    "Law",
    "Library Science",
    "Linguistics",
    "Literature",
    "Logic",
    "Macroeconomics",
    "Malay",
    "Management",
    "Mandarin Chinese",
    "Marine Biology",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Metalwork",
    "Meteorology",
    "Microeconomics",
    "Music",
    "Music Theory",
    "Norwegian",
    "Nutrition",
    "Oceanography",
    "Orchestra",
    "Painting",
    "Performing Arts",
    "Philosophy",
    "Photography",
    "Physical Education",
    "Physics",
    "Polish",
    "Political Science",
    "Portuguese",
    "Probability",
    "Programming",
    "Psychology",
    "Public Speaking",
    "Punjabi",
    "Religious Studies",
    "Robotics",
    "Russian",
    "Sculpture",
    "Sign Language",
    "Slovak",
    "Sociology",
    "Spanish",
    "Statistics",
    "Study Skills",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tamil",
    "Telugu",
    "Textiles",
    "Thai",
    "Theatre",
    "Theology",
    "Trigonometry",
    "Turkish",
    "Ukrainian",
    "Urban Studies",
    "Urdu",
    "Vietnamese",
    "Visual Arts",
    "Voice",
    "Woodwork",
    "World History",
    "Xhosa",
    "Zulu",
];

pub const ACADEMIC_DISCIPLINES: &[&str] = &[
    "Accounting",
    "Actuarial Science",
    "Aerospace Engineering",
    "Aesthetics",
    "Agricultural Science",
    "Analytical Chemistry",
    "Ancient History",
    "Animal Science",
    "Anthropology",
    "Applied Mathematics",
    "Archaeology",
    "Architecture",
    "Art History",
    "Artificial Intelligence",
    "Astronomy",
    "Astrophysics",
    "Biochemistry",
    "Biology",
    "Biomedical Engineering",
    "Botany",
    "Business",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classics",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Communication Studies",
    "Comparative Literature",
    "Comparative Politics",
    "Comparative Religion",
    "Computer Engineering",
    "Computer Science",
    "Creative Writing",
    "Criminology",
    "Cultural Studies",
    "Curriculum Studies",
    "Cybersecurity",
    "Dance Studies",
    "Data Science",
    "Dentistry",
    "Design",
    "Developmental Psychology",
    "Ecology",
    "Econometrics",
    "Economics",
    "Education",
    "Educational Psychology",
    "Electrical Engineering",
    "Engineering",
    "English Literature",
    "Environmental Science",
    "Epistemology",
    "Ethics",
    "Ethnomusicology",
    "Experimental Physics",
    "Fashion Design",
    "Film Studies",
    "Finance",
    "Fine Arts",
    "Food Science",
    "Genetics",
    "Geography",
    "Geology",
    "Graphic Design",
    "History",
    "Horticulture",
    "Human Resources",
    "Industrial Engineering",
    "Information Systems",
    "Inorganic Chemistry",
    "Instructional Design",
    "International Relations",
    "Journalism",
    "Jurisprudence",
    "Law",
    "Legal Studies",
    "Library Science",
    "Linguistics",
    "Literature",
    "Logic",
    "Machine Learning",
    "Macroeconomics",
    "Management",
    "Marine Biology",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Medicine",
    "Medieval History",
    "Metaphysics",
    "Meteorology",
    "Microbiology",
    "Microeconomics",
    "Military Science",
    "Modern History",
    "Musicology",
    "Nuclear Physics",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Oceanography",
    "Operations Research",
    "Organic Chemistry",
    "Paleontology",
    "Performing Arts",
    "Pharmacy",
    "Philosophy",
    "Phonetics",
    "Phonology",
    "Physical Therapy",
    "Physics",
    "Planetary Science",
    "Political Philosophy",
    "Political Science",
    "Pragmatics",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Pure Mathematics",
    "Religious Studies",
    "Robotics",
    "Semantics",
    "Social Psychology",
    "Social Work",
    "Sociolinguistics",
    "Sociology",
    "Software Engineering",
    "Special Education",
    "Speech Pathology",
    "Sports Science",
    "Statistics",
    "Syntax",
    "Theatre Studies",
    "Theology",
    "Theoretical Physics",
    "Urban Studies",
    "Veterinary Science",
    "Visual Arts",
    "World Literature",
    "Zoology",
];

pub const DEGREES_TITLES: &[&str] = &[
    "A-Level",
    "Academic Advisor",
    "Academic Transcript",
    "Adjunct Professor",
    "Advanced Diploma",
    "Apprenticeship Certificate",
    "Assistant Professor",
    "Associate Professor",
    "Associate of Applied Science",
    "Associate of Arts",
    "Associate of Science",
    "Bachelor of Architecture",
    "Bachelor of Arts",
    "Bachelor of Business Administration",
    "Bachelor of Communications",
    "Bachelor of Computer Science",
    "Bachelor of Design",
    "Bachelor of Economics",
    "Bachelor of Education",
    "Bachelor of Engineering",
    "Bachelor of Fine Arts",
    "Bachelor of Information Technology",
    "Bachelor of Laws",
    "Bachelor of Mathematics",
    "Bachelor of Music",
    "Bachelor of Nursing",
    "Bachelor of Pharmacy",
    "Bachelor of Philosophy",
    "Bachelor of Political Science",
    "Bachelor of Public Health",
    "Bachelor of Science",
    "Bachelor of Social Work",
    "CELTA",
    "CPD Certificate",
    "Certificate IV",
    "Certified Financial Planner",
    "Certified Public Accountant",
    "Chancellor",
    "Chartered Accountant",
    "Chartered Engineer",
    "Continuing Education Unit",
    "Craft Certificate",
    "Credential",
    "Dean",
    "Diploma Supplement",
    "Diploma in Business",
    "Diploma in Education",
    "Diploma in Engineering",
    "Diploma in IT",
    "Diploma in Law",
    "Diploma in Marketing",
    "Distinction",
    "Doctor honoris causa",
    "Doctor of Business Administration",
    "Doctor of Dental Medicine",
    "Doctor of Dental Surgery",
    "Doctor of Divinity",
    "Doctor of Education",
    "Doctor of Engineering",
    "Doctor of Humane Letters",
    "Doctor of Laws",
    "Doctor of Medicine",
    "Doctor of Nursing Practice",
    "Doctor of Pharmacy",
    "Doctor of Philosophy",
    "Doctor of Psychology",
    "Doctor of Public Health",
    "Doctor of Science",
    "Doctor of Theology",
    "Doctor of Veterinary Medicine",
    "Double Major",
    "Dual Degree",
    "Emeritus Professor",
    "Executive MBA",
    "Fellow of the Royal Society",
    "First Class Honours",
    "Foundation Degree",
    "General Certificate of Secondary Education",
    "Graduate Assistant",
    "Graduate Certificate",
    "Graduate Diploma",
    "Habilitation",
    "High School Diploma",
    "Higher National Certificate",
    "Higher National Diploma",
    "Honours Degree",
    "Instructor",
    "Journeyman Certificate",
    "Lecturer",
    "Letter of Recommendation",
    "Licensed Practical Nurse",
    "Licentiate",
    "MOOC Completion",
    "Master of Accounting",
    "Master of Architecture",
    "Master of Arts",
    "Master of Business Administration",
    "Master of Computer Science",
    "Master of Education",
    "Master of Engineering",
    "Master of Finance",
    "Master of Fine Arts",
    "Master of Information Systems",
    "Master of International Relations",
    "Master of Laws",
    "Master of Mathematics",
    "Master of Nursing",
    "Master of Philosophy",
    "Master of Psychology",
    "Master of Public Administration",
    "Master of Public Health",
    "Master of Public Policy",
    "Master of Science",
    "Master of Social Work",
    "Member of the Academy of Sciences",
    "Merit",
    "Micro Masters",
    "Nano Degree",
    "Online Certificate",
    "Online MBA",
    "Paralegal Certificate",
    "Pass",
    "Postdoctoral Fellow",
    "Postgraduate",
    "Professional Certificate",
    "Professional Development Unit",
    "Professional Diploma",
    "Professional Engineer",
    "Professor",
    "Provost",
    "Reader",
    "Rector",
    "Registered Nurse",
    "Research Fellow",
    "Second Class Honours",
    "Senior Lecturer",
    "Specialisation Certificate",
    "Summer School Certificate",
    "TESOL Certificate",
    "Teaching Certificate",
    "Teaching Fellow",
    "Technical Diploma",
    "Trade Qualification",
    "Undergraduate",
    "Visiting Scholar",
    "Vocational Certificate",
];

pub const FAMOUS_UNIVERSITIES: &[&str] = &[
    "Aarhus University",
    "Australian National University (ANU)",
    "Autonomous University of Barcelona",
    "Autonomous University of Madrid",
    "Boston University",
    "Brown University",
    "CEU San Pablo University",
    "California Institute of Technology (Caltech)",
    "Camilo José Cela University",
    "Carlos III University of Madrid",
    "Carnegie Mellon University",
    "Chalmers University of Technology",
    "Columbia University",
    "Comillas Pontifical University",
    "Cornell University",
    "Durham University",
    "EADA Business School Barcelona",
    "ESADE Business School",
    "ETH Zurich – Swiss Federal Institute of Technology",
    "European University of Madrid",
    "Fudan University",
    "Georgia Institute of Technology",
    "Harvard University",
    "Humboldt University of Berlin",
    "IE University",
    "Imperial College London",
    "Institut Polytechnique de Paris",
    "Johns Hopkins University",
    "KTH Royal Institute of Technology",
    "KU Leuven",
    "King's College London",
    "Korea Advanced Institute of Science & Technology (KAIST)",
    "Kyoto University",
    "Kyushu University",
    "Lomonosov Moscow State University",
    "London School of Economics and Political Science (LSE)",
    "Lund University",
    "Massachusetts Institute of Technology (MIT)",
    "McGill University",
    "Miguel Hernández University of Elche",
    "Monash University",
    "Nagoya University",
    "Nanyang Technological University (NTU)",
    "National University of Singapore (NUS)",
    "Nebrija University",
    "New York University (NYU)",
    "Osaka University",
    "Pablo de Olavide University",
    "Peking University",
    "Pennsylvania State University",
    "Polytechnic University of Catalonia",
    "Polytechnic University of Madrid",
    "Polytechnic University of Valencia",
    "Polytechnique Montréal",
    "Pontifical University of Salamanca",
    "Princeton University",
    "Purdue University",
    "RWTH Aachen University",
    "Rey Juan Carlos University",
    "Seoul National University",
    "Shanghai Jiao Tong University",
    "Stanford University",
    "Technical University of Munich (TUM)",
    "The University of Hong Kong",
    "The University of Melbourne",
    "The University of New South Wales (UNSW Sydney)",
    "Tokyo Institute of Technology",
    "Trinity College Dublin",
    "Tsinghua University",
    "Télécom Paris",
    "University College London (UCL)",
    "University of A Coruña",
    "University of Aberdeen",
    "University of Adelaide",
    "University of Agder",
    "University of Alberta",
    "University of Alcalá",
    "University of Almería",
    "University of Amsterdam",
    "University of Antwerp",
    "University of Arizona",
    "University of Auckland",
    "University of Barcelona",
    "University of Basel",
    "University of Bergen",
    "University of Bern",
    "University of Birmingham",
    "University of Bremen",
    "University of Bristol",
    "University of British Columbia",
    "University of Burgos",
    "University of California, Berkeley (UCB)",
    "University of California, Los Angeles (UCLA)",
    "University of California, San Diego (UCSD)",
    "University of Cambridge",
    "University of Canterbury",
    "University of Cape Town",
    "University of Castilla–La Mancha",
    "University of Chicago",
    "University of Cologne",
    "University of Copenhagen",
    "University of Cádiz",
    "University of Delaware",
    "University of Deusto",
    "University of Eastern Finland",
    "University of Edinburgh",
    "University of Exeter",
    "University of Extremadura",
    "University of Florence",
    "University of Geneva",
    "University of Girona",
    "University of Glasgow",
    "University of Gothenburg",
    "University of Granada",
    "University of Groningen",
    "University of Helsinki",
    "University of Hohenheim",
    "University of Huelva",
    "University of Illinois at Urbana–Champaign",
    "University of Innsbruck",
    "University of Jaén",
    "University of La Laguna",
    "University of Las Palmas de Gran Canaria",
    "University of Lausanne",
    "University of Leeds",
    "University of León",
    "University of Liège",
    "University of Lleida",
    "University of Manchester",
    "University of Manitoba",
    "University of Marburg",
    "University of Maryland, College Park",
    "University of Michigan–Ann Arbor",
    "University of Milano-Bicocca",
    "University of Murcia",
    "University of Málaga",
    "University of Münster",
    "University of Nantes",
    "University of Navarra",
    "University of New Mexico",
    "University of Nottingham",
    "University of Oslo",
    "University of Ottawa",
    "University of Oulu",
    "University of Oviedo",
    "University of Oxford",
    "University of Pennsylvania",
    "University of Pisa",
    "University of Porto",
    "University of Pretoria",
    "University of Queensland",
    "University of Reading",
    "University of Rovira i Virgili",
    "University of Salford",
    "University of Santiago de Compostela",
    "University of Seville",
    "University of Sheffield",
    "University of South Carolina",
    "University of Southampton",
    "University of Southern Denmark",
    "University of St Andrews",
    "University of Stavanger",
    "University of Strasbourg",
    "University of Sydney",
    "University of São Paulo",
    "University of Tampere",
    "University of Technology Sydney (UTS)",
    "University of Tokyo",
    "University of Toronto",
    "University of Trento",
    "University of Turin",
    "University of Twente",
    "University of Valencia",
    "University of Valladolid",
    "University of Vic – Central University of Catalonia",
    "University of Vienna",
    "University of Vigo",
    "University of Warwick",
    "University of Washington",
    "University of Western Australia (UWA)",
    "University of Wisconsin–Madison",
    "University of Zaragoza",
    "University of Zurich",
    "University of the Balearic Islands",
    "University of the Basque Country",
    "Università di Bologna",
    "Universität Freiburg",
    "Université Catholique de Louvain (UCLouvain)",
    "Université Laval",
    "Université Paris Science & Lettre (PSL)",
    "Université Paris-Cité",
    "Université Paris-Saclay",
    "Université de Montréal",
    "Utrecht University",
    "Vrije Universiteit Amsterdam",
    "Vrije Universiteit Brussel (VUB)",
    "Wageningen University & Research",
    "Yale University",
    "Yonsei University",
    "École Polytechnique Fédérale de Lausanne (EPFL)",
];

