pub const SCHOOL_SUBJECTS: [&str; 144] = [
    "Mathematics",
    "Algebra",
    "Geometry",
    "Trigonometry",
    "Calculus",
    "Statistics",
    "Probability",
    "Physics",
    "Chemistry",
    "Biology",
    "Earth Science",
    "Environmental Science",
    "Astronomy",
    "Computer Science",
    "Programming",
    "Information Technology",
    "Robotics",
    "Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Economics",
    "Microeconomics",
    "Macroeconomics",
    "Accounting",
    "Business Studies",
    "Finance",
    "Entrepreneurship",
    "Marketing",
    "Management",
    "Ethics",
    "Political Science",
    "Civics",
    "Law",
    "History",
    "World History",
    "European History",
    "American History",
    "Ancient History",
    "Geography",
    "Sociology",
    "Psychology",
    "Philosophy",
    "Religious Studies",
    "Theology",
    "Literature",
    "English",
    "English Language",
    "English Literature",
    "Creative Writing",
    "Linguistics",
    "French",
    "Spanish",
    "German",
    "Italian",
    "Portuguese",
    "Latin",
    "Greek",
    "Mandarin Chinese",
    "Cantonese",
    "Japanese",
    "Korean",
    "Arabic",
    "Russian",
    "Hindi",
    "Swahili",
    "Hebrew",
    "Turkish",
    "Punjabi",
    "Bengali",
    "Urdu",
    "Tamil",
    "Telugu",
    "Polish",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Ukrainian",
    "Czech",
    "Slovak",
    "Hungarian",
    "Indonesian",
    "Malay",
    "Thai",
    "Vietnamese",
    "Tagalog",
    "Zulu",
    "Xhosa",
    "Sign Language",
    "Art",
    "Painting",
    "Drawing",
    "Sculpture",
    "Photography",
    "Design",
    "Graphic Design",
    "Visual Arts",
    "Performing Arts",
    "Theatre",
    "Drama",
    "Dance",
    "Music",
    "Choir",
    "Orchestra",
    "Band",
    "Music Theory",
    "Voice",
    "Instrumental Music",
    "Physical Education",
    "Health Education",
    "Nutrition",
    "Home Economics",
    "Food Technology",
    "Textiles",
    "Woodwork",
    "Metalwork",
    "Carpentry",
    "Automotive Technology",
    "Agricultural Science",
    "Horticulture",
    "Animal Science",
    "Marine Biology",
    "Forestry",
    "Meteorology",
    "Oceanography",
    "Astronautics",
    "Game Design",
    "App Development",
    "Media Studies",
    "Film Studies",
    "Journalism",
    "Debate",
    "Public Speaking",
    "Logic",
    "Critical Thinking",
    "Study Skills",
    "Library Science",
    "Fashion Design",
    "Cosmetology",
    "Interior Design",
    "Architecture",
    "Urban Studies",
];

pub const ACADEMIC_DISCIPLINES: [&str; 142] = [
    "Mathematics",
    "Applied Mathematics",
    "Pure Mathematics",
    "Statistics",
    "Actuarial Science",
    "Physics",
    "Theoretical Physics",
    "Experimental Physics",
    "Astrophysics",
    "Nuclear Physics",
    "Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Analytical Chemistry",
    "Biochemistry",
    "Biology",
    "Zoology",
    "Botany",
    "Genetics",
    "Microbiology",
    "Marine Biology",
    "Ecology",
    "Environmental Science",
    "Geology",
    "Paleontology",
    "Geography",
    "Meteorology",
    "Oceanography",
    "Astronomy",
    "Planetary Science",
    "Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Chemical Engineering",
    "Computer Engineering",
    "Software Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Industrial Engineering",
    "Computer Science",
    "Information Systems",
    "Artificial Intelligence",
    "Machine Learning",
    "Robotics",
    "Data Science",
    "Cybersecurity",
    "Philosophy",
    "Epistemology",
    "Metaphysics",
    "Logic",
    "Ethics",
    "Aesthetics",
    "Political Philosophy",
    "Linguistics",
    "Syntax",
    "Semantics",
    "Pragmatics",
    "Phonetics",
    "Phonology",
    "Sociolinguistics",
    "Anthropology",
    "Sociology",
    "Psychology",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Developmental Psychology",
    "Social Psychology",
    "Educational Psychology",
    "Economics",
    "Microeconomics",
    "Macroeconomics",
    "Econometrics",
    "Business",
    "Accounting",
    "Finance",
    "Marketing",
    "Management",
    "Human Resources",
    "Operations Research",
    "Political Science",
    "International Relations",
    "Comparative Politics",
    "Public Administration",
    "Law",
    "Jurisprudence",
    "Criminology",
    "Legal Studies",
    "Education",
    "Curriculum Studies",
    "Instructional Design",
    "Special Education",
    "Religious Studies",
    "Theology",
    "Comparative Religion",
    "History",
    "Ancient History",
    "Medieval History",
    "Modern History",
    "Art History",
    "Archaeology",
    "Classics",
    "Literature",
    "Comparative Literature",
    "English Literature",
    "World Literature",
    "Cultural Studies",
    "Media Studies",
    "Film Studies",
    "Communication Studies",
    "Journalism",
    "Library Science",
    "Architecture",
    "Urban Studies",
    "Design",
    "Graphic Design",
    "Fashion Design",
    "Performing Arts",
    "Musicology",
    "Ethnomusicology",
    "Dance Studies",
    "Theatre Studies",
    "Fine Arts",
    "Visual Arts",
    "Creative Writing",
    "Agricultural Science",
    "Horticulture",
    "Animal Science",
    "Food Science",
    "Nutrition",
    "Public Health",
    "Nursing",
    "Medicine",
    "Dentistry",
    "Pharmacy",
    "Veterinary Science",
    "Occupational Therapy",
    "Physical Therapy",
    "Speech Pathology",
    "Social Work",
    "Military Science",
    "Sports Science",
];

pub const DEGREES_TITLES: [&str; 146] = [
    "High School Diploma",
    "General Certificate of Secondary Education",
    "A-Level",
    "Associate of Arts",
    "Associate of Science",
    "Associate of Applied Science",
    "Bachelor of Arts",
    "Bachelor of Science",
    "Bachelor of Fine Arts",
    "Bachelor of Business Administration",
    "Bachelor of Engineering",
    "Bachelor of Laws",
    "Bachelor of Architecture",
    "Bachelor of Education",
    "Bachelor of Music",
    "Bachelor of Computer Science",
    "Bachelor of Social Work",
    "Bachelor of Nursing",
    "Bachelor of Public Health",
    "Bachelor of Pharmacy",
    "Bachelor of Design",
    "Bachelor of Information Technology",
    "Bachelor of Communications",
    "Bachelor of Mathematics",
    "Bachelor of Philosophy",
    "Bachelor of Economics",
    "Bachelor of Political Science",
    "Master of Arts",
    "Master of Science",
    "Master of Business Administration",
    "Master of Fine Arts",
    "Master of Engineering",
    "Master of Architecture",
    "Master of Laws",
    "Master of Education",
    "Master of Public Health",
    "Master of Social Work",
    "Master of Nursing",
    "Master of Computer Science",
    "Master of Information Systems",
    "Master of Public Administration",
    "Master of Public Policy",
    "Master of Mathematics",
    "Master of Philosophy",
    "Master of Finance",
    "Master of Accounting",
    "Master of Psychology",
    "Master of International Relations",
    "Doctor of Philosophy",
    "Doctor of Science",
    "Doctor of Medicine",
    "Doctor of Dental Surgery",
    "Doctor of Dental Medicine",
    "Doctor of Veterinary Medicine",
    "Doctor of Pharmacy",
    "Doctor of Nursing Practice",
    "Doctor of Education",
    "Doctor of Business Administration",
    "Doctor of Laws",
    "Doctor of Theology",
    "Doctor of Engineering",
    "Doctor of Public Health",
    "Doctor of Psychology",
    "Postdoctoral Fellow",
    "Licentiate",
    "Habilitation",
    "Chartered Engineer",
    "Chartered Accountant",
    "Certified Public Accountant",
    "Certified Financial Planner",
    "Professional Engineer",
    "Registered Nurse",
    "Licensed Practical Nurse",
    "Paralegal Certificate",
    "Teaching Certificate",
    "TESOL Certificate",
    "CELTA",
    "Diploma in Engineering",
    "Diploma in Business",
    "Diploma in IT",
    "Diploma in Education",
    "Diploma in Marketing",
    "Diploma in Law",
    "Technical Diploma",
    "Vocational Certificate",
    "Trade Qualification",
    "Apprenticeship Certificate",
    "Journeyman Certificate",
    "Craft Certificate",
    "Certificate IV",
    "Advanced Diploma",
    "Higher National Certificate",
    "Higher National Diploma",
    "Professional Diploma",
    "Foundation Degree",
    "Graduate Certificate",
    "Graduate Diploma",
    "Executive MBA",
    "Online MBA",
    "Dual Degree",
    "Double Major",
    "Honours Degree",
    "First Class Honours",
    "Second Class Honours",
    "Distinction",
    "Merit",
    "Pass",
    "Doctor honoris causa",
    "Emeritus Professor",
    "Adjunct Professor",
    "Visiting Scholar",
    "Research Fellow",
    "Teaching Fellow",
    "Lecturer",
    "Senior Lecturer",
    "Reader",
    "Professor",
    "Instructor",
    "Assistant Professor",
    "Associate Professor",
    "Dean",
    "Chancellor",
    "Provost",
    "Rector",
    "Academic Advisor",
    "Graduate Assistant",
    "Postgraduate",
    "Undergraduate",
    "Fellow of the Royal Society",
    "Member of the Academy of Sciences",
    "Doctor of Humane Letters",
    "Doctor of Divinity",
    "Professional Certificate",
    "Online Certificate",
    "Summer School Certificate",
    "MOOC Completion",
    "Nano Degree",
    "Micro Masters",
    "Specialisation Certificate",
    "Continuing Education Unit",
    "Professional Development Unit",
    "CPD Certificate",
    "Academic Transcript",
    "Letter of Recommendation",
    "Diploma Supplement",
    "Credential",
];

pub const FAMOUS_UNIVERSITIES: [&str; 145] = [
    "Harvard University",
    "University of Oxford",
    "Stanford University",
    "Massachusetts Institute of Technology",
    "University of Cambridge",
    "California Institute of Technology",
    "Princeton University",
    "Yale University",
    "University of Chicago",
    "Columbia University",
    "University of Pennsylvania",
    "University of California Berkeley",
    "University of California Los Angeles",
    "University of Michigan",
    "University of Toronto",
    "University College London",
    "University of Edinburgh",
    "University of Tokyo",
    "University of Melbourne",
    "University of Sydney",
    "University of Hong Kong",
    "National University of Singapore",
    "University of California San Diego",
    "Cornell University",
    "University of Washington",
    "University of Wisconsin Madison",
    "University of Illinois Urbana Champaign",
    "University of Texas Austin",
    "New York University",
    "London School of Economics",
    "University of British Columbia",
    "University of Manchester",
    "University of Queensland",
    "University of Amsterdam",
    "University of Zurich",
    "University of Copenhagen",
    "University of Helsinki",
    "University of Oslo",
    "University of Sao Paulo",
    "University of Buenos Aires",
    "University of Cape Town",
    "University of Auckland",
    "Seoul National University",
    "Peking University",
    "Tsinghua University",
    "ETH Zurich",
    "Technical University of Munich",
    "University of Geneva",
    "University of Warwick",
    "University of Glasgow",
    "University of Bristol",
    "University of Leeds",
    "University of Southampton",
    "University of Birmingham",
    "University of Sheffield",
    "University of Nottingham",
    "University of Liverpool",
    "University of New South Wales",
    "Australian National University",
    "University of Western Australia",
    "University of Adelaide",
    "University of Otago",
    "McGill University",
    "University of Montreal",
    "University of Alberta",
    "Carnegie Mellon University",
    "Duke University",
    "Johns Hopkins University",
    "Northwestern University",
    "University of Virginia",
    "University of Southern California",
    "University of Florida",
    "University of North Carolina Chapel Hill",
    "University of Maryland College Park",
    "Boston University",
    "University of Minnesota",
    "University of Arizona",
    "University of Colorado Boulder",
    "University of California Davis",
    "University of California Irvine",
    "University of California Santa Barbara",
    "University of California Santa Cruz",
    "University of Pittsburgh",
    "University of Rochester",
    "University of Texas Southwestern Medical Center",
    "University of Illinois Chicago",
    "University of Utah",
    "University of Hawaii",
    "University of Notre Dame",
    "University of Miami",
    "University of Kansas",
    "University of Iowa",
    "University of Connecticut",
    "University of Georgia",
    "University of Delaware",
    "University of Nebraska Lincoln",
    "University of Missouri",
    "University of Oregon",
    "University of Kentucky",
    "University of Tennessee",
    "University of Cincinnati",
    "University of Arkansas",
    "University of Oklahoma",
    "University of Mississippi",
    "University of Louisiana",
    "University of South Carolina",
    "University of Vermont",
    "University of New Hampshire",
    "University of Maine",
    "University of Montana",
    "University of Idaho",
    "University of Nevada",
    "University of Alaska Fairbanks",
    "University of Wyoming",
    "University of North Dakota",
    "University of South Dakota",
    "University of Nebraska Omaha",
    "University of Kansas Medical Center",
    "University of Texas Medical Branch",
    "University of Texas Health Science Center",
    "University of California San Francisco",
    "University of Washington School of Medicine",
    "University of Pittsburgh School of Medicine",
    "University of Michigan Medical School",
    "University of Wisconsin School of Medicine",
    "University of Minnesota Medical School",
    "University of Iowa Carver College of Medicine",
    "University of Virginia School of Medicine",
    "University of North Carolina School of Medicine",
    "University of Florida College of Medicine",
    "University of Illinois College of Medicine",
    "University of Arizona College of Medicine",
    "University of Colorado School of Medicine",
    "University of Utah School of Medicine",
    "University of Hawaii John A. Burns School of Medicine",
    "University of Nebraska Medical Center",
    "University of Arkansas for Medical Sciences",
    "University of Oklahoma College of Medicine",
    "University of Louisville School of Medicine",
    "University of South Carolina School of Medicine",
    "University of Vermont College of Medicine",
    "University of New Hampshire School of Law",
    "University of Maine School of Law",
    "University of Montana School of Law",
    "University of Idaho College of Law",
];
