pub const US_STATE_ABBREVIATIONS: [&str; 50] = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS",
    "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
    "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
    "WI", "WY",
];

pub const AMERICAN_STATES: [&str; 50] = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];

pub const US_ROADS: [&str; 51] = [
    "Route 66",
    "Pacific Coast Highway",
    "Lincoln Highway",
    "Blue Ridge Parkway",
    "US Highway 1",
    "Interstate 95",
    "Interstate 10",
    "Interstate 5",
    "Interstate 80",
    "Route 1",
    "Broadway",
    "Sunset Boulevard",
    "Michigan Avenue",
    "Hollywood Boulevard",
    "Fifth Avenue",
    "Wall Street",
    "Bourbon Street",
    "Canal Street",
    "Lombard Street",
    "Mulholland Drive",
    "Pennsylvania Avenue",
    "Park Avenue",
    "Santa Monica Boulevard",
    "Beale Street",
    "Magnolia Avenue",
    "Las Vegas Boulevard",
    "Ocean Drive",
    "King’s Highway",
    "State Route 1",
    "Dixie Highway",
    "Cherokee Street",
    "Atlantic Avenue",
    "Bay Street",
    "Columbia Road",
    "Grand Avenue",
    "Elm Street",
    "Main Street",
    "Elm Street",
    "Market Street",
    "Broad Street",
    "High Street",
    "Mulberry Street",
    "Orange Avenue",
    "Harbor Drive",
    "Seventh Avenue",
    "Madison Avenue",
    "Roosevelt Boulevard",
    "Jefferson Avenue",
    "Canal Boulevard",
    "Wilshire Boulevard",
    "Delaware Avenue",
];

pub const US_ROAD_TYPES: [&str; 20] = [
    "Street",
    "Avenue",
    "Boulevard",
    "Drive",
    "Road",
    "Lane",
    "Court",
    "Circle",
    "Trail",
    "Parkway",
    "Terrace",
    "Place",
    "Way",
    "Highway",
    "Expressway",
    "Freeway",
    "Alley",
    "Loop",
    "Crescent",
    "Row",
];
