pub const COUNTRIES: [&str; 194] = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. \"Swaziland\")",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

pub const MOST_POPULATED_CITIES: [&str; 199] = [
    "Tokyo",
    "Delhi",
    "Shanghai",
    "São Paulo",
    "Mexico City",
    "Cairo",
    "Mumbai",
    "Beijing",
    "Dhaka",
    "Osaka",
    "New York City",
    "Karachi",
    "Buenos Aires",
    "Chongqing",
    "Istanbul",
    "Kolkata",
    "Manila",
    "Lagos",
    "Rio de Janeiro",
    "Tianjin",
    "Kinshasa",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Paris",
    "Bogotá",
    "Jakarta",
    "Chennai",
    "Lima",
    "Bangkok",
    "Seoul",
    "Nagoya",
    "Hyderabad",
    "London",
    "Tehran",
    "Chicago",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Ho Chi Minh City",
    "Luanda",
    "Ahmedabad",
    "Kuala Lumpur",
    "Xi'an",
    "Hong Kong",
    "Dongguan",
    "Hangzhou",
    "Foshan",
    "Shenyang",
    "Riyadh",
    "Baghdad",
    "Santiago",
    "Surat",
    "Madrid",
    "Suzhou",
    "Pune",
    "Harbin",
    "Houston",
    "Dallas",
    "Toronto",
    "Dar es Salaam",
    "Miami",
    "Belo Horizonte",
    "Singapore",
    "Philadelphia",
    "Atlanta",
    "Fukuoka",
    "Khartoum",
    "Barcelona",
    "Johannesburg",
    "Saint Petersburg",
    "Qingdao",
    "Dalian",
    "Washington, D.C.",
    "Yangon",
    "Alexandria",
    "Jinan",
    "Guadalajara",
    "Boston",
    "Sydney",
    "Melbourne",
    "Cape Town",
    "Zhengzhou",
    "Monterrey",
    "Chittagong",
    "Nairobi",
    "Hanoi",
    "Addis Ababa",
    "Kabul",
    "Hefei",
    "Shantou",
    "Rangoon",
    "Pittsburgh",
    "Ankara",
    "Brasília",
    "Phoenix",
    "Fort Worth",
    "Detroit",
    "Medellín",
    "Recife",
    "Fortaleza",
    "Salvador",
    "Porto Alegre",
    "Curitiba",
    "Guayaquil",
    "Kuwait City",
    "Casablanca",
    "Vienna",
    "Budapest",
    "Warsaw",
    "Prague",
    "Brussels",
    "Munich",
    "Berlin",
    "Milan",
    "Rome",
    "Amsterdam",
    "Hamburg",
    "Cologne",
    "Lyon",
    "Marseille",
    "Naples",
    "Zurich",
    "Lisbon",
    "Athens",
    "Copenhagen",
    "Stockholm",
    "Oslo",
    "Helsinki",
    "Dublin",
    "Edinburgh",
    "Glasgow",
    "Birmingham",
    "Manchester",
    "Leeds",
    "Liverpool",
    "Sheffield",
    "Bristol",
    "Cardiff",
    "Newcastle",
    "Nottingham",
    "Southampton",
    "Leicester",
    "Coventry",
    "Bradford",
    "Hull",
    "Pune",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Guwahati",
    "Chandigarh",
    "Solapur",
    "Hubli-Dharwad",
    "Bareilly",
    "Mysore",
    "Tiruchirappalli",
    "Tiruppur",
    "Aligarh",
    "Bhubaneswar",
    "Moradabad",
    "Mira-Bhayandar",
    "Gurgaon",
    "Noida",
    "Jalandhar",
];

pub const CONTINENTS: [&str; 7] = [
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
];

pub const COUNTRY_CODES: [&str; 249] = [
    "AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW", "AU", "AT", "AZ",
    "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT", "BO", "BQ", "BA", "BW", "BV", "BR",
    "IO", "BN", "BG", "BF", "BI", "CV", "KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC",
    "CO", "KM", "CD", "CG", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ", "DK", "DJ", "DM", "DO",
    "EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR", "GF", "PF", "TF",
    "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP", "GU", "GT", "GG", "GN", "GW", "GY",
    "HT", "HM", "VA", "HN", "HK", "HU", "IS", "IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM",
    "JP", "JE", "JO", "KZ", "KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY",
    "LI", "LT", "LU", "MO", "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU", "YT", "MX",
    "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR", "NP", "NL", "NC", "NZ", "NI",
    "NE", "NG", "NU", "NF", "MK", "MP", "NO", "OM", "PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH",
    "PN", "PL", "PT", "PR", "QA", "RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC",
    "WS", "SM", "ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA", "GS",
    "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ", "TH", "TL", "TG", "TK",
    "TO", "TT", "TN", "TR", "TM", "TC", "TV", "UG", "UA", "AE", "GB", "US", "UM", "UY", "UZ", "VU",
    "VE", "VN", "VG", "VI", "WF", "EH", "YE", "ZM", "ZW",
];

pub const WORLD_STREETS: [&str; 95] = [
    "Broadway",
    "Fifth Avenue",
    "Wall Street",
    "Sunset Boulevard",
    "Champs Elysees",
    "Oxford Street",
    "Lombard Street",
    "Las Ramblas",
    "Nevsky Prospekt",
    "Orchard Road",
    "Via del Corso",
    "Kurfürstendamm",
    "Avenida Paulista",
    "Bourbon Street",
    "Nanjing Road",
    "King's Road",
    "Queen Street",
    "Rodeo Drive",
    "Sunshine Coast Highway",
    "Gran Via",
    "Ginza",
    "Rodeo Drive",
    "Unter den Linden",
    "Hollywood Boulevard",
    "Michigan Avenue",
    "Pennsylvania Avenue",
    "Friedrichstrasse",
    "La Rambla",
    "Khao San Road",
    "Market Street",
    "Bourbon Street",
    "Las Olas Boulevard",
    "Beale Street",
    "Rue de Rivoli",
    "Queen Street",
    "Yonge Street",
    "Abbey Road",
    "Portobello Road",
    "Lombard Street",
    "Baker Street",
    "Sunset Boulevard",
    "Bourbon Street",
    "Champs Elysees",
    "Broadway",
    "Oxford Street",
    "Las Ramblas",
    "Nevsky Prospekt",
    "Orchard Road",
    "Via del Corso",
    "Kurfürstendamm",
    "Avenida Paulista",
    "Bourbon Street",
    "Nanjing Road",
    "King's Road",
    "Rodeo Drive",
    "Gran Via",
    "Ginza",
    "Unter den Linden",
    "Hollywood Boulevard",
    "Michigan Avenue",
    "Pennsylvania Avenue",
    "Friedrichstrasse",
    "La Rambla",
    "Khao San Road",
    "Market Street",
    "Las Olas Boulevard",
    "Beale Street",
    "Rue de Rivoli",
    "Queen Street",
    "Yonge Street",
    "Abbey Road",
    "Portobello Road",
    "Lombard Street",
    "Baker Street",
    "Sunset Boulevard",
    "Bourbon Street",
    "Champs Elysees",
    "Broadway",
    "Oxford Street",
    "Las Ramblas",
    "Nevsky Prospekt",
    "Orchard Road",
    "Via del Corso",
    "Kurfürstendamm",
    "Avenida Paulista",
    "Bourbon Street",
    "Nanjing Road",
    "King's Road",
    "Rodeo Drive",
    "Gran Via",
    "Ginza",
    "Unter den Linden",
    "Hollywood Boulevard",
    "Michigan Avenue",
    "Pennsylvania Avenue",
];

pub const LONGEST_RIVERS: [&str; 50] = [
    "Nile",
    "Amazon",
    "Yangtze",
    "Mississippi",
    "Yenisei",
    "Yellow",
    "Ob",
    "Parana",
    "Congo",
    "Amur",
    "Lena",
    "Mekong",
    "Mackenzie",
    "Niger",
    "Murray",
    "Tocantins",
    "Volga",
    "Indus",
    "Shatt al Arab",
    "Madeira",
    "Yukon",
    "Sao Francisco",
    "Syr Darya",
    "Salween",
    "Saint Lawrence",
    "Rio Grande",
    "Tunguska",
    "Danube",
    "Zambezi",
    "Don",
    "Ganges",
    "Rhine",
    "Saint John",
    "Tana",
    "Ural",
    "Kolyma",
    "Kura",
    "Purus",
    "Salado",
    "Selenge",
    "Vaal",
    "Gila",
    "Kaveri",
    "Panjnad",
    "Tigris",
    "Kafue",
    "Seyhan",
    "Isonzo",
    "Pechora",
    "Tagus",
];
