name: Lints

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    clippy:
        strategy:
          matrix:
            rust: [stable, nightly]
            os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.rust }}
                override: true
                components: clippy

            - name: Cargo clippy
              run: cargo clippy --all -- --verbose -D warnings
