name: Coverage

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                override: true

            - name: Install cargo Binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install tarpaulin
              run: cargo binstall -y cargo-tarpaulin

            - name: Check coverage
              run: cargo tarpaulin --doc --tests --fail-under 98

            - name: Run coverage per feature
              run: |
                features=(
                  address animals art colours computer currencies datetime education finance france history internet minimal names people personal science sky_space text uk us work world
                )
                for feature in "${features[@]}"; do
                  echo "Running coverage for feature: $feature"
                  cargo tarpaulin --features "$feature" --no-default-features --fail-under 80
                done
