name: Coverage

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:
        strategy:
          matrix:
            rust: [nightly]
            os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.rust }}
                override: true

            - name: Install cargo binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install tarpaulin
              run: cargo binstall -y cargo-tarpaulin

            - name: Check coverage
              run: cargo tarpaulin --doc --tests --fail-under 95
