name: Tests

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    tests:
        strategy:
          matrix:
            rust: [stable, nightly]
            os: [ubuntu-latest, windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.rust }}
                override: true

            - name: Install cargo binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install cargo hack
              run: cargo binstall -y cargo-hack

            - name: Check coverage
              run: cargo hack test --each-feature --exclude-no-default-features
