name: Coverage

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            rust: [stable, nightly]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                override: true

            - name: Install cargo Binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install tarpaulin
              run: cargo binstall -y cargo-hack

            - name: Check coverage
              run: cargo hack --each-feature --exclude-no-default-features
