pub const CURRENCY_SYMBOLS: [&str; 40] = [
    "$", "€", "£", "¥", "₹", "₽", "₩", "₪", "₫", "฿", "₴", "₦", "₲", "₵", "₡", "₺", "₸", "₼", "₺",
    "₺", "₺", "₮", "₦", "₱", "₭", "₲", "₳", "₥", "₠", "₣", "₤", "₧", "₨", "₩", "₪", "₫", "₭", "₮",
    "₯", "₰",
];

pub const CURRENCY_NAMES: [&str; 50] = [
    "US Dollar",
    "Euro",
    "Japanese Yen",
    "British Pound",
    "Australian Dollar",
    "Canadian Dollar",
    "Swiss Franc",
    "Chinese Yuan",
    "Swedish Krona",
    "New Zealand Dollar",
    "Mexican Peso",
    "Singapore Dollar",
    "Hong Kong Dollar",
    "Norwegian Krone",
    "South Korean Won",
    "Turkish Lira",
    "Russian Ruble",
    "Indian Rupee",
    "Brazilian Real",
    "South African Rand",
    "Philippine Peso",
    "Czech Koruna",
    "Indonesian Rupiah",
    "Malaysian Ringgit",
    "Hungarian Forint",
    "Icelandic Krona",
    "Israeli New Shekel",
    "Colombian Peso",
    "Thai Baht",
    "Polish Zloty",
    "Chilean Peso",
    "Saudi Riyal",
    "Danish Krone",
    "United Arab Emirates Dirham",
    "Argentine Peso",
    "Egyptian Pound",
    "Pakistani Rupee",
    "Qatari Riyal",
    "Vietnamese Dong",
    "Bangladeshi Taka",
    "Ukrainian Hryvnia",
    "Peruvian Sol",
    "Kuwaiti Dinar",
    "Omani Rial",
    "Moroccan Dirham",
    "Bahraini Dinar",
    "Costa Rican Colon",
    "Croatian Kuna",
    "Jordanian Dinar",
    "Lebanese Pound",
];

pub const CURRENCY_CODES: [&str; 50] = [
    "USD", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "CNY", "SEK", "NZD", "MXN", "SGD", "HKD",
    "NOK", "KRW", "TRY", "RUB", "INR", "BRL", "ZAR", "PHP", "CZK", "IDR", "MYR", "HUF", "ISK",
    "ILS", "COP", "THB", "PLN", "CLP", "SAR", "DKK", "AED", "ARS", "EGP", "PKR", "QAR", "VND",
    "BDT", "UAH", "PEN", "KWD", "OMR", "MAD", "BHD", "CRC", "HRK", "JOD", "LBP",
];
