pub const FRENCH_STREETS: [&str; 94] = [
    "Avenue des Champs Elysees",
    "Rue de Rivoli",
    "Boulevard Haussmann",
    "Rue Saint Honore",
    "Avenue Montaigne",
    "Rue du Faubourg Saint Honore",
    "Rue de la Paix",
    "Rue de la Boetie",
    "Avenue des Champs Elysees",
    "Boulevard Saint Germain",
    "Rue de la Fayette",
    "Rue Oberkampf",
    "Rue de la Roquette",
    "Rue de Belleville",
    "Rue Mouffetard",
    "Rue des Martyrs",
    "Rue de la Huchette",
    "Rue des Rosiers",
    "Rue Saint Denis",
    "Rue du Temple",
    "Rue des Francs Bourgeois",
    "Rue du Commerce",
    "Rue de la Pompe",
    "Rue de Rennes",
    "Rue de la Convention",
    "Rue de Vaugirard",
    "Rue de la Tour",
    "Rue de Grenelle",
    "Rue Cler",
    "Rue Saint Antoine",
    "Rue de Buci",
    "Rue des Archives",
    "Rue du Bac",
    "Rue de la Harpe",
    "Rue de la Paix",
    "Rue Saint Lazare",
    "Boulevard Montmartre",
    "Boulevard Bonne Nouvelle",
    "Boulevard Voltaire",
    "Rue des Petits Champs",
    "Rue de la Clef",
    "Rue de l'Abbe de l'Epee",
    "Rue de Lappe",
    "Rue des Archives",
    "Rue Saint Martin",
    "Rue des Ecoles",
    "Rue Saint Jacques",
    "Rue de la Huchette",
    "Rue des Ecoles",
    "Rue de Rivoli",
    "Boulevard Beaumarchais",
    "Rue du Faubourg Montmartre",
    "Rue de Douai",
    "Rue Lafayette",
    "Rue de la Monnaie",
    "Rue de la Barre",
    "Rue des Francs Bourgeois",
    "Rue du Faubourg Saint Antoine",
    "Rue de la Victoire",
    "Rue Saint Georges",
    "Rue de la Pompe",
    "Rue de la Boetie",
    "Boulevard Haussmann",
    "Boulevard des Italiens",
    "Rue Saint Honore",
    "Rue du Faubourg Poissonniere",
    "Rue de la Bourse",
    "Rue de Seine",
    "Rue de Turenne",
    "Rue de Castiglione",
    "Rue de l'Odéon",
    "Rue de la Tour d'Auvergne",
    "Rue Saint Dominique",
    "Rue du Pont Neuf",
    "Rue du Mont Thabor",
    "Rue des Archives",
    "Rue de l'Eglise",
    "Rue Saint Charles",
    "Rue de Bellechasse",
    "Rue de la Villette",
    "Rue du Faubourg Saint Martin",
    "Rue des Francs Bourgeois",
    "Rue du Chemin Vert",
    "Rue Saint Bernard",
    "Rue du Faubourg Saint Denis",
    "Rue de la Barre",
    "Rue de la Fontaine",
    "Rue du Cherche Midi",
    "Rue des Martyrs",
    "Rue des Francs Bourgeois",
    "Rue de la Roquette",
    "Rue de la Harpe",
    "Rue des Francs Bourgeois",
    "Rue Saint Antoine",
];

pub const FRENCH_ROAD_TYPES: [&str; 20] = [
    "Avenue",
    "Boulevard",
    "Chemin",
    "Cours",
    "Impasse",
    "Place",
    "Promenade",
    "Quai",
    "Route",
    "Rue",
    "Allée",
    "Voie",
    "Passage",
    "Sentier",
    "Traverse",
    "Esplanade",
    "Square",
    "Ruelle",
    "Domaine",
    "Clos",
];

pub const FRENCH_COUNTIES: [&str; 101] = [
    "Ain",
    "Aisne",
    "Allier",
    "Alpes-de-Haute-Provence",
    "Hautes-Alpes",
    "Alpes-Maritimes",
    "Ardèche",
    "Ardennes",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bouches-du-Rhône",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente-Maritime",
    "Cher",
    "Corrèze",
    "Corse-du-Sud",
    "Haute-Corse",
    "Côte-d'Or",
    "Côtes-d'Armor",
    "Creuse",
    "Dordogne",
    "Doubs",
    "Drôme",
    "Eure",
    "Eure-et-Loir",
    "Finistère",
    "Gard",
    "Haute-Garonne",
    "Gers",
    "Gironde",
    "Hérault",
    "Ille-et-Vilaine",
    "Indre",
    "Indre-et-Loire",
    "Isère",
    "Jura",
    "Landes",
    "Loir-et-Cher",
    "Loire",
    "Haute-Loire",
    "Loire-Atlantique",
    "Loiret",
    "Lot",
    "Lot-et-Garonne",
    "Lozère",
    "Maine-et-Loire",
    "Manche",
    "Marne",
    "Haute-Marne",
    "Mayenne",
    "Meurthe-et-Moselle",
    "Meuse",
    "Morbihan",
    "Moselle",
    "Nièvre",
    "Nord",
    "Oise",
    "Orne",
    "Pas-de-Calais",
    "Puy-de-Dôme",
    "Pyrénées-Atlantiques",
    "Hautes-Pyrénées",
    "Pyrénées-Orientales",
    "Bas-Rhin",
    "Haut-Rhin",
    "Rhône",
    "Haute-Saône",
    "Saône-et-Loire",
    "Sarthe",
    "Savoie",
    "Haute-Savoie",
    "Paris",
    "Seine-Maritime",
    "Seine-et-Marne",
    "Yvelines",
    "Deux-Sèvres",
    "Somme",
    "Tarn",
    "Tarn-et-Garonne",
    "Var",
    "Vaucluse",
    "Vendée",
    "Vienne",
    "Haute-Vienne",
    "Vosges",
    "Yonne",
    "Territoire de Belfort",
    "Essonne",
    "Hauts-de-Seine",
    "Seine-Saint-Denis",
    "Val-de-Marne",
    "Val-d'Oise",
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte",
];

pub const LONGEST_FRENCH_RIVERS: [&str; 50] = [
    "Loire",
    "Seine",
    "Garonne",
    "Rhône",
    "Meuse",
    "Moselle",
    "Dordogne",
    "Saône",
    "Charente",
    "Lot",
    "Vienne",
    "Allier",
    "Marne",
    "Somme",
    "Oise",
    "Aisne",
    "Aube",
    "Tarn",
    "Adour",
    "Hérault",
    "Cèze",
    "Bléone",
    "Durance",
    "Ardèche",
    "Aude",
    "Gave de Pau",
    "Gave d'Oloron",
    "Sèvre Niortaise",
    "Creuse",
    "Sarthe",
    "Cher",
    "Orne",
    "Mayenne",
    "Dives",
    "Eure",
    "Vézère",
    "Loir",
    "La Vienne",
    "La Meurthe",
    "La Drôme",
    "L'Indre",
    "L'Allier",
    "L'Ain",
    "L'Oise",
    "La Vilaine",
    "La Nive",
    "La Dordogne",
    "La Durance",
    "La Saône",
    "La Garonne",
];
