pub const FAMOUS_PHILOSOPHERS: [&str; 151] = [
    "Plato",
    "Aristotle",
    "Socrates",
    "Descartes",
    "Kant",
    "Nietzsche",
    "Confucius",
    "Spinoza",
    "Hume",
    "Locke",
    "Hegel",
    "Rousseau",
    "Marx",
    "Wittgenstein",
    "Heidegger",
    "Sartre",
    "Aquinas",
    "Camus",
    "Mill",
    "Leibniz",
    "Rawls",
    "Dewey",
    "Peirce",
    "Rorty",
    "Derrida",
    "Foucault",
    "Ayer",
    "Quine",
    "Nagel",
    "Chomsky",
    "Popper",
    "Bergson",
    "Russell",
    "Merleau-Ponty",
    "Arendt",
    "Habermas",
    "Butler",
    "Al-Farabi",
    "Averroes",
    "Avicenna",
    "Zeno",
    "Epicurus",
    "Plotinus",
    "Boethius",
    "Augustine",
    "Voltaire",
    "Locke",
    "Hobbes",
    "Machiavelli",
    "Montesquieu",
    "Condorcet",
    "Schopenhauer",
    "Tolstoy",
    "Heidegger",
    "Maritain",
    "Simone de Beauvoir",
    "Jaspers",
    "Feyerabend",
    "Davidson",
    "Anscombe",
    "Nagel",
    "Rousseau",
    "Duns Scotus",
    "Ockham",
    "Wittgenstein",
    "Gadamer",
    "Schelling",
    "Fichte",
    "Levinas",
    "Deleuze",
    "Merlin Donald",
    "Kierkegaard",
    "Schelling",
    "Frege",
    "Moore",
    "Anscombe",
    "McTaggart",
    "Husserl",
    "Gramsci",
    "Feyerabend",
    "Aquinas",
    "Rousseau",
    "Singer",
    "Chalmers",
    "Rawls",
    "Nozick",
    "Putnam",
    "Quine",
    "Habermas",
    "Butler",
    "Nagel",
    "Heidegger",
    "Derrida",
    "Camus",
    "Foucault",
    "Sartre",
    "Nietzsche",
    "Kant",
    "Locke",
    "Hume",
    "Aristotle",
    "Plato",
    "Descartes",
    "Confucius",
    "Sun Tzu",
    "Laozi",
    "Zhuangzi",
    "Mozi",
    "Mencius",
    "Xunzi",
    "Al-Ghazali",
    "Ibn Rushd",
    "Avicenna",
    "Al-Kindi",
    "Aquinas",
    "Ockham",
    "Scotus",
    "Hobbes",
    "Machiavelli",
    "Voltaire",
    "Rousseau",
    "Montesquieu",
    "Hegel",
    "Marx",
    "Schopenhauer",
    "Nietzsche",
    "Heidegger",
    "Sartre",
    "Camus",
    "De Beauvoir",
    "Derrida",
    "Foucault",
    "Butler",
    "Habermas",
    "Rawls",
    "Nozick",
    "Singer",
    "Chalmers",
    "Putnam",
    "Nagel",
    "McDowell",
    "Davidson",
    "Anscombe",
    "Williams",
    "Dewey",
    "James",
    "Peirce",
    "Rorty",
    "Dewey",
    "Brandom",
    "Sellars",
];

pub const FAMOUS_PAINTERS: [&str; 151] = [
    "Leonardo da Vinci",
    "Vincent van Gogh",
    "Pablo Picasso",
    "Michelangelo",
    "Rembrandt",
    "Claude Monet",
    "Salvador Dalí",
    "Raphael",
    "Andy Warhol",
    "Jackson Pollock",
    "Edvard Munch",
    "Paul Cézanne",
    "Henri Matisse",
    "Caravaggio",
    "Georges Seurat",
    "Frida Kahlo",
    "Johannes Vermeer",
    "Pierre-Auguste Renoir",
    "Edgar Degas",
    "Titian",
    "Gustav Klimt",
    "Marc Chagall",
    "Paul Gauguin",
    "Édouard Manet",
    "Wassily Kandinsky",
    "Jan van Eyck",
    "Francisco Goya",
    "Diego Velázquez",
    "Joan Miró",
    "Caspar David Friedrich",
    "Georgia O’Keeffe",
    "Hieronymus Bosch",
    "Albrecht Dürer",
    "Élisabeth Vigée Le Brun",
    "Giorgio de Chirico",
    "Henri Rousseau",
    "Anselm Kiefer",
    "Fernand Léger",
    "Paul Klee",
    "Jean-Michel Basquiat",
    "Keith Haring",
    "Francis Bacon",
    "Lucian Freud",
    "Thomas Gainsborough",
    "Edward Hopper",
    "Édouard Vuillard",
    "Georges Braque",
    "Artemisia Gentileschi",
    "Mary Cassatt",
    "Jean-Auguste-Dominique Ingres",
    "Sandro Botticelli",
    "Roy Lichtenstein",
    "Jean-Baptiste-Camille Corot",
    "Gustave Courbet",
    "Alfred Sisley",
    "Berthe Morisot",
    "Jacques-Louis David",
    "J.M.W. Turner",
    "Francisco de Zurbarán",
    "David Hockney",
    "Piet Mondrian",
    "Marcello Bacciarelli",
    "Hans Holbein",
    "Édouard Detaille",
    "William Blake",
    "Gustave Moreau",
    "James McNeill Whistler",
    "Franz Marc",
    "Georges Rouault",
    "Max Ernst",
    "Kazimir Malevich",
    "Jean Dubuffet",
    "Gustave Caillebotte",
    "Camille Pissarro",
    "Hans Memling",
    "Alfred Stieglitz",
    "John Singer Sargent",
    "Claude Lorrain",
    "Pietro Perugino",
    "Gustave Klimt",
    "Paul Signac",
    "Rene Magritte",
    "Tamara de Lempicka",
    "Emil Nolde",
    "Otto Dix",
    "Max Beckmann",
    "Edwin Landseer",
    "Angelica Kauffman",
    "Edward Burne-Jones",
    "Frederic Leighton",
    "Thomas Cole",
    "Alfred Munnings",
    "Jean-François Millet",
    "Georges Lemmen",
    "Jean-Léon Gérôme",
    "Paul Delaroche",
    "Franz Kline",
    "Keith Haring",
    "Eduardo Paolozzi",
    "Jean Arp",
    "Lovis Corinth",
    "Franz von Stuck",
    "John Constable",
    "Hans Zimmer",
    "El Greco",
    "Marc Antony",
    "Clyfford Still",
    "Jean-Honoré Fragonard",
    "Rosa Bonheur",
    "Lucio Fontana",
    "Hans Baldung",
    "Giorgio Vasari",
    "Giotto",
    "Francis Picabia",
    "Paul Cézanne",
    "Willem de Kooning",
    "Hans Hofmann",
    "Antonio Canaletto",
    "Maurits Cornelis Escher",
    "Georges Seurat",
    "Gustave Doré",
    "Jacopo Tintoretto",
    "Francisco de Goya",
    "David LaChapelle",
    "Jean-Paul Riopelle",
    "Fernando Botero",
    "Yayoi Kusama",
    "Damien Hirst",
    "Takashi Murakami",
    "Banksy",
    "Ai Weiwei",
    "Gerhard Richter",
    "Chuck Close",
    "Jeff Koons",
    "Jenny Holzer",
    "Kara Walker",
    "Zdzisław Beksiński",
    "James Rosenquist",
    "Frank Stella",
    "Helen Frankenthaler",
    "Robert Rauschenberg",
    "Cy Twombly",
    "Ellsworth Kelly",
    "Brice Marden",
    "Donald Judd",
    "Richard Serra",
    "Anish Kapoor",
    "Damien Hirst",
    "Olafur Eliasson",
    "Tracey Emin",
    "Jenny Saville",
];

pub const FAMOUS_WRITERS: [&str; 140] = [
    "William Shakespeare",
    "Jane Austen",
    "Charles Dickens",
    "Leo Tolstoy",
    "Mark Twain",
    "Virginia Woolf",
    "George Orwell",
    "Ernest Hemingway",
    "F. Scott Fitzgerald",
    "J.K. Rowling",
    "Gabriel García Márquez",
    "Franz Kafka",
    "James Joyce",
    "Emily Dickinson",
    "Homer",
    "John Steinbeck",
    "T.S. Eliot",
    "Oscar Wilde",
    "Haruki Murakami",
    "Edgar Allan Poe",
    "Marcel Proust",
    "J.R.R. Tolkien",
    "Mary Shelley",
    "H.G. Wells",
    "Arthur Conan Doyle",
    "Miguel de Cervantes",
    "Sylvia Plath",
    "Aldous Huxley",
    "Ralph Waldo Emerson",
    "Dante Alighieri",
    "George Eliot",
    "E.E. Cummings",
    "Kurt Vonnegut",
    "Langston Hughes",
    "Jules Verne",
    "Robert Frost",
    "William Blake",
    "Toni Morrison",
    "Ray Bradbury",
    "John Milton",
    "Anne Rice",
    "Cormac McCarthy",
    "Louisa May Alcott",
    "Isaac Asimov",
    "Margaret Atwood",
    "Edith Wharton",
    "Lewis Carroll",
    "Philip K. Dick",
    "Sylvia Plath",
    "Charles Baudelaire",
    "Herman Melville",
    "Yann Martel",
    "Walt Whitman",
    "Graham Greene",
    "J.D. Salinger",
    "Cormac McCarthy",
    "Victor Hugo",
    "Chinua Achebe",
    "William Faulkner",
    "Flannery O’Connor",
    "Roald Dahl",
    "Zadie Smith",
    "Salman Rushdie",
    "Isabel Allende",
    "Kazuo Ishiguro",
    "John Updike",
    "E.M. Forster",
    "Stephen King",
    "Neil Gaiman",
    "Emily Brontë",
    "Charlotte Brontë",
    "Henry James",
    "Oscar Wilde",
    "Terry Pratchett",
    "Arthur Miller",
    "George R.R. Martin",
    "Jonathan Swift",
    "Anton Chekhov",
    "Louise Erdrich",
    "Cormac McCarthy",
    "Jack London",
    "Kahlil Gibran",
    "John Grisham",
    "Agatha Christie",
    "Dashiell Hammett",
    "Raymond Chandler",
    "Henrik Ibsen",
    "August Strindberg",
    "Jean-Paul Sartre",
    "Albert Camus",
    "Simone de Beauvoir",
    "Franz Kafka",
    "Marcel Proust",
    "James Baldwin",
    "Maya Angelou",
    "T.S. Eliot",
    "Sylvia Plath",
    "Seamus Heaney",
    "Pablo Neruda",
    "Rainer Maria Rilke",
    "Dylan Thomas",
    "Ted Hughes",
    "Robert Browning",
    "Elizabeth Barrett Browning",
    "John Keats",
    "Percy Bysshe Shelley",
    "William Wordsworth",
    "Samuel Taylor Coleridge",
    "Emily Dickinson",
    "Langston Hughes",
    "Gwendolyn Brooks",
    "Billy Collins",
    "Mary Oliver",
    "Robert Frost",
    "E.E. Cummings",
    "Charles Bukowski",
    "Allen Ginsberg",
    "W.H. Auden",
    "Sylvia Plath",
    "Matsuo Bashō",
    "Rumi",
    "Li Bai",
    "Rabindranath Tagore",
    "Octavio Paz",
    "Derek Walcott",
    "Seamus Heaney",
    "Ted Hughes",
    "Carol Ann Duffy",
    "Billy Collins",
    "Louise Glück",
    "Mary Oliver",
    "Philip Larkin",
    "John Ashbery",
    "Adrienne Rich",
    "Robert Hayden",
    "Anne Sexton",
    "Sylvia Plath",
    "William Carlos Williams",
    "Langston Hughes",
    "Carl Sandburg",
];

pub const FAMOUS_COMPOSERS: [&str; 141] = [
    "Ludwig van Beethoven",
    "Wolfgang Amadeus Mozart",
    "Johann Sebastian Bach",
    "Frédéric Chopin",
    "Pyotr Ilyich Tchaikovsky",
    "Antonio Vivaldi",
    "Joseph Haydn",
    "Claude Debussy",
    "Franz Schubert",
    "Gustav Mahler",
    "Igor Stravinsky",
    "George Frideric Handel",
    "Johannes Brahms",
    "Richard Wagner",
    "Sergei Rachmaninoff",
    "Felix Mendelssohn",
    "Robert Schumann",
    "Dmitri Shostakovich",
    "Giuseppe Verdi",
    "Jean Sibelius",
    "Antonín Dvořák",
    "Camille Saint-Saëns",
    "Gioachino Rossini",
    "Carl Maria von Weber",
    "Edvard Grieg",
    "Maurice Ravel",
    "Béla Bartók",
    "Georges Bizet",
    "Modest Mussorgsky",
    "Aram Khachaturian",
    "Giacomo Puccini",
    "Alexander Borodin",
    "Ralph Vaughan Williams",
    "Francis Poulenc",
    "Anton Bruckner",
    "Charles Ives",
    "Igor Stravinsky",
    "Benjamin Britten",
    "John Cage",
    "Philip Glass",
    "Aaron Copland",
    "Gustav Holst",
    "Edgar Varèse",
    "Sergei Prokofiev",
    "Carl Orff",
    "Alban Berg",
    "Clara Schumann",
    "Heinrich Schütz",
    "Jean-Philippe Rameau",
    "Johann Strauss II",
    "Domenico Scarlatti",
    "Gaetano Donizetti",
    "Hector Berlioz",
    "Paul Hindemith",
    "Gustav Mahler",
    "Erik Satie",
    "Arnold Schoenberg",
    "Samuel Barber",
    "Edward Elgar",
    "Luigi Boccherini",
    "Francisco Tárrega",
    "Franciszek Chopin",
    "John Williams",
    "Hans Zimmer",
    "Ennio Morricone",
    "Danny Elfman",
    "Thomas Newman",
    "Max Richter",
    "Michael Nyman",
    "Philip Glass",
    "Steve Reich",
    "John Adams",
    "Leonard Bernstein",
    "Gustav Mahler",
    "Sergei Rachmaninoff",
    "Camille Saint-Saëns",
    "Johann Pachelbel",
    "Antonio Salieri",
    "Franz Liszt",
    "Jean-Baptiste Lully",
    "George Gershwin",
    "Dmitri Kabalevsky",
    "Carl Philipp Emanuel Bach",
    "John Dowland",
    "Edvard Grieg",
    "Anton Webern",
    "Alfred Schnittke",
    "Benjamin Britten",
    "Leoš Janáček",
    "Gioachino Rossini",
    "Ottorino Respighi",
    "Charles Gounod",
    "Fanny Mendelssohn",
    "Louise Farrenc",
    "Clara Schumann",
    "Lili Boulanger",
    "Amy Beach",
    "Florence Price",
    "Ethel Smyth",
    "Nikolai Rimsky-Korsakov",
    "Dmitri Shostakovich",
    "Sergei Prokofiev",
    "Igor Stravinsky",
    "Alexander Glazunov",
    "Mily Balakirev",
    "Carl Nielsen",
    "Jean Sibelius",
    "Arvo Pärt",
    "Gustav Holst",
    "Benjamin Britten",
    "Michael Tippett",
    "Edward Elgar",
    "Ralph Vaughan Williams",
    "Alexander Scriabin",
    "Nikolai Medtner",
    "Anton Bruckner",
    "Johann Nepomuk Hummel",
    "Samuel Coleridge-Taylor",
    "William Walton",
    "Herbert Howells",
    "Malcolm Arnold",
    "Havergal Brian",
    "Ernest Bloch",
    "George Crumb",
    "Alfred Schnittke",
    "John Tavener",
    "Karlheinz Stockhausen",
    "György Ligeti",
    "Pierre Boulez",
    "Einojuhani Rautavaara",
    "Tan Dun",
    "John Cage",
    "Philip Glass",
    "Steve Reich",
    "Arvo Pärt",
    "Henryk Górecki",
    "Kaija Saariaho",
    "Unsuk Chin",
    "Jennifer Higdon",
    "Anna Clyne",
    "Missy Mazzoli",
];

pub const FAMOUS_MATHEMATICIANS: [&str; 155] = [
    "Euclid",
    "Archimedes",
    "Isaac Newton",
    "Carl Friedrich Gauss",
    "Leonhard Euler",
    "Pierre-Simon Laplace",
    "Joseph Fourier",
    "Henri Poincaré",
    "Gottfried Wilhelm Leibniz",
    "David Hilbert",
    "Blaise Pascal",
    "René Descartes",
    "George Boole",
    "John von Neumann",
    "Srinivasa Ramanujan",
    "Bernhard Riemann",
    "Kurt Gödel",
    "Alan Turing",
    "Niels Henrik Abel",
    "Évariste Galois",
    "Augustin-Louis Cauchy",
    "Joseph-Louis Lagrange",
    "Élie Cartan",
    "André Weil",
    "Sofia Kovalevskaya",
    "Emmy Noether",
    "John Nash",
    "Mary Cartwright",
    "Harald Bohr",
    "Jean-Pierre Serre",
    "Jacques Hadamard",
    "Felix Klein",
    "Carl Gustav Jacobi",
    "David Mumford",
    "William Rowan Hamilton",
    "J.J. Sylvester",
    "George Pólya",
    "Hermann Minkowski",
    "Alan Baker",
    "Paul Erdős",
    "John Conway",
    "Michael Atiyah",
    "Peter Lax",
    "Jean Leray",
    "Shing-Tung Yau",
    "Andrew Wiles",
    "Terence Tao",
    "Grigori Perelman",
    "Maryam Mirzakhani",
    "Roger Penrose",
    "Isaiah Bowman",
    "Alfred North Whitehead",
    "Emil Artin",
    "Norbert Wiener",
    "Ludwig Wittgenstein",
    "Richard Feynman",
    "Max Born",
    "Alexander Grothendieck",
    "Hermann Weyl",
    "Andrey Kolmogorov",
    "Paul Dirac",
    "René Thom",
    "William Thurston",
    "Louis de Broglie",
    "Alexander Fleming",
    "Henri Lebesgue",
    "Otto Toeplitz",
    "Heinz Hopf",
    "Kiyoshi Itō",
    "John Milnor",
    "Jacob Bernoulli",
    "James Clerk Maxwell",
    "Sophus Lie",
    "Bernard Bolzano",
    "Cauchy",
    "Émile Picard",
    "Joseph Henry",
    "G.H. Hardy",
    "Edmond Laguerre",
    "Emil Borel",
    "Mikhail Lavrentiev",
    "David Blackwell",
    "Richard Courant",
    "Anders Celsius",
    "Alonzo Church",
    "Otto Hahn",
    "Felix Hausdorff",
    "Andrei Markov",
    "Leonhard Euler",
    "Carl Jacobi",
    "August Ferdinand Möbius",
    "Bernard Riemann",
    "Sophus Lie",
    "Rene Descartes",
    "Niels Henrik Abel",
    "Évariste Galois",
    "Isaac Newton",
    "Leonhard Euler",
    "Carl Friedrich Gauss",
    "David Hilbert",
    "Alan Turing",
    "Henri Poincaré",
    "Pierre de Fermat",
    "Joseph-Louis Lagrange",
    "Bernhard Riemann",
    "Emmy Noether",
    "Srinivasa Ramanujan",
    "Kurt Gödel",
    "André Weil",
    "Jean-Pierre Serre",
    "John von Neumann",
    "Paul Erdős",
    "John Nash",
    "Terence Tao",
    "Maryam Mirzakhani",
    "Grigori Perelman",
    "Alexander Grothendieck",
    "Michael Atiyah",
    "John Milnor",
    "Pierre-Simon Laplace",
    "William Rowan Hamilton",
    "Georg Cantor",
    "Richard Feynman",
    "Paul Dirac",
    "David Mumford",
    "Roger Penrose",
    "Andrew Wiles",
    "Emil Artin",
    "Norbert Wiener",
    "Felix Klein",
    "Hermann Minkowski",
    "Peter Lax",
    "Jean Leray",
    "Shing-Tung Yau",
    "Alexander Fleming",
    "Henri Lebesgue",
    "Otto Toeplitz",
    "Heinz Hopf",
    "Kiyoshi Itō",
    "John Conway",
    "Harald Bohr",
    "Mary Cartwright",
    "Jacques Hadamard",
    "George Pólya",
    "Alfred North Whitehead",
    "Max Born",
    "Alonzo Church",
    "Andrei Markov",
    "David Blackwell",
    "Richard Courant",
    "Emil Borel",
    "Edmond Laguerre",
    "Sophus Lie",
    "Bernard Bolzano",
    "James Clerk Maxwell",
];

pub const FAMOUS_PHYSICIANS: [&str; 141] = [
    "Hippocrates",
    "Galen",
    "Andreas Vesalius",
    "William Harvey",
    "Edward Jenner",
    "Louis Pasteur",
    "Joseph Lister",
    "Alexander Fleming",
    "Marie Curie",
    "Sigmund Freud",
    "Paul Ehrlich",
    "Robert Koch",
    "René Laennec",
    "Avicenna",
    "Hildegard von Bingen",
    "Thomas Sydenham",
    "Harvey Cushing",
    "William Osler",
    "Joseph Bazalgette",
    "Carl Wunderlich",
    "Christiaan Barnard",
    "Francis Crick",
    "James Watson",
    "Robert Hooke",
    "Claude Bernard",
    "Walter Reed",
    "Elizabeth Blackwell",
    "Ignaz Semmelweis",
    "Alfred Nobel",
    "Camillo Golgi",
    "Santiago Ramón y Cajal",
    "John Snow",
    "Rene Favaloro",
    "Alessandro Volta",
    "Harvey Itano",
    "Paul Farmer",
    "Virginia Apgar",
    "Charles Best",
    "Frederick Banting",
    "Gerty Cori",
    "Rosalind Franklin",
    "Joseph Priestley",
    "Walter Cannon",
    "Karl Landsteiner",
    "Ernst von Bergmann",
    "Jean-Martin Charcot",
    "Emil von Behring",
    "Christoph Hufeland",
    "John Hunter",
    "Max von Pettenkofer",
    "Julius Wagner-Jauregg",
    "Robert Edwards",
    "Baruch Blumberg",
    "Paul Langerhans",
    "Giovanni Battista Morgagni",
    "William Withering",
    "George Washington Carver",
    "Ignaz Semmelweis",
    "John Langdon Down",
    "Gerty Cori",
    "Thomas Hodgkin",
    "Howard Florey",
    "John Snow",
    "Emil Kraepelin",
    "William Stewart Halsted",
    "Hans Selye",
    "Clara Barton",
    "Paul Broca",
    "William Bowman",
    "Thomas Hodgkin",
    "Jean Baptiste Denis",
    "Charles Darwin",
    "Elizabeth Garrett Anderson",
    "Joseph Lister",
    "Christiaan Barnard",
    "Benjamin Rush",
    "Niels Ryberg Finsen",
    "Francis Galton",
    "Carl Jung",
    "Alfred Adler",
    "Ignaz Semmelweis",
    "Wilhelm Röntgen",
    "Gregor Mendel",
    "John Cade",
    "Frederick Banting",
    "Gerty Cori",
    "Walter Reed",
    "Rudolf Virchow",
    "Robert Koch",
    "Edward Jenner",
    "Paul Ehrlich",
    "Christiaan Eijkman",
    "Marie Curie",
    "Sigmund Freud",
    "Harvey Cushing",
    "Hans Asperger",
    "Florence Nightingale",
    "Virginia Apgar",
    "Claude Bernard",
    "Hippocrates",
    "Galen",
    "Avicenna",
    "Andreas Vesalius",
    "William Harvey",
    "Edward Jenner",
    "Joseph Lister",
    "Alexander Fleming",
    "Robert Hooke",
    "Louis Pasteur",
    "Ignaz Semmelweis",
    "Jean-Martin Charcot",
    "Paul Ehrlich",
    "Christoph Hufeland",
    "Harvey Cushing",
    "Walter Reed",
    "Camillo Golgi",
    "Santiago Ramón y Cajal",
    "Thomas Sydenham",
    "John Snow",
    "Elizabeth Blackwell",
    "Harold Gillies",
    "Baruch Blumberg",
    "Emil von Behring",
    "Paul Langerhans",
    "Giovanni Battista Morgagni",
    "William Withering",
    "George Washington Carver",
    "John Hunter",
    "Max von Pettenkofer",
    "Julius Wagner-Jauregg",
    "Robert Edwards",
    "Howard Florey",
    "John Langdon Down",
    "Hans Selye",
    "Clara Barton",
    "Paul Broca",
    "William Bowman",
    "Thomas Hodgkin",
    "Jean Baptiste Denis",
    "Charles Darwin",
    "Elizabeth Garrett Anderson",
];

pub const FAMOUS_BIOLOGISTS: [&str; 128] = [
    "Charles Darwin",
    "Gregor Mendel",
    "Alexander von Humboldt",
    "Carolus Linnaeus",
    "Louis Pasteur",
    "Ernst Haeckel",
    "Barbara McClintock",
    "James Watson",
    "Francis Crick",
    "Rachel Carson",
    "Theodosius Dobzhansky",
    "Rosalind Franklin",
    "Lynn Margulis",
    "Thomas Hunt Morgan",
    "Santiago Ramón y Cajal",
    "Alfred Russel Wallace",
    "Robert Hooke",
    "Antonie van Leeuwenhoek",
    "Joseph Lister",
    "Jean-Baptiste Lamarck",
    "Harvey Cushing",
    "Paul Nurse",
    "Jacques Monod",
    "Sydney Brenner",
    "Hans Krebs",
    "Richard Dawkins",
    "Emil du Bois-Reymond",
    "Erwin Chargaff",
    "Kary Mullis",
    "Francisco J. Ayala",
    "Thomas Cavalier-Smith",
    "Elizabeth Blackburn",
    "Craig Venter",
    "Richard Lenski",
    "G. Evelyn Hutchinson",
    "Gregor Mendel",
    "Max Delbrück",
    "Barbara McClintock",
    "Francisco Mojica",
    "Mary Anning",
    "John Maynard Smith",
    "Julian Huxley",
    "E. O. Wilson",
    "August Weismann",
    "Wilhelm Roux",
    "George Washington Carver",
    "Herbert Spencer",
    "Alfred Kinsey",
    "Richard Owen",
    "Paul Ehrlich",
    "Hans Spemann",
    "Konrad Lorenz",
    "Niko Tinbergen",
    "Theodore Schwann",
    "Matthias Schleiden",
    "Carl Woese",
    "Alfred Wallace",
    "Francis Crick",
    "James Watson",
    "Sewall Wright",
    "J. B. S. Haldane",
    "Rita Levi-Montalcini",
    "Salvador Luria",
    "Max Planck",
    "Hermann Muller",
    "Jean-Baptiste Lamarck",
    "Ivan Pavlov",
    "Camillo Golgi",
    "Emil von Behring",
    "Thomas Hunt Morgan",
    "Charles Lyell",
    "Gregory Mendel",
    "Harald zur Hausen",
    "Elizabeth Blackburn",
    "Craig Venter",
    "Sydney Brenner",
    "Richard Dawkins",
    "Francis Crick",
    "Barbara McClintock",
    "Lynn Margulis",
    "Theodosius Dobzhansky",
    "Rosalind Franklin",
    "Kary Mullis",
    "James Watson",
    "Francisco J. Ayala",
    "Thomas Cavalier-Smith",
    "Hans Krebs",
    "Emil du Bois-Reymond",
    "Richard Lenski",
    "Francisco Mojica",
    "Mary Anning",
    "John Maynard Smith",
    "Julian Huxley",
    "E. O. Wilson",
    "August Weismann",
    "Wilhelm Roux",
    "George Washington Carver",
    "Herbert Spencer",
    "Alfred Kinsey",
    "Richard Owen",
    "Paul Ehrlich",
    "Hans Spemann",
    "Konrad Lorenz",
    "Niko Tinbergen",
    "Theodore Schwann",
    "Matthias Schleiden",
    "Carl Woese",
    "Alfred Wallace",
    "Francis Crick",
    "James Watson",
    "Sewall Wright",
    "J. B. S. Haldane",
    "Rita Levi-Montalcini",
    "Salvador Luria",
    "Max Planck",
    "Hermann Muller",
    "Jean-Baptiste Lamarck",
    "Ivan Pavlov",
    "Camillo Golgi",
    "Emil von Behring",
    "Thomas Hunt Morgan",
    "Charles Lyell",
    "Harald zur Hausen",
    "Elizabeth Blackburn",
    "Craig Venter",
    "Sydney Brenner",
    "Richard Dawkins",
    "Francis Crick",
];

pub const FAMOUS_COMPUTER_SCIENTISTS: [&str; 156] = [
    "Alan Turing",
    "John von Neumann",
    "Donald Knuth",
    "Edsger Dijkstra",
    "Dennis Ritchie",
    "Ken Thompson",
    "Grace Hopper",
    "Ada Lovelace",
    "Tim Berners-Lee",
    "Linus Torvalds",
    "Brian Kernighan",
    "Bjarne Stroustrup",
    "John McCarthy",
    "Marvin Minsky",
    "Alonzo Church",
    "Claude Shannon",
    "Barbara Liskov",
    "Leslie Lamport",
    "Niklaus Wirth",
    "Tony Hoare",
    "Peter Naur",
    "Robert Floyd",
    "Fred Brooks",
    "Andrew Tanenbaum",
    "James Gosling",
    "Guido van Rossum",
    "Richard Stallman",
    "Donald Davies",
    "Vint Cerf",
    "Robert Kahn",
    "Douglas Engelbart",
    "JCR Licklider",
    "Seymour Cray",
    "Jean E. Sammet",
    "Ivan Sutherland",
    "Alan Kay",
    "Robin Milner",
    "David Patterson",
    "John Backus",
    "Raj Reddy",
    "Frances Allen",
    "Stephen Cook",
    "Michael Rabin",
    "Dana Scott",
    "John C. Hennessy",
    "Martin Hellman",
    "Whitfield Diffie",
    "Adi Shamir",
    "Ron Rivest",
    "Leonard Kleinrock",
    "Shafi Goldwasser",
    "Silvio Micali",
    "Andrew Yao",
    "John Carmack",
    "Brendan Eich",
    "Larry Page",
    "Sergey Brin",
    "Jeff Dean",
    "Barbara Simons",
    "Yukihiro Matsumoto",
    "Philip Wadler",
    "Benjamin C. Pierce",
    "Martin Odersky",
    "James Clerk Maxwell",
    "Noam Chomsky",
    "Steve Wozniak",
    "Bill Gates",
    "Steve Jobs",
    "Mark Zuckerberg",
    "John Resig",
    "Donald Knuth",
    "Peter Norvig",
    "Geoffrey Hinton",
    "Yoshua Bengio",
    "Yann LeCun",
    "Sebastian Thrun",
    "Andrew Ng",
    "David Chaum",
    "Nick Szabo",
    "Hal Finney",
    "Judea Pearl",
    "Terry Winograd",
    "Carver Mead",
    "Ray Kurzweil",
    "David Gelernter",
    "Leslie Valiant",
    "Randy Pausch",
    "Manuel Blum",
    "Butler Lampson",
    "Luca Cardelli",
    "Ken Iverson",
    "Bertrand Meyer",
    "Robert Tarjan",
    "John Reif",
    "David MacKay",
    "Tom Knight",
    "Danny Hillis",
    "Gerald Jay Sussman",
    "Guy Steele",
    "Paul Graham",
    "Joe Armstrong",
    "Simon Peyton Jones",
    "Chris Lattner",
    "David Heinemeier Hansson",
    "Brendan Gregg",
    "Brian Cantrill",
    "Theo de Raadt",
    "Daniel J. Bernstein",
    "Nadia Eghbal",
    "Jean-Raymond Abrial",
    "Turing Award Winners",
    "Richard Hamming",
    "Rasmus Lerdorf",
    "Kent Beck",
    "Martin Fowler",
    "Ward Cunningham",
    "Grady Booch",
    "Ivar Jacobson",
    "Erich Gamma",
    "Anders Hejlsberg",
    "Robert C. Martin",
    "Dave Thomas",
    "Yukihiro Matsumoto",
    "Chris Okasaki",
    "Benjamin Franklin",
    "Alan Perlis",
    "Judea Pearl",
    "Andrew Tanenbaum",
    "Robert Dewar",
    "Doug McIlroy",
    "Tom Love",
    "David Gries",
    "Fernando J. Corbató",
    "Robert Sedgewick",
    "Brian W. Kernighan",
    "Ken Thompson",
    "Dennis Ritchie",
    "John Mashey",
    "Michael Stonebraker",
    "Eric Brewer",
    "Werner Vogels",
    "L Peter Deutsch",
    "Dan Ingalls",
    "Jef Raskin",
    "Mitchell Baker",
    "Ada Lovelace",
    "Mary Kenneth Keller",
    "Sophie Wilson",
    "Margaret Hamilton",
    "Radia Perlman",
    "Joan Clarke",
    "Jean Bartik",
    "Lynn Conway",
    "Karen Spärck Jones",
    "Elizabeth Feinler",
    "Anita Borg",
];
