pub const CHEMICAL_ELEMENTS: [&str; 118] = [
    "Hydrogen",
    "Helium",
    "Lithium",
    "Beryllium",
    "Boron",
    "Carbon",
    "Nitrogen",
    "Oxygen",
    "Fluorine",
    "Neon",
    "Sodium",
    "Magnesium",
    "Aluminium",
    "Silicon",
    "Phosphorus",
    "Sulfur",
    "Chlorine",
    "Argon",
    "Potassium",
    "Calcium",
    "Scandium",
    "Titanium",
    "Vanadium",
    "Chromium",
    "Manganese",
    "Iron",
    "Cobalt",
    "Nickel",
    "Copper",
    "Zinc",
    "Gallium",
    "Germanium",
    "Arsenic",
    "Selenium",
    "Bromine",
    "Krypton",
    "Rubidium",
    "Strontium",
    "Yttrium",
    "Zirconium",
    "Niobium",
    "Molybdenum",
    "Technetium",
    "Ruthenium",
    "Rhodium",
    "Palladium",
    "Silver",
    "Cadmium",
    "Indium",
    "Tin",
    "Antimony",
    "Tellurium",
    "Iodine",
    "Xenon",
    "Cesium",
    "Barium",
    "Lanthanum",
    "Cerium",
    "Praseodymium",
    "Neodymium",
    "Promethium",
    "Samarium",
    "Europium",
    "Gadolinium",
    "Terbium",
    "Dysprosium",
    "Holmium",
    "Erbium",
    "Thulium",
    "Ytterbium",
    "Lutetium",
    "Hafnium",
    "Tantalum",
    "Tungsten",
    "Rhenium",
    "Osmium",
    "Iridium",
    "Platinum",
    "Gold",
    "Mercury",
    "Thallium",
    "Lead",
    "Bismuth",
    "Polonium",
    "Astatine",
    "Radon",
    "Francium",
    "Radium",
    "Actinium",
    "Thorium",
    "Protactinium",
    "Uranium",
    "Neptunium",
    "Plutonium",
    "Americium",
    "Curium",
    "Berkelium",
    "Californium",
    "Einsteinium",
    "Fermium",
    "Mendelevium",
    "Nobelium",
    "Lawrencium",
    "Rutherfordium",
    "Dubnium",
    "Seaborgium",
    "Bohrium",
    "Hassium",
    "Meitnerium",
    "Darmstadtium",
    "Roentgenium",
    "Copernicium",
    "Nihonium",
    "Flerovium",
    "Moscovium",
    "Livermorium",
    "Tennessine",
    "Oganesson",
];

pub const MATHEMATICAL_FUNCTIONS: [&str; 131] = [
    "Absolute",
    "Additive Inverse",
    "Algebraic",
    "Algebraic Closure",
    "Analytic",
    "Antiderivative",
    "Arc Cosine",
    "Arc Sine",
    "Arc Tangent",
    "Bessel",
    "Beta",
    "Binomial",
    "Ceiling",
    "Characteristic",
    "Circle",
    "Circular",
    "Composite",
    "Conjugate",
    "Cosine",
    "Cotangent",
    "Cosecant",
    "Derivative",
    "Dirac",
    "Exponential",
    "Factorial",
    "Floor",
    "Fourier",
    "Gamma",
    "Gaussian",
    "Geometric",
    "Harmonic",
    "Heaviside",
    "Hyperbolic Cosine",
    "Hyperbolic Sine",
    "Hyperbolic Tangent",
    "Identity",
    "Imaginary",
    "Indicator",
    "Integral",
    "Inverse",
    "Jacobi",
    "Lambert",
    "Laplace",
    "Legendre",
    "Logarithm",
    "Logistic",
    "Möbius",
    "Modulus",
    "Multiplicative Inverse",
    "Normal",
    "Orthogonal",
    "Partial Derivative",
    "Permutation",
    "Pi",
    "Prime",
    "Probability",
    "Quadratic",
    "Radical",
    "Radius",
    "Rational",
    "Real",
    "Reciprocal",
    "Sine",
    "Sigmoid",
    "Square",
    "Square Root",
    "Step",
    "Summation",
    "Tangent",
    "Taylor",
    "Theta",
    "Trigonometric",
    "Unit",
    "Vector",
    "Wavelet",
    "Zeta",
    "Algebraic Number",
    "Analytic Continuation",
    "Arithmetic",
    "Bernoulli",
    "Cauchy",
    "Chebyshev",
    "Clenshaw",
    "Complex",
    "Convolution",
    "Definite Integral",
    "Elliptic",
    "Error",
    "Exponential Decay",
    "Fourier Transform",
    "Gamma Function",
    "Gaussian Integral",
    "Geometric Progression",
    "Hermite",
    "Hessian",
    "Holomorphic",
    "Imaginary Unit",
    "Indicator Function",
    "Integral Transform",
    "Jacobian",
    "Laplace Transform",
    "Laurent",
    "Legendre Polynomial",
    "Linear",
    "Logarithmic Integral",
    "Minkowski",
    "Modular",
    "Neumann",
    "Normal Distribution",
    "Orthogonal Polynomial",
    "Partial Sum",
    "Periodic",
    "Probability Density",
    "Probability Mass",
    "Quadratic Formula",
    "Rational Function",
    "Real Number",
    "Recurrence",
    "Riemann",
    "Sigmoid Function",
    "Spherical",
    "Square Wave",
    "Stirling",
    "Summation Notation",
    "Taylor Series",
    "Trigonometric Function",
    "Unit Step",
    "Unit Vector",
    "Vector Space",
    "Wave Function",
    "Z-Transform",
];
