pub const SPORTS: [&str; 121] = [
    "Football",
    "Basketball",
    "Tennis",
    "Cricket",
    "Baseball",
    "Golf",
    "Rugby",
    "American Football",
    "Ice Hockey",
    "Volleyball",
    "Table Tennis",
    "Badminton",
    "Swimming",
    "Athletics",
    "Cycling",
    "Boxing",
    "Wrestling",
    "Gymnastics",
    "Ski",
    "Snowboard",
    "Skateboard",
    "Surf",
    "Karate",
    "Judo",
    "Taekwondo",
    "Fencing",
    "Shooting",
    "Archery",
    "Weightlifting",
    "Rowing",
    "Canoe",
    "Kayak",
    "Handball",
    "Lacrosse",
    "Field Hockey",
    "Motorsport",
    "Formula One",
    "Motorcycle Racing",
    "Horse Racing",
    "Equestrian",
    "Diving",
    "Curling",
    "Triathlon",
    "Bobsleigh",
    "Skeleton",
    "Speed Skating",
    "Figure Skating",
    "Luge",
    "Roller Derby",
    "Ultimate Frisbee",
    "Squash",
    "Powerlifting",
    "Mixed Martial Arts",
    "Water Polo",
    "Sailing",
    "Climbing",
    "Darts",
    "Snooker",
    "Bowling",
    "Chess",
    "Esports",
    "Parkour",
    "Bull Riding",
    "Kite Surf",
    "Wakeboard",
    "Bodybuilding",
    "Fishing",
    "Bowls",
    "Beach Volleyball",
    "CrossFit",
    "Gaelic Football",
    "Hurling",
    "Polo",
    "Softball",
    "Speedway",
    "Floorball",
    "Netball",
    "Pickleball",
    "Roller Hockey",
    "Snowmobiling",
    "Street Luge",
    "Synchronized Swimming",
    "Trampoline",
    "Water Ski",
    "Windsurf",
    "Yoga",
    "Zumba",
    "Air Racing",
    "Arm Wrestling",
    "Base Jumping",
    "BMX",
    "Caving",
    "Cheerleading",
    "Cross-Country Running",
    "Disc Golf",
    "Freediving",
    "Gliding",
    "Hang Gliding",
    "Ice Climbing",
    "Jet Ski",
    "Kendo",
    "Korfball",
    "Motocross",
    "Mountain Biking",
    "Orienteering",
    "Paragliding",
    "Rafting",
    "Rodeo",
    "Roller Skating",
    "Sandboarding",
    "Ski Jumping",
    "Skydiving",
    "Snowshoeing",
    "Speed Climbing",
    "Strongman",
    "Sumo Wrestling",
    "Surf Lifesaving",
    "Tchoukball",
    "Underwater Hockey",
    "Wood Chopping",
    "Zorbing",
];
