pub const TYPES_OF_CLOUDS: [&str; 137] = [
    "Cirrus",
    "Cirrostratus",
    "Cirrocumulus",
    "Altostratus",
    "Altocumulus",
    "Nimbostratus",
    "Stratus",
    "Stratocumulus",
    "Cumulus",
    "Cumulonimbus",
    "Towering Cumulus",
    "Lenticular",
    "Mammatus",
    "Contrail",
    "Fog",
    "Mist",
    "Haze",
    "Smoke",
    "Dust",
    "Volcanic Ash",
    "Wall Cloud",
    "Shelf Cloud",
    "Anvil Cloud",
    "Virga",
    "Pannus",
    "Roll Cloud",
    "Arcus",
    "Kelvin-Helmholtz",
    "Noctilucent",
    "Radiation Fog",
    "Advection Fog",
    "Upslope Fog",
    "Evaporation Fog",
    "Freezing Fog",
    "Frontal Fog",
    "Lake-Effect Snow",
    "Snow Squall",
    "Ice Pellets",
    "Graupel",
    "Virga",
    "Fog Bow",
    "Cloud Streets",
    "Cloud Bands",
    "Cloud Streets",
    "Altocumulus Castellanus",
    "Stratiformis",
    "Fumulus",
    "Cumulus Humilis",
    "Cumulus Mediocris",
    "Cumulus Congestus",
    "Cirrus Fibratus",
    "Cirrus Uncinus",
    "Cirrus Spissatus",
    "Cirrus Intortus",
    "Altostratus Opacus",
    "Altostratus Translucidus",
    "Altocumulus Lenticularis",
    "Altocumulus Floccus",
    "Altocumulus Stratiformis",
    "Nimbostratus Praecipitatio",
    "Stratus Nebulosus",
    "Stratus Fractus",
    "Stratocumulus Stratiformis",
    "Stratocumulus Lenticularis",
    "Cumulonimbus Calvus",
    "Cumulonimbus Capillatus",
    "Cumulonimbus Incus",
    "Cumulonimbus Pileus",
    "Cumulonimbus Mammatus",
    "Pyrocumulus",
    "Asperitas",
    "Volutus",
    "Homogenitus",
    "Fluctus",
    "Undulatus",
    "Lenticularis",
    "Radiatus",
    "Duplicatus",
    "Translucidus",
    "Perlucidus",
    "Intortus",
    "Murus",
    "Fractus",
    "Virga",
    "Pileus",
    "Capillatus",
    "Incus",
    "Calvus",
    "Spissatus",
    "Fibratus",
    "Uncinus",
    "Castellanus",
    "Floccus",
    "Nebulosus",
    "Stratiformis",
    "Congestus",
    "Humilis",
    "Mediocris",
    "Praecipitatio",
    "Fulguritus",
    "Altocumulus Perlucidus",
    "Altostratus Duplicatus",
    "Nimbostratus Praecipitatio",
    "Stratocumulus Duplicatus",
    "Cumulus Praecipitatio",
    "Cumulus Radiatus",
    "Cumulus Fractus",
    "Cirrostratus Nebulosus",
    "Cirrostratus Fibratus",
    "Cirrostratus Duplicatus",
    "Cirrostratus Spissatus",
    "Stratus Opacus",
    "Stratus Perlucidus",
    "Stratus Translucidus",
    "Stratus Duplicatus",
    "Fog Stratus",
    "Mist Stratus",
    "Haze Stratus",
    "Smoke Stratus",
    "Dust Stratus",
    "Volcanic Ash Stratus",
    "Wall Stratus",
    "Shelf Stratus",
    "Anvil Stratus",
    "Virga Stratus",
    "Pannus Stratus",
    "Roll Stratus",
    "Arcus Stratus",
    "Kelvin-Helmholtz Stratus",
    "Noctilucent Stratus",
    "Radiation Stratus",
    "Advection Stratus",
    "Upslope Stratus",
    "Evaporation Stratus",
    "Freezing Stratus",
    "Frontal Stratus",
    "Lake-Effect Stratus",
];
